### ISSUE TITLE
What differences with twitteR?

### ISSUE THREAD

**Issue by masalmon** [mkearney/rtweet#1]
I knew the https://github.com/geoffjentry/twitteR package by @geoffjentry -> what are the differences between both packages? Thanks.

**Comment by geoffjentry** [comment]
A quick peek makes this look like a more modern implementation which actually has someone working on it ;)

If rtweet is intended for full use, I'd personally start directing people over here simply because I haven't had time to work on twitteR for a few years now. I've mainly been living off of pull requests.

**Comment by masalmon** [comment]
Oh and from https://github.com/leeper/webservices I see there's also https://github.com/joyofdata/RTwitterAPI from @joyofdata

**Comment by mkearney** [comment]
My only hesitation is that I'm new to package maintenance, and I'd hate to let people down. With that said, I am committed to maintaining the package for a while (and I have some people willing to help me if I need it), so I'd happily take over and save you from the work (you've obviously done way more than your fair share to get R users access to Twitter data). So whatever you think totally works for me :).

**Comment by masalmon** [comment]
@mkearney by the way since Twitter data has a scientific application (which is why you wrote the package?), why not submit it to rOpenSci? See instructions [here](https://github.com/ropensci/onboarding/) As a new package maintainer myself reading their packaging guidelines + receiving feedback helped me a lot, and rOpenSci would advertise for your package.

**Comment by mkearney** [comment]
@masalmon That seems like a good idea to me. Thanks for the link!

**Comment by masalmon** [comment]
rOpenSci is really awesome ☺ Don't hesitate to ping me if you need help on anything!

**Comment by geoffjentry** [comment]
@mkearney I don't want to push you into anything :) Like I said, I didn't know what you viewed as the current state of `rtweet` nor what your goals were. 

I'll admit that I've been meaning to look to find a new maintainer for `twitteR` but I could solve the same issue by having a successor package to point people to. If this is a torch you're interested in picking up we should chat, if not no worries :)

**Comment by mkearney** [comment]
@geoffjentry I'm very interested--sending a message to your gmail account right now! (Let me know if you don't get it or if you prefer I send it to a different address)

**Comment by mkearney** [comment]
For the sake of linking/documenting {rtweet} as the successor pkg to {twitteR} here's a screen shot (taken May 15, 2019) of the current deprecation-in-favor-of-rtweet note (commit occurred Sep 1, 2016) in the README of {twitteR} https://github.com/geoffjentry/twitteR
![Screen Shot 2019-05-15 at 12 38 24 PM](https://user-images.githubusercontent.com/13401460/57796778-89673280-770e-11e9-8a95-17681386be3e.png)
