### ISSUE TITLE
Ability to construct the token by directly providing ACCESSTOKEN and ACCESSTOKENSECRET

### ISSUE THREAD

**Issue by justa9** [mkearney/rtweet#102]
Hello.

Is there a way to construct the token by directly providing ACCESSTOKEN and ACCESSTOKENSECRET? This would help mitigate the problem with installations on older OS's (Windows XP reports an IDN-related error in KERNEL32.dll).

Thank you.

**Comment by digital-dharma** [comment]
@justa9 - Oddly, following the general connection instructions provided I get an error:

**Code:**
```
twitter_token <-
create_token(
  app = "Analysis of Political Tweets",
  consumer_key = consumer_key,
  consumer_secret = consumer_secret)
```

**Results:**
`Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission, : Unauthorized (HTTP 401).`

In other implementations of Twitter APIs, I have seen the access token and access secret also leveraged - Which do not appear to be here.

Are you hitting the same issue?

**Comment by justa9** [comment]
No, I just need to automate the procedure of collecting tweets in a portable manner.

As a side note, ensure you have correctly set the callback address in the app as ```http://localhost:1410/```

**Comment by mkearney** [comment]
I'm not exactly sure what's being asked here. The `create_token()` function accepts both keys and should work if you follow the [auth vignette](http://rtweet.info/articles/auth.html).

Once you've created a token, you can save it and read it into R using `saveRDS` and `readRDS`. That should allow you to read a token and then specify it in rtweet calls

### 1. Create a token (code taken from auth vignette)

``` r
## whatever name you assigned to your created app
appname <- "rtweet_token"

## api key (example below is not a real key)
key <- "XYznzPFOFZR2a39FwWKN1Jp41"

## api secret (example below is not a real key)
secret <- "CtkGEWmSevZqJuKl6HHrBxbCybxI1xGLqrD5ynPd9jG0SoHZbD"

## create token named "twitter_token"
twitter_token <- create_token(
    app = appname,
    consumer_key = key,
    consumer_secret = secret
)
```

### 2. Save token

``` r
## save token to wherever
saveRDS(twitter_token, "~/path/to/twitter_token.rds")
```

### 3. Read token and use in function call

``` r
## read token from wherever
twitter_token <- readRDS("~/path/to/twitter_token.rds")

## pass token to fun call
rt <- search_tweets("rstats", n = 200, token = twitter_token)

## view data
rt
```

**Comment by justa9** [comment]
Thank you for the detailed explanation and sincere apologies for the needless bug report.
