### ISSUE TITLE
Shiny OAuth

### ISSUE THREAD

**Issue by JohnCoene** [mkearney/rtweet#104]
Hi,

Is there any way we could have the OAuth work outside of an interactive environment so that we could use it with Shinyapps. I'm talking about the `create_token()` function.

`create_token()` works in local Shiny app but I can't deploy it.

**Comment by JohnCoene** [comment]
Nevermind it now seems to work thanks to `httr`'s `.httr-oauth`

**Comment by rajaramana** [comment]
Hi @JohnCoene, this is the exact problem that i am facing. Could you please tell me, how you were able to solve this issue?

Thanks in advance.

**Comment by JohnCoene** [comment]
Install retweet from GitHub, save token as .rds then read .rds

**Comment by rajaramana** [comment]
@JohnCoene Thank you very much. That worked!!
