### ISSUE TITLE
entities urls

### ISSUE THREAD

**Issue by andreamamprin** [mkearney/rtweet#105]
Hi mkearney.
First of all, thanks for the great job!

Comparing the CRAN version of the package (0.4.0) and the github one (0.4.8), I'm not able to find the urls, urls_display, urls_expanded columns. Is there any issue? 

In the meantime, thank you for your attention!

**Comment by mkearney** [comment]
Some names have bene modified to be more descriptive and/or to be more unique across different data types (tweets vs users). These variables should now appear as "media_url", "media_t.co", and "media_expanded_url".

**Comment by mkearney** [comment]
Let me know if you have any more problems with this. For now I'm closing this issue, but I'd be happy to reopen. Also, I'm open to suggestions about naming conventions, btw.
