### ISSUE TITLE
users_data returns wrong variables

### ISSUE THREAD

**Issue by swood-ecology** [mkearney/rtweet#106]
I've noticed that the users_data function returns different variables depending on how many tweets are searched for. Here's a first search:
```
t1 <- search_tweets("soil health", n = 100, exact = TRUE, retryonratelimit=T, include_rts = TRUE)
users_data(t1) %>%
  head()
```
Here's a second search:
```
t2 <- search_tweets("soil health", n = 100000, exact = TRUE, retryonratelimit=T, include_rts = TRUE)
users_data(t2) %>%
  head()
```
The variables returned by users_data for the two searches are different:
`names(users_data(t1))==names(users_data(t2))`
```
[1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[14] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[27] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
Warning message:
In names(users_data(t1)) == names(users_data(t2)) :
  longer object length is not a multiple of shorter object length
```

**Comment by mkearney** [comment]
The users data correspond to the rows in the tweets data. So, assuming the search has an ample pool of matching tweets, if you search `n = 100` then you'll be returned data on 100 observations. Each observation consists of both tweets *and* users data. Thus, `n = 100` should return 100 rows of tweets data and 100 rows of users data while `n = 10000` should return 10000 rows of tweets data and 10000 rows of users data. Of course, if the same user is responsible for multiple tweets, then there may be some redundancies in your data frame of users data, but that's a reflection of the APIs design.

If that doesn't make sense or if I misunderstood your issue, please let me know!
