### ISSUE TITLE
example for search_users() function throws error

### ISSUE THREAD

**Issue by JVAdams** [mkearney/rtweet#107]
When I run the first example for the search_users() function, I get an error.

```
library(rtweet)
pc <- search_users(q = "political communication", n = 1000)
```

_Error in UseMethod("seach_users") : 
  no applicable method for 'seach_users' applied to an object of class "character"_

**Comment by mkearney** [comment]
This should now be fixed. My attempt to simplify some of these functions got disrupted by a recent move. Thank you for pointing out this lingering issue!
