### ISSUE TITLE
User IDs returned as double, not character

### ISSUE THREAD

**Issue by noamross** [mkearney/rtweet#11]
I've noticed that when running `get_followers()` or `get_friends()` User IDs are returned as double, like so:

```
          value
          <dbl>
1  4.113280e+07
2  3.977203e+08
3  1.580207e+09
4  7.538385e+17
5  3.177425e+09
6  1.792013e+08
7  1.027735e+08
8  1.687261e+09
9  1.298028e+08
10 3.050178e+09
# ... with 530 more rows
```

Perhaps these should be returned as character values by default?

**Comment by mkearney** [comment]
Good catch. Twitter encourages use of string variables since user_ids can be longer than what is allowed by many numeric or integer classes, but requesting ids seems to want to produce numeric classes. Either way, it should be fixed now!
