### ISSUE TITLE
Prescheduled tweets

### ISSUE THREAD

**Issue by higgi13425** [mkearney/rtweet#111]
Could you add a functionality to post tweets at specific days and times in the future? perhaps via Tweetdeck?
Thinking about setting this up from a spreadsheet with columns for tweet, image, date, and time.
Could be a google sheet, and use googlesheets package and pipe these in to rTweet

**Comment by mkearney** [comment]
It'd have to include interaction with another package or external-to-R-and-Twitter API. If there's anything I can do to make that easier, I'd be happy to try! But otherwise I'd prefer not to go down that road.
