### ISSUE TITLE
users_data not always working

### ISSUE THREAD

**Issue by michelleclements** [mkearney/rtweet#119]
Hi there, 

users_data sometimes doesn't return anything. I'm afraid I can't give a reproducible example as I can't figure out what's going on. 
It seems to happen more when n > 10000 in search_tweets so I'm not sure if it's something to do with rate limits being hit but an error not being thrown. However, it doesn't seem to be to do with how many tweets are actually returned - just that n itself is a low number. 

I can only suggest running the code below a few times to see if it happens to you too. Thanks

tweets <- search_tweets( "rstats", 
                         n = 10000,
                         retryonratelimit = T , 
                         include_rts = F, 
                         language = "en", 
                         type = "mixed")

users <- users_data(tweets)
nrow(users)

tweets2 <- search_tweets( "rstats", 
                         n = 18000,
                         retryonratelimit = T , 
                         include_rts = F, 
                         language = "en", 
                         type = "mixed")

users2 <- users_data(tweets2)
nrow(users2)

**Comment by mkearney** [comment]
@michelleclements Good catch! I'm going to run some tests with `retryonratelimit = TRUE` but for now the fix has resolved your issue. 

Btw, if your goal is to maximize the number of tweets returned (really if you want more than a couple thousand), then you might be better of sticking with the default `type = "recent"`. I don't believe the pagination will function the same if the result type is "mixed" or "popular."

**Comment by michelleclements** [comment]
great - thank you!

I'm trying to have a look at at bunch of search terms to see how much activity there is around each. I have been using 'mixed' to make sure that I get the most main tweets which, I think, is then kinda topped up with recent. Please shout if you think that seems like a terrible idea. 

Also, when I'm installing rweet using devtools on windows (install_github("mkearney/rtweet")) I'm getting an error (Installation failed: cannot open file '...AppData/Local/Temp/RtmpQ5pQFq/devtoolsd4139d2f21/mkearney-rtweet-118d917/R/ *NeoTree*': Invalid argument). It was working earlier today and it doesn't look like the R folder is being copied down properly. Given it was working today, I don't suppose it was maybe something with the last commit?

**Comment by mkearney** [comment]
Whooopsies. Should be fixed now :)

**Comment by michelleclements** [comment]
Thank you!
