### ISSUE TITLE
get_timeline is missing the documentation for `...`

### ISSUE THREAD

**Issue by jsta** [mkearney/rtweet#12]
Should the documentation for `...` from the `search_tweets` function be copied over to `get_timeline`? I am thinking specifically about the option to turn off RTs.

**Comment by jsta** [comment]
I would submit a PR but I already have one pending.

**Comment by mkearney** [comment]
Yep. Thank you. It's fixed now. Next week (assuming everything goes to plan and I send out my dissertation prospectus this week), I'm going to make a final push on adding as much documentation as I can before next cran release.
