### ISSUE TITLE
export for list_statuses is missing 

### ISSUE THREAD

**Issue by dmpe** [mkearney/rtweet#121]
https://github.com/mkearney/rtweet/blob/master/R/lists-statuses.R#L34

#' @export is missing there

**Comment by mkearney** [comment]
That was somewhat intentional. I'm trying to hold back the API functions that are not ready for the limelight (if new, if tests have yet to be implemented, etc.). You can always export the function manually, e.g., `rtweet:::lists_statuses(...)`.

**Comment by mkearney** [comment]
There are now multiple `lists_` functions accessing various Twitter APIs. These functions still haven't received the same attention as some of the others like `search_tweets`, `get_timelines`, `lookup_statuses` and the like, but they should get the job done!

**Comment by dmpe** [comment]
thanks
