### ISSUE TITLE
Need to add parsing logic for "full_text" attribute in extended tweet

### ISSUE THREAD

**Issue by robtougher** [mkearney/rtweet#122]
If I call "search_tweets" and pass "tweet_mode=extended" (which gets passed to the URL), the response from the Twitter API puts the tweet's text in a "full_text" field, and not "text". It looks like the rtweet library does not parse and collect this full_text field. The data frame the I receive from the library has NA in text, and no full_text field.

I tried making a few changes locally to add parsing for full_text, and while I was able to get it to work for my use case, I'm not sure it covers all scenarios.

**Comment by mkearney** [comment]
It does. By default it includes tweet_mode=extended in requests and then renames the full_text field to "text." I did that originally because it seemed like the phased in full text in such a way that it broke the parser. Renaming to "text" allowed me to keep the parsing routines...and I'm not really sure what the benefit is of returning the non-extended tweet text.

**Comment by robtougher** [comment]
Thanks! Hmmmm - I just downloaded the package source [1] and extracted, and then did a "Find in Files" for both "extended" and "full_text" and I don't see either of them in the files. Is this happening in another library somewhere that I'm not seeing?

[1] https://cran.r-project.org/src/contrib/rtweet_0.4.0.tar.gz

**Comment by robtougher** [comment]
I'm clicking around the code in github and I'm realizing that the list of file names for the R sources on github are different than the ones I got in the CRAN source package. Is one like a stable version, and the other a latest?

**Comment by syphon5** [comment]
Is this feature in CRAN or dev? I pulled tweets in CRAN and see concatenation.

**Comment by LeszekDiez** [comment]
I'm using rtweet which I installed using the "install.packages" from my rstudio, but I'm still getting truncated texts.  If I add the tweet_mode='extended', then I get NA in the text column.

**Comment by robtougher** [comment]
If I install rtweet in R via the below, I do get the most up-to-date sources. Calling "search_tweets" will return a tibble which contains a field named "text" that has the extended tweet's text. So it appears just to be a situation where CRAN is a bit behind github.

library(devtools)
install_github("mkearney/rtweet")
library(rtweet)
