### ISSUE TITLE
Latest github ver: Error in as.POSIXct.default

### ISSUE THREAD

**Issue by syphon5** [mkearney/rtweet#123]
```
library("devtools")
#install_github("mkearney/rtweet")
library(rtweet)

## name assigned to created app
appname <- "App Name"
## api key (example below is not a real key)
key <- "XYZ"
## api secret (example below is not a real key)
secret <- "123"
twitter_token <- create_token(
  app = appname,
  consumer_key = key,
  consumer_secret = secret)

# Get Stevonio tweets
stevonio_tweets <- get_timeline("stevonio", n = 10)
head(stevonio_tweets)
```

Console: 

> Auto-refreshing stale OAuth token.
Error in as.POSIXct.default(x, origin = "1970-01-01", tz = "UTC") : 
  do not know how to convert 'x' to class “POSIXct”

Works fine on CRAN version, but I need dev version for the extended tweet functionality.

**Comment by mkearney** [comment]
Can you post the output to the following code:

``` r
packageVersion("rtweet")
sessionInfo()
```

**Comment by syphon5** [comment]
```
> packageVersion("rtweet")
[1] ‘0.5.13’
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rtweet_0.5.13   devtools_1.12.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9   digest_0.6.11 withr_1.0.2   R6_2.2.0      jsonlite_1.5  git2r_0.18.0  magrittr_1.5  httr_1.3.1    rlang_0.1.1   curl_2.3      tools_3.3.2   bit64_0.9-7   readr_1.1.1   bit_1.1-12    hms_0.3       memoise_1.0.0
[17] openssl_0.9.7 knitr_1.15.1  tibble_1.3.4 
```

**Comment by syphon5** [comment]
I removed/installed your new version and still have the issue.

Error:

> Auto-refreshing stale OAuth token.
Error in as.POSIXct.default(x, origin = "1970-01-01", tz = "UTC") : 
  do not know how to convert 'x' to class “POSIXct”

Your requested info:
```
> packageVersion("rtweet")
[1] ‘0.5.14’
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rtweet_0.5.14   devtools_1.12.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9   digest_0.6.11 withr_1.0.2   R6_2.2.0      jsonlite_1.5  git2r_0.18.0  magrittr_1.5 
 [8] httr_1.3.1    rlang_0.1.1   curl_2.3      tools_3.3.2   bit64_0.9-7   readr_1.1.1   bit_1.1-12   
[15] hms_0.3       memoise_1.0.0 openssl_0.9.7 knitr_1.15.1  tibble_1.3.4 
```

**Comment by llsigerson** [comment]
I'm having the same problem:
get_followers("387082640")
Error in as.POSIXct.default(x, origin = "1970-01-01", tz = "UTC") : 
  do not know how to convert 'x' to class “POSIXct”

the same thing happens with the get_friends and get_timeline functions. Strangely, there's no problem if I enter the screen name rather than the user ID. Nothing obviously unusual about this account.

Updating to R 3.4.2 didn't change anything (my info below).

packageVersion("rtweet")
[1] ‘0.5.14’
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RCurl_1.95-4.8 bitops_1.0-6   httr_1.3.1     ROAuth_0.9.6   httpuv_1.3.5   rtweet_0.5.14 

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.13    digest_0.6.12   withr_2.0.0     R6_2.2.2        jsonlite_1.5    git2r_0.19.0   
 [7] magrittr_1.5    rlang_0.1.2     curl_3.0        devtools_1.13.3 tools_3.4.2     bit64_0.9-7    
[13] readr_1.1.1     bit_1.1-12      hms_0.3         compiler_3.4.2  memoise_1.1.0   openssl_0.9.7  
[19] tibble_1.3.4

**Comment by llsigerson** [comment]
To follow up, it looks like it's related to the token that's used:
get_friends("llsigerson")
Error in as.POSIXct.default(x, origin = "1970-01-01", tz = "UTC") : 
  do not know how to convert 'x' to class “POSIXct”
> get_friends("llsigerson", token=get_tokens()[[12]])
# A tibble: 229 x 2
         user            user_id
        <chr>              <chr>
 1 llsigerson 910938360461611008
 2 llsigerson         1240421984
 3 llsigerson 902965228937379842
 4 llsigerson           17732153
 5 llsigerson         3327720838
 6 llsigerson         3079929572
 7 llsigerson           37213193
 8 llsigerson          582161546
 9 llsigerson           24897626
10 llsigerson         1529809286
# ... with 219 more rows

It looks to me like it's coming up only when token=NULL,  and when the function is checking whether a token is non-exhausted. If  the application/rate_status query for that token is exhausted, then this error is returned.
I'm working around this problem for now, but I think I've pinpointed when it comes up (usually when sending a lot of queries quickly). Happy to provide more info.

**Comment by mkearney** [comment]
Thank you, @llsigerson, for looking into this. I was starting to lose my mind a bit trying to figure out what was going wrong with the conversion of date-time vectors. Your explanation makes sense, and I should be able to implement a fix for it later this afternoon. Functions should be returning an error (or warning message) instead of trying to format the returned object into tweets data.

**Comment by llsigerson** [comment]
Sure, glad this was helpful info, good luck!

**Comment by pssguy** [comment]
As this is still an open issue am I right in that this is not yet fixed?

This is my experience
I am mapping a vector of user_ids to get their timelines with get_timeline and printing their id first
So I hit the problem here

```r
...
[1] 4675087285
[1] 3402033682
Error in as.POSIXct.default(x, origin = "1970-01-01", tz = "UTC") : 
  do not know how to convert 'x' to class “POSIXct”

problem <- get_timeline(3402033682,n=200)
str(problem)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	0 obs. of  0 variables
 - attr(*, "users")='data.frame':	0 obs. of  0 variables

 user <-lookup_users(3402033682)
 str(user)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	1 obs. of  20 variables:
 $ user_id               : chr "3402033682"
 $ name                  : chr "SK13"
 $ screen_name           : chr "Kinsville13"
 $ location              : chr ""
 $ description           : chr "London, Arsenal FC."
 $ url                   : logi NA
 $ protected             : logi TRUE
 $ followers_count       : int 1093
 $ friends_count         : int 3694
 $ listed_count          : int 5
 $ statuses_count        : int 7727
 $ favourites_count      : int 948
 $ account_created_at    : POSIXct, format: "2015-08-03 23:09:26"
 $ verified              : logi FALSE
 $ profile_url           : chr NA
 $ profile_expanded_url  : chr NA
 $ account_lang          : chr "en"
 $ profile_banner_url    : chr "https://pbs.twimg.com/profile_banners/3402033682/1478552297"
 $ profile_background_url: chr "http://abs.twimg.com/images/themes/theme1/bg.png"
 $ profile_image_url     : chr "http://pbs.twimg.com/profile_images/753662034722582529/V0hQ0oqi_normal.jpg"
 - attr(*, "tweets")='data.frame':	0 obs. of  0 variables


# try  not parsing time_line()
 x <-get_timeline(3402033682,n=200, parse=FALSE)

 x$V1
[[1]]
[[1]]$request
[1] "/1.1/statuses/user_timeline.json"

[[1]]$error
[1] "Not authorized."

attr(,"users")

## Physically look at users timeline
y <- lookup_users(3402033682)
y$screen_name
[1] "Kinsville13"
```

This user does exist but examining on twitter at first glance all actions appear to be replies
This is on v 0.5.25

**Comment by mkearney** [comment]
This should now return a data frame with zero rows. The user data is still returned for your example, @pssguy, but when I look that user up at Twitter.com, it says it's a private account...which would explain why `get_timeline()` results in the "not authorized" response from Twitter.

**Comment by mkearney** [comment]
I'm getting a slightly different result with the most recent version. But it makes me think this is related to how the user IDs have been stored. IF you saved some data using `save.csv`, for example, they were likely saved as numeric values using scientific notation and, often, some rounding method depending on the number of digits. So when you re-read the data back into R, they were treated as approximations of numeric values.

I've started to update the save functions (`save_as_csv` and `write_as_csv`) so they automatically paste prepend an "x" at the beginning of each ID string. This would prevent the internal R processes from treating the values as numeric.

If you're working in R anyway, I'd encourage you to use the `saveRDS()` function, which is fast, and a lot better at preserving the structure of data.

``` r
> 
> ## load rtweet package
> library(rtweet)
> 
> ## user fun
> myFun <- function(x) {
+   print(x)
+   get_timeline(x, n = 200)
+ }
> 
> ## user IDs are best stored as characters because scientific notation often
> ## results in rounding
> 
> ## for example, here are the IDs from your code with default(ish) options
> options(scipen = 3)
> (ids <- c(35515250, 7.151537e+17))
[1] 3.551525e+07 7.151537e+17
> 
> ## when I adjust the scipen option setting to correct this, it's clear that the
> ## 2nd ID is conveniently rounded off to zero...perhaps TOO conveniently
> options(scipen = 10)
> (ids <- c(35515250, 7.151537e+17))
[1]           35515250 715153700000000000
> 
> ## create a data frame of user IDs (with the scientific notation removed)
> followers <- tibble::data_frame(
+   user_id = as.character(ids)
+ )
> 
> ## map myfun to followers df
> followerTweets <- purrr::map_df(followers$user_id, myFun)
[1] "35515250"
[1] "715153700000000000"
Warning message:
Sorry, that page does not exist. 
> 
> ## view data
> followerTweets
# A tibble: 200 x 42
            status_id          created_at  user_id screen_name
                <chr>              <dttm>    <chr>       <chr>
 1 925327902140399616 2017-10-31 11:45:38 35515250   ekendriss
 2 925119300142338053 2017-10-30 21:56:43 35515250   ekendriss
 3 925108630709592064 2017-10-30 21:14:19 35515250   ekendriss
 4 925108277284884480 2017-10-30 21:12:55 35515250   ekendriss
 5 925099006140796929 2017-10-30 20:36:05 35515250   ekendriss
 6 925093482083078144 2017-10-30 20:14:08 35515250   ekendriss
 7 925021686507896832 2017-10-30 15:28:50 35515250   ekendriss
 8 925020352811622400 2017-10-30 15:23:32 35515250   ekendriss
 9 925014806561742848 2017-10-30 15:01:30 35515250   ekendriss
10 925011676839268352 2017-10-30 14:49:04 35515250   ekendriss
# ... with 190 more rows, and 38 more variables: text <chr>, source <chr>,
#   reply_to_status_id <chr>, reply_to_user_id <chr>,
#   reply_to_screen_name <chr>, is_quote <lgl>, is_retweet <lgl>,
#   favorite_count <int>, retweet_count <int>, hashtags <list>, symbols <list>,
#   urls_url <list>, urls_t.co <list>, urls_expanded_url <list>,
#   media_url <list>, media_t.co <list>, media_expanded_url <list>,
#   media_type <list>, ext_media_url <list>, ext_media_t.co <list>,
#   ext_media_expanded_url <list>, ext_media_type <lgl>,
#   mentions_user_id <list>, mentions_screen_name <list>, lang <chr>,
#   quoted_status_id <chr>, quoted_text <chr>, retweet_status_id <chr>,
#   retweet_text <chr>, place_url <chr>, place_name <chr>,
#   place_full_name <chr>, place_type <chr>, country <chr>, country_code <chr>,
#   geo_coords <list>, coords_coords <list>, bbox_coords <list>
> 

```

**Comment by pssguy** [comment]
@mkearney 
Thanks for tip re rds. I do use that with larger datasets but have tended to use write_csv otherwise - no particular reason

Anyways sorry to report that I am still getting this error appearing

```
myFun <- function(x) {
  print(x)
  get_timeline(x,n=200)
}

followerTweets <- map_df(followers$user_id,myFun)

...
[1] "352930089"
[1] "18406335"
Error in as.POSIXct.default(x, origin = "1970-01-01", tz = "UTC") : 
  do not know how to convert 'x' to class “POSIXct”

testFollower <- get_timeline("18406335",n=200, parse=TRUE) # df with 200 rows retuned
user <-lookup_users(18406335) # screen_name dogvile

```
So here we have a short user_id throwing an error during map_df.; no problem when it is entered individually ; and a screen_name which when viewed appears, to me, to have no odd characteristics in time-line. So no obvious line of enquiry

Is there a way I can use tryCatch in the myFun fuction so that if this error occurs it just ignores that user_id and tries the next one. I'm not sure how to do this

That would be a temporary hack - but sufficient for my purposes
TIA

**Comment by mkearney** [comment]
I'm not getting the same error

``` r
> myFun <- function(x) {
+   print(x)
+   get_timeline(x,n=200)
+ }
> followers <- data.frame(user_id = c("352930089", "18406335"), stringsAsFactors = FALSE)
> followerTweets <- purrr::map_df(followers$user_id,myFun)
[1] "352930089"
[1] "18406335"
> followerTweets
# A tibble: 399 x 42
            status_id          created_at   user_id screen_name
                <chr>              <dttm>     <chr>       <chr>
 1 925327581636939776 2017-10-31 11:44:21 352930089      g1ov35
 2 923821558141014016 2017-10-27 07:59:57 352930089      g1ov35
 3 923203552612438016 2017-10-25 15:04:13 352930089      g1ov35
 4 922956150143897600 2017-10-24 22:41:08 352930089      g1ov35
 5 922032001699287040 2017-10-22 09:28:54 352930089      g1ov35
 6 921386929286991872 2017-10-20 14:45:37 352930089      g1ov35
 7 919510565160136704 2017-10-15 10:29:37 352930089      g1ov35
 8 918496974466441217 2017-10-12 15:21:58 352930089      g1ov35
 9 918426470799888389 2017-10-12 10:41:48 352930089      g1ov35
10 916677282571448320 2017-10-07 14:51:09 352930089      g1ov35
# ... with 389 more rows, and 38 more variables: text <chr>, source <chr>,
#   reply_to_status_id <chr>, reply_to_user_id <chr>,
#   reply_to_screen_name <chr>, is_quote <lgl>, is_retweet <lgl>,
#   favorite_count <int>, retweet_count <int>, hashtags <list>, symbols <list>,
#   urls_url <list>, urls_t.co <list>, urls_expanded_url <list>,
#   media_url <list>, media_t.co <list>, media_expanded_url <list>,
#   media_type <list>, ext_media_url <list>, ext_media_t.co <list>,
#   ext_media_expanded_url <list>, ext_media_type <lgl>,
#   mentions_user_id <list>, mentions_screen_name <list>, lang <chr>,
#   quoted_status_id <chr>, quoted_text <chr>, retweet_status_id <chr>,
#   retweet_text <chr>, place_url <chr>, place_name <chr>,
#   place_full_name <chr>, place_type <chr>, country <chr>, country_code <chr>,
#   geo_coords <list>, coords_coords <list>, bbox_coords <list>

```

As for the `tryCatch`...

``` r
myFun <- function(x) {
  print(x)
  tryCatch(get_timeline(x,n=200), error = function(e) return(NULL))
}
```
