### ISSUE TITLE
Question about retryonratelimit parameter

### ISSUE THREAD

**Issue by methodds** [mkearney/rtweet#125]
Hi, 

first of all many thanks for creating `rtweet`, which is sooo useful for twitter research. I'm currently trying to use `search_tweets` for retrieving tweets related to a currently trending hashtag, `#metoo`:

```
metoo <- search_tweets("#metoo", n = 500000, token = twitter_token,
                       retryonratelimit = TRUE)

Searching for tweets...
Finished collecting tweets!
retry on rate limit...
waiting about 10 minutes...
Searching for tweets...
Warning message:
rate limit exceeded. 
```
Although setting `retryonratelimit` to `TRUE`, the function stops and I have an object with 17.500 (first attempt) / 18.000 tweets (second attempt) in my environment. So how exactly does the parameter work? I thought that its usage would avoid hitting rate limits and therefore not stop the process?

**Comment by mkearney** [comment]
This is behaving well now. So I'd recommend installing the most recent Github version and giving it another try. You may still on rare occasion reach rate limit capacity, but that should only be due to requests made from a concurrent session.
