### ISSUE TITLE
get_friends gives no results

### ISSUE THREAD

**Issue by github-jk** [mkearney/rtweet#126]
Pretty much what the title says. I tried it with several thousand Twitter IDs as well as with the basic example get_friends(user = "epa"). The result was always the same: I get 0 friends instead of the real amount of friends. get_followers, however, works just fine. Anyone else having this issue as well or has an idea on how to resolve that?

**Comment by mkearney** [comment]
This is likely due to a rate limit issue. Users only get 15 `get_friends` requests every 15 minutes. Any request made after the rate limit is exceeded would then likely return a data frame without rows. I'll try to modify the code so it spits out a warning.

I may still be wrong. If you think so, can you provide me with code that replicates the wrong output?

Thanks!

**Comment by github-jk** [comment]
Hi, thanks for getting back to me!
I don't think it's a rate limit as I'm not even able to get the friends for one Twitter user. I.e. I tried to example of the EPA which yielded no result. Same thin happened when I tried it with a different id/screen name. Sounds like it's an issue on my end?

**Comment by mkearney** [comment]
Can you try to install the latest version and see if that works?

``` r
devtools::install_github("kearney/rtweet")

library(rtweet)

get_friends("epa")
```

If you get an error, copy and paste the output from this line of code in a post here and I'll see what's going on.

``` r
get_friends("epa", parse = FALSE)
```

It probably won't come to that. I'm betting that updating to the newest version will fix your issue.

**Comment by github-jk** [comment]
Hi,

so I'm getting this output. Still doesn't work for me (re-checked Twitter environment and I was able to get 75,000 followers for EPA, so this seems to work)

> get_friends("epa", parse = FALSE)
Response [https://api.twitter.com/1.1/friends/ids.json?screen_name=epa&count=5000&cursor=-1&stringify=TRUE]
  Date: 2017-11-02 19:35
  Status: 400
  Content-Type: application/json; charset=utf-8
  Size: 62 B

**Comment by mkearney** [comment]
@github-jk 

You're still using an old version of `rtweet`. A few weeks ago I [fixed a bug related to the `stringify` parameter](https://github.com/mkearney/rtweet/blob/master/R/friends.R#L190). The URL in your request was made by an old version of rtweet.

**Comment by github-jk** [comment]
Sorry and thanks for the heads up! I thought I had installed it but it threw me an error! It works with the new version! Thanks so much!

**Comment by mkearney** [comment]
```
Edit: Also only works somehow for me with the added "token = twitter_token"
```

Can you elaborate? It only works if you specify a token? Are other functions working when you don't specify a token?
