### ISSUE TITLE
"filter" parameter in ts_plot

### ISSUE THREAD

**Issue by etancoigne** [mkearney/rtweet#128]
Hi,
I am updating a script that uses rtweet, for an undergrad lesson. I used to use ts_plot with the "filter" parameter, such as 

`ts_plot(a_timeline, filter = "a_word", by = "months")`

but it does not seem to work anymore: 

`Erreur : Unknown parameters: filter`

I searched in the documentation but could not see anything related to this. Is there another function that replaces it?

Thanks.

**Comment by mkearney** [comment]
The filter feature is now deprecated. It was originally offered as a quick and easy convenience, but I decided users would ultimately be better off if they wrote specific code to create grouping variables.

``` r
## download most recent github version of rtweet
devtools::install_github("mkearney/rtweet")

## create logical variable using regexp matching via grepl() fun.
a_timeline$variable <- grepl("a_word", a_timeline$text, ignore.case = TRUE)
```

Here's some code I wrote today to create a variable with multiple categories and then plotted the time series for each group.

``` r
## stream tweets
rt <- stream_tweets(
  "manafort,papadopoulos,gates,mueller,trump,clinton",
  timeout = 60L * 5L
)

## user defined function to create grouping var with multiple levels
mkp <- function(m, x) {
  kp <- grepl(m, x$text, ignore.case = TRUE)
  usr <- users_data(x)
  usr <- usr[usr$user_id %in% x$user_id[kp], ]
  x <- x[kp, ]
  x$regmatch <- m
  attr(x, "users") <- usr
  x
}

## apply grouping fun to data rt
rtm <- lapply(
  c("mueller", "gates", "papadopoulos", "manafort", "trump", "clinton"),
  mkp, rt
)

## handy new rtweet function for binding a list of tweets/users data
rtm <- do_call_rbind(rtm)

## 
rtm %>%
  dplyr::group_by(regmatch) %>%
  ts_plot("15 secs", trim = 1L) +
  theme_mwk() + ggplot2::labs(x= NULL, y= NULL) +
  ggplot2::ggsave("~/Desktop/groupgitexample.png")
```

![groupgitexample](https://user-images.githubusercontent.com/13401460/32202449-d3204228-bdaa-11e7-8f8a-277de5eabe67.png)

**Comment by use-r-carlvogt** [comment]
Thanks for your reply. I liked this parameter for educational reasons, but indeed, a single line may replace it. Thanks for the code you offered above. 
All the best

**Comment by etancoigne** [comment]
Thanks for your reply. I liked this parameter for educational reasons, but indeed, a single line may replace it. Thanks for the code you offered above.
All the best
