### ISSUE TITLE
search_tweets only return a max of 18000 tweets when using parse = F

### ISSUE THREAD

**Issue by LeszekDiez** [mkearney/rtweet#130]
When using the parameter of parse = F in search_tweets, the max number of large matrix elements to return are 180 (18,000 tweets) even though I'm using the **n** parameter greater then 18000. 

I'm also setting the parameter retryonratelimit = TRUE.

Example: 
tw <- search_tweets(keyword, n = 30000, tweet_mode='extended', parse = F, token=twitter_token, retryonratelimit = TRUE)

**Comment by mkearney** [comment]
This should be fixed now! But let me know if you have any more issues!
