### ISSUE TITLE
search_tweets return list

### ISSUE THREAD

**Issue by JohnCoene** [mkearney/rtweet#132]
It returns a list for some reason

```R
df <- search_tweets("gendergap17", type = "recent", n = 100)
```

In some cases `do.call(rbind, df)` works but in others columns are unequal:

```R
purrr::map_dbl(df, length)
```

**Comment by mkearney** [comment]
This has been fixed. Install the most recent version from Github and you should get a tbl data frame.

## install devtools package if it's not already
if (!"devtools" %in% installed.packages()) {
  install.packages("devtools")
}

## install dev version of rtweet from github
devtools::install_github("mkearney/rtweet")
