### ISSUE TITLE
Error upon first authentication of twitter app

### ISSUE THREAD

**Issue by oli666** [mkearney/rtweet#134]
Following the set up procedure for the setup token, the following error messages comes up:

Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error: are_named(dots) is not TRUE

**Comment by mkearney** [comment]
Thanks, @oli666. You've caught a [small but critical typo](commit/dc36ec9cf73e85658c9c9277a4b8d582e88054bd) related to the authorization methods. Your error message made this easy to find/fix, so thank you for including that! It's now fixed. Let me know if you have any more issues!

**Comment by oli666** [comment]
Thanks. The installation now works fine. However, running your test query (rt <- search_tweets( "#rstats", n = 5000, include_rts = FALSE) results in: 

_Error in if (date) { : argument is not interpretable as logical_

**Comment by mkearney** [comment]
@oli666 Good catch again! It should now be fixed. And it's running fine for me, but let me know! I am a little behind on unit testing :).

**Comment by oli666** [comment]
No worries. I DO love your library; so much more elegant compared to what I have worked before. Your fix did do the job, all good now! Thanks for the quick turn around.
