### ISSUE TITLE
No authorization / No Data

### ISSUE THREAD

**Issue by renegro90** [mkearney/rtweet#135]
Hey there 
Since the new Update I'm having serious problems using the rtweet package.

First:
When I follow the instructions for the new authorization method, everything works fine for the moment. But after I installed the package and run one of the API request functions (e.g. get_followers, get_timeline) there's neither a browser window to log into my Twitter Account nor anything to authorize the rtweet application.

Second (maybe it's connected with the missing authorization?!):
By running the "get_timeline" argument, I constantly receive the following Error: "Error in if (date) { : argument is not interpretable as logical".

Is there any solution for my problems?

Thanks in advance :)

**Comment by mkearney** [comment]
I made a small but critical typo related to the authorization methods. It's now fixed. Please let me know if you still have any issues!

**Comment by mkearney** [comment]
@renegro90 Good catch again :). That issue should now be fixed as well!
