### ISSUE TITLE
Inaccuracy of User IDs with get_followers()

### ISSUE THREAD

**Issue by alhosu** [mkearney/rtweet#137]
Hi,

I am having some issues obtaining the followers IDs using get_followers(). The problem is mostly with those IDs with 18 characters (I think those are for newer users). See for example:

`followersids <- get_followers("alhosu")`

The first 6 IDs I get are:

926268612230381568
123082538
297795810
907302769773694976
906323537719427072
900199777928978432

However, when I use `lookup_users` for each of these user IDs, I cannot find 3 of these 6 codes:

926268612230381568
906323537719427072
900199777928978432

I know the screen name of these 3 followers by simply looking my Twitter account on a browser. When I look these users by screen name I get the correct code which are:

926268612230381569 - AndreaForeroCa3
906323537719427078 - GermnJimnez9
900199777928978436 - AHV71529917

You can see that the codes returned by `get_followers` and the codes obtained from `lookup_users` are very similar, they only differ in the last digit. I think the problem is with the Twitter API GET followers/ids which for some reason is returning inaccurate codes, and this problem only happens with ID codes with 18 characters. I had this problem with many other accounts.

Anyone had this problem before?

Thank you!

**Comment by mkearney** [comment]
@alhosu I was under the impression this behavior was fixed with a [somewhat recent update](https://github.com/mkearney/rtweet/commit/38a101fae5837a79e710b1c357f1d073f39916a4). What version of rtweet are you using?

``` r
packageVersion("rtweet")
```

**Comment by alhosu** [comment]
Thanks! For some reason when I installed from CRAN, it installs the version 4.0, but I got version 6.0 and it is working great.

Thanks a lot!
