### ISSUE TITLE
Error in readRDS(pat) : error reading from connection

### ISSUE THREAD

**Issue by adriannebradford** [mkearney/rtweet#139]
I'm getting this error using the newest version of rtweet.  The current documentation indicates I should get a pop-up to authenticate/login to twitter.  I do not get this.  

I also tried to create the token, for which i got this error:
``Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission, : Unauthorized (HTTP 401).``

**Comment by mkearney** [comment]
@adriannebradford Does the full error message include the "Error in readRDS..." from the issue title?

**Comment by mkearney** [comment]
Do you have anything already set as the `TWITTER_PAT` environment variable?

``` r
Sys.getenv("TWITTER_PAT")
```

**Comment by adriannebradford** [comment]
Sorry!  The error I get when trying it expecting the popup was the issue title.  The second error was what I got when I explicitly tried to set the token.

I got "" for the sys.getenv("TWITTER_PAT").

**Comment by mkearney** [comment]
You might try a fresh R session. Make sure there isn't an `.httr-oauth` file in the current working directory. I'm about to board a plane, so I won't have a chance to troubleshoot again until later tonight :/.

**Comment by adriannebradford** [comment]
I appreciate your help whenever you have time.  

I've cleared session, new session, deleted workspace, created a new working directory with nothing in it, reinstalled R and RStudio...

Here's the traceback if that helps:
`10. readRDS(pat)
9. (function (pat, env = globalenv()) { if (identical(pat, ".httr-oauth")) { readRDS(pat) ...
8. mapply(FUN = f, ..., SIMPLIFY = FALSE)
7. Map("load_tokens_", pat = pat, MoreArgs = list(env = env))
6. load_tokens(twitter_pat())
5. get_tokens()
4. check_token(token, "search/tweets")
3. search_tweets_(q = "#rstats", n = 18000, type = "recent", include_rts = FALSE, geocode = NULL, max_id = NULL, parse = TRUE, token = NULL, retryonratelimit = FALSE, verbose = TRUE)
2. do.call("search_tweets_", args)
1. search_tweets("#rstats", n = 18000, include_rts = FALSE)
`

**Comment by mkearney** [comment]
It looks like an .httr-oauth file is causing this. Can you run this in the working directory and try again?

``` r
unlink(“.httr-oauth”)
```

**Comment by adriannebradford** [comment]
That didn't work either.  But, I did get it to work on another computer.  So I'm all good.  Not sure what I did to flummox this up.
