### ISSUE TITLE
get_friends() error

### ISSUE THREAD

**Issue by moman822** [mkearney/rtweet#14]
Getting the following error when using `get_friends()`, but only some of the time. It will work for a few calls then won't.
```

> get_friends("potus")
Error in names(x) <- "ids" : 
  'names' attribute [1] must be the same length as the vector [0]
```

**Comment by mkearney** [comment]
That should mean it's being fed a NULL or value with a length of zero (empty character or numeric). Can you identify which IDs are producing errors?

**Comment by moman822** [comment]
It will work fine for a few runs, and then won't work with the same IDs just moments later, like in the next call (both character and numeric). It consistently does not work when I try and use it in conjunction with `lapply` like so:

`lapply(users, get_friends)`

when `users` is a *longer* character vector of `user_id`s obtained from `search_tweets()`. That is, it worked on a character vector of only 2 user IDs but not on 50.

**Comment by mkearney** [comment]
The rate limit for get_friends is 15 requests per 15 minutes. It sounds like you may be running up against that. I started to build the infrastructure for a 'wait.on.reset' argument, so I'll get around to finishing that.

**Comment by moman822** [comment]
Ah ok that is probably it. Maybe throw that into the documentation for the function when you get a chance. Thanks again, the package is very good.
