### ISSUE TITLE
Bulk follow

### ISSUE THREAD

**Issue by meneos** [mkearney/rtweet#140]
I created a function that uses rtweet to do bulk follow and unfollow. This is the repository:

https://github.com/meneos/twitter_bulk_follow

I'm not sure you are interested in this functionality because rtweet seems to be adressed to research, but just so you know.

**Comment by mkearney** [comment]
I'm somewhat open to this sort of thing–I've [dabbled](https://github.com/mkearney/trickrtweet) a bit myself–but I'd like to be careful about following Twitter's [Terms of Service](https://twitter.com/en/tos), and I'm not yet familiar enough with their posting rules to hardwire in any bulk posting behavior. 

With that said, I like that you've included a 20-second delay between follows. I believe Twitter limits the number of new follows a day to 1,000 (or, at least, to 1,000 POST follow/REST API requests), so it's probably not a bad idea to include a max number of users as well (else you'll be forced to reset your user token).

You've also got an interesting approach to writing the code. I think you'll find there may be more efficient ways to write a similar script (I'd recommend checking out [Hadley Wickham's Advanced R](http://adv-r.had.co.nz) if you haven't already done so), but–in my experience anyway–you've exhibited a degree of creativity that makes me interested to see what you'll come up with moving forward! I'll close this issue for now, but please don't be discouraged from future contributions!

**Comment by meneos** [comment]
Yes, probably this script crosses the edge of Twitter's Terms of Service. About the way of writing the script, well, yes, I'm actually a noob in R so I'm sure there's more efficient ways to code this.

Thanks anyway. Nice package by the way.

**Comment by mkearney** [comment]
@meneos You're not a n00b if you're writing our own functions and using Github!
