### ISSUE TITLE
Variable names change during parsing

### ISSUE THREAD

**Issue by simonsays1980** [mkearney/rtweet#143]
I have been using rtweet in a Shiny App for a while. Now, after the latest update, I get a couple of warnings and errors when using my code. I investigated the errors a little further and it seems that rtweet changes variable names during parsing: 

```
#use your own token here
tweets.not.parsed <- search_tweets( 'tidyverse', n = 10, token = token, lang = "en", include_rts = TRUE, parse = FALSE )
# the variable name "in_reply_to_screen_name exists"
names( tweets.not.parsed[[1]]$statuses )
```
```
# now parse the results
tweets.parsed <- search_tweets( 'tidyverse', n = 10, token = token, lang = "en", include_rts = TRUE, parse = TRUE )
# the variable name "in_reply_to_screen_name" is now named "reply_to_screen_name"
names( tweets.parsed )
```
 

My application uses the original names and therefore it crashes when it calls the variable 'in_reply_to_screen_name'. This must have been come with the latest changes.

**Comment by mkearney** [comment]
Yes. There were a few name changes that were requested by users. That name change, however, was totally my bad. I mistakenly thought I had dropped the `in_` prior publishing the first version of rtweet. Sorry about that! Future versions will only alter variable names in response to problematic changes in Twitter's API. Even then, I'll do what I can to limit it.
