### ISSUE TITLE
stream_tweets appending parameter is not working

### ISSUE THREAD

**Issue by seuriously** [mkearney/rtweet#144]
Hii,
On rtweet package document there is a parameter append on function stream_tweets().
However, upon changing append value to TRUE I did not get my file appended thus deleting my already exist file. 

stream = stream_tweets(q = "telkomsel", timeout = Inf, parse = F, token = twitter_token, 
                       file_name = "D:\\stream2.json", append=TRUE)

thanks

**Comment by seuriously** [comment]
@mkearney Thanks for the confirmation.
I tried stream_tweets2() but it save nothing while creating 2 files (0 kb size).
```
stream_tweets2(q = "telkomsel OR tsel OR @Telkomsel", timeout = Inf, parse = F, 
              token = twitter_token)
```
Did I use the function wrong?

**Comment by mkearney** [comment]
@seuriously ahh, you did almost everything right, but the syntax for the stream is a little different than the search. Instead of the ` OR `, you should use `,` in the stream syntax (that's a feature inherited from Twitter's APIs).

``` r
stream_tweets2(q = "telkomsel,tsel,@Telkomsel", timeout = 30, parse = F, 
               token = twitter_token)
```
