### ISSUE TITLE
Historical PowerTrack Data integration

### ISSUE THREAD

**Issue by swood-ecology** [mkearney/rtweet#145]
Hi,

Is there any functionality in rtweet that would allow for making data from the Historical PowerTrack API useable with rtweet's analytic functions?

Thanks,
Steve

**Comment by mkearney** [comment]
@swood-ecology rtweet wouldn't be any help as a direct interface with Historical PowerTrack. There API seems manageable, though, so it probably wouldn't be too hard for someone to write a package for it. I'd consider doing it myself if I was working with the data.

Once you download the data, though, my bet is that you can still leverage rtweet functions. If it's a json file, for example:

``` r
rt <- parse_stream("path/to/twitter-data.json")
```

That of course assumes the structure of the json file is similar to their public API. Based on this documentation, it sounds like there's a chance, but it's not certain. For instance, the [Activity Streams format](http://support.gnip.com/sources/twitter/data_format.html) definitely wouldn't work.


> Data for completed Historical PowerTrack jobs is delivered via an array of flat, gzip compressed JSON files. Each file represents a 10 minute segment of the overall time period requested for the job.

> Tweets delivered through Historical PowerTrack can be provided in either Gnip’s Activity Streams format, or in Twitter’s native format. For details on the Activity Streams format for Twitter, see our documentation here. For documentation on Twitter’s native data format, see their documentation here.

I'm going to close this for now as I don't–at the current moment–consider it within the scope of the rtweet package. With that said, I'd probably welcome contributions that integrated the APIs!
