### ISSUE TITLE
Unable to install dev version of rtweet from github

### ISSUE THREAD

**Issue by Keveene** [mkearney/rtweet#146]
It fails trying to install rtweet from github. I tried it on RStudio (R version 3.4.2) and Microsoft R Open (3.4.0)

`devtools::install_github("mkearney/rtweet")`
_Downloading GitHub repo mkearney/rtweet@master
from URL https://api.github.com/repos/mkearney/rtweet/zipball/master_
`Installation failed: transfer closed with 291711 bytes remaining to read`

Version from CRAN installs without any problems. Kindly fix.

**Comment by mkearney** [comment]
Sorry about that, @Keveene. This should have been fixed a while back, but please let me know if you run into any more issues.
