### ISSUE TITLE
Error in readRDS(pat) : error reading from connection

### ISSUE THREAD

**Issue by valentinap** [mkearney/rtweet#15]
I'm testing the rtweet package, but I'm encountering this issue:

Error in readRDS(pat) : error reading from connection

when I try to start a data extraction. If I well understand, for the connection is still required to use the setup_twitter_oauth() fonction from twitteR package? 

Thanks a lot

**Comment by mkearney** [comment]
There are three ways to setup authorization to interact with Twitter's API through rtweet:

1. Save token(s) and setup an environment variable (recommended method). 
- Ideally, you'd setup an environment variable that contains a path to your saved token(s). I made a [tokens vignette that describes how to do that](https://github.com/mkearney/rtweet/blob/master/vignettes/tokens.Rmd), so I'd encourage you to follow that method.

2. Create token(s) object and use token argument.
- Another method is to create a token and then specify it as the "token" function in each call. An example of this can be found on the [README](https://github.com/mkearney/rtweet/blob/master/README.md) file.

3. Use token(s) originally created for the twitteR.
- For ease of transition, I added some checks to see if an .httr-oauth file was already generated, following the instructions provided by the twitteR package. Depending on system cache options, this can [create a problem](https://github.com/mkearney/rtweet/issues/9). Fortunately, until I fix this (which I hope to do relatively soon), the other two methods should still work.

If you've done any/all of that and you're still getting that error, can you share your code so I can get a better idea of what might be going wrong?

**Comment by valentinap** [comment]
Sorry to reply so in late. I'm following your vignette but when I put my data to create a twitter token I get the following error:

Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission,  : 
  Unauthorized (HTTP 401).


This is the code:

twitter_tokens <- c(
        create_token(app = "my_app",
                     consumer_key = "xxxxxxxxxxxxxxx",
                     consumer_secret = "XXXXXXXXXXXXXXXXXXXXXXXXXX"), 
        create_token(app = "my_app",
                     consumer_key = "xxxxxxxxxxxxxxx",
                     consumer_secret = "XXXXXXXXXXXXXXXXXXXXXXXXXX"))


Thanks in advance for your help

**Comment by mkearney** [comment]
You'll have to make sure to replace the xxxxx with the appropriate keys. If you only made one app, then you'd want to change the code to only includ one create_token. I can give a fuller answer a little later, but you can also try the Github version, which now has a couple of tokens built in!

**Comment by mkearney** [comment]
@valentinap This same problem error comes up if you leave an extra space when copy/pasting the keys or if you forget to enter the callback URL. I'm guessing the latter is more likely. To fix it, go to https://apps.twitter.com, click on your app, and then select "settings." For "callback url" enter the following

```
http://127.0.0.1:1410
```

**Comment by valentinap** [comment]
Thanks a lot! Now seems working fine!

**Comment by mosrihari** [comment]
I gave the callback URL as above and also tried to search the tweet. But I am getting the same error
> library(rtweet)
> library(twitteR)

Attaching package: ‘twitteR’

The following object is masked from ‘package:rtweet’:

    lookup_statuses

> library(ROAuth)
> setup_twitter_oauth("consumer key",
+ "consumer secret",
+ "access token",,
+ "access secret")
[1] "Using direct authentication"
> trump=search_tweets("DonaldTrump",n=10)
Error in readRDS(pat) : error reading from connection

**Comment by mkearney** [comment]
@mosrihari this is because R is reading the wrong token. for reference: https://github.com/mkearney/rtweet/issues/141

**Comment by mosrihari** [comment]
Hi mkearney, Even then I am not able to connect to twitter. With reference to #141 , I removed my httr.oauth in my current directory and tried the same. Please note that my current working directory doesnt have .httr.oauth
Please advice on the below code
> library(rtweet)
Warning message:
package ‘rtweet’ was built under R version 3.4.3 
> appname <- "Srihari_NTU"
> key <- "consumer key"
> secret <- "consumer secret"
> twitter_token <- create_token(
+   app = appname,
+   consumer_key = key,
+   consumer_secret = secret)
Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission,  : 
  Unauthorized (HTTP 401).
> rstats_tweets <- search_tweets(q = "#rstats",
+                                n = 500)
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Error in shell.exec(url) : 
  file association for 'https://api.twitter.com/oauth/authenticate?oauth_token=zLGxnQAAAAAAxSTkAAABYXOT5qM&permission=read' not available or invalid

**Comment by mkearney** [comment]
Perhaps @mosrihari it's the callback URL that needs to be corrected. Go to https://apps.twitter.com, select your app, and set callback URL to `http://127.0.0.1:1410`

**Comment by mosrihari** [comment]
Sorry to bother you again. I had my callback URL as the one you specified before. But even then it is not working . httroauth is not my current working directory. Could you please advice me how to proceed ? The main purpose I wanted to use rtweets is I can use extended keyword which can take more characters. This is actually failing for me

**Comment by trenkert** [comment]
@mkearney I have the same problem as @mosrihari . My callback URL is correct, I had deleted the .httr-oauth file. I still get

```
Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission,  : 
  Unauthorized (HTTP 401).
```

**Comment by 97joseph** [comment]
I have also tried changing the callback Url to http://127.0.0.1:1410 ,but with zero luck..i am still getting the same error
