### ISSUE TITLE
stream_tweets not returning the full text, even when made sure they are non-RT/quotes

### ISSUE THREAD

**Issue by pakoputki** [mkearney/rtweet#166]
Having a lot of fun with rtweet, thank you for the great package! However I'm facing some major trouble with getting the full tweet text using the stream_tweets.

I collected 1347 tweets in Finnish language. Checking the "text" column shows that I'm missing part of the text when comparing the view to that in the browser. As suggested in issue 142 ( https://github.com/mkearney/rtweet/issues/142 ) I further analyzed whether I'm experiencing an issue.

```
>sum(grepl("...\\s{0,}$", rtweettest$text))
[1] 1347
> sum(grepl("...\\s{0,}$",rtweettest$text)& !rtweettest$is_quote & !rtweettest$is_retweet)
[1] 587
```
The number of truncated non-RT/quote tweets appears very high (n=587), compared to the numbers seen in issue 142. Also, checking some of the tweets in browser clearly show that for some reason they are truncated in the data. I wondered if it would have something to do with the language and tested a random sample:

```
>randomsampletest <- stream_tweets("",timeout = 30)
Streaming tweets for 30 seconds...
Downloading: 1.6 MB       
Finished streaming tweets!
opening file input connection.
 Imported 1026 records. Simplifying...
closing file input connection.
> sum(grepl("...\\s{0,}$",randomsampletest$text))
[1] 1025
> sum(grepl("...\\s{0,}$",randomsampletest$text) & !randomsampletest$is_quote & !randomsampletest$is_retweet)
[1] 456
```
Again, the number of truncated tweets is high. I'm wondering am I doing something wrong...?

**Comment by mkearney** [comment]
@pakoputki I think you've been tricked by the awfulness of regular expressions!

So, first, when you enter "...\\s{0,}$" as a pattern, the dots are not acting like simple dots, e.g.,

``` r
> grepl("...\\s{0,}$", c("...", "..", "hey."))
[1]  TRUE FALSE  TRUE
```

You can escape the dots, but then it'll only pick up people who ended the tweet with "..." themselves.

``` r
> sum(grepl("\\.\\.\\.\\s{0,}$",randomsampletest$text) & !randomsampletest$is_quote & !randomsampletest$is_retweet)
[1] 1
```

What you really want is to search for the ellipses symbol (Twitter is UTF-8 encoded and it chose these annoying little things as a truncation marker):

``` r
> randomsampletest$text[grepl("…$",randomsampletest$text) & !randomsampletest$is_quote & !randomsampletest$is_retweet]
character(0)
```

As you can see, once you've adjusted the pattern to use `…` instead of `...`, it's actually not truncating anything that's not a retweet or a quote!

**Comment by thomas-keller** [comment]
Hi @mkearney, @pakoputki, 

I was looking into this issue myself recently. I'm not sure about your examples, but right now tweets (not RTs, those correctly use the full_text field) don't grab the full_text field when they are shortened.

An example tweet text:

gah$text
[1] "@TheJordanRachel @realDonaldTrump Gunning for a spot as a Fox News Clone or a job in the Oval Office? That’s awesom… https://t.co/YW5tFbn2EJ"

b$full_text[3]
"@TheJordanRachel @realDonaldTrump Gunning for a spot as a Fox News Clone or a job in the Oval Office? That’s awesome! https://t.co/9GVcfGF6CM"

The first text field comes from a parsed rtweet stream, the second from the raw jsonlite list structure df$extended_tweet$full_text

I need this for my own research, so I can probably submit a patch in the within the next day or so.

**Comment by thomas-keller** [comment]
if you add this one liner to the beginning of tweets_to_tbl, it should fix it. I'll submit a pull in a minute.

dat$text <- ifelse(dat$truncated, dat$extended_tweet$full_text, dat$text)

**Comment by pakoputki** [comment]
Hi @thomas-keller ,

Yeah, I witnessed the same behaviour as you! First I thought that I had messed up with regular expressions as suggested but I later double-checked the data and it infact was truncated... Very glad that you have come up with a solution, thanks!
