### ISSUE TITLE
Is creating own Twitter app really neccessary?

### ISSUE THREAD

**Issue by yutannihilation** [mkearney/rtweet#167]
I saw this conversation on Twitter months ago: https://twitter.com/hadleywickham/status/927918886707761153

Are there any progress or further discussions on this topic?

**Comment by mkearney** [comment]
Yep. It's been integrated in the current version posted to CRAN. Users can now install package, use function, and click a button to authorize [on behalf of their Twitter account]!

**Comment by mkearney** [comment]
Thank you @yutannihilation! And just so you know, if you ever wanted to make a contribution, it'd be very welcome 😉!

**Comment by yutannihilation** [comment]
Thanks, I'll start to contribute by blogging about this, as many of my friends doesn't seem to know this nice news :)
