### ISSUE TITLE
Error in search_tweets - can only search less than 100 tweets

### ISSUE THREAD

**Issue by DrMattG** [mkearney/rtweet#169]
I'm really enjoying playing with rtweet - great package. I have a strange error which I can not replicate on my home computer (i.e. at home I can search 18000 tweets without issue). When at work I can only search less than 100 tweets (see below). I suspect the solution would be to delete the package from my work computer and re-load it. I was just wandering if you had seen this issue before. I've probably done something stupid, I just cant work it out! 
> rt <- search_tweets("#Rstats", n =99, include_rts = FALSE, token=twitter_token)
Searching for tweets...
Finished collecting tweets!
> rt <- search_tweets("#Rstats", n =100, include_rts = FALSE, token=twitter_token)
Searching for tweets...
Error in namespaceExport(ns, exports) : 
  undefined exports: :.default, :.integer64, is.double.default, is.double.integer64, match.default, %in%.default, rank.default, order.default, binattr, plusclass, minusclass, integer64, identical.integer64, is.integer64, as.integer64, as.integer64.integer64, as.integer64.NULL, as.integer64.character, as.integer64.double, as.integer64.integer, as.integer64.logical, as.integer64.factor, NA_integer64_, as.character.integer64, as.double.integer64, as.integer.integer64, as.logical.integer64, as.bitstring, as.bitstring.integer64, length<-.integer64, [.integer64, [[.integer64, [[<-.integer64, [<-.integer64, str.integer64, print.integer64, format.integer64, is.vector.integer64, is.na.integer64, is.nan.integer64, is.finite.integer64, is.infinite.integer64, all.integer64, any.integer64, !.integer64, &.integer64, |.integer64, xor.integer64, !=.integer64, ==.integer64, <.integer64, <=.integer64, >.integer64, >=.integer64, +.integer64, -.integer64, *.integer64, ^.integer64, /.integer64, %/%
In addition: Warning message:
S3 methods ‘:.default’, ‘:.integer64’, ‘is.double.default’, ‘is.double.integer64’, ‘match.default’, ‘%in%.default’, ‘rank.default’, ‘order.default’, ‘identical.integer64’, ‘is.integer64’, ‘as.integer64’, ‘as.integer64.integer64’, ‘as.integer64.NULL’, ‘as.integer64.character’, ‘as.integer64.double’, ‘as.integer64.integer’, ‘as.integer64.logical’, ‘as.integer64.factor’, ‘as.character.integer64’, ‘as.double.integer64’, ‘as.integer.integer64’, ‘as.logical.integer64’, ‘as.bitstring’, ‘as.bitstring.integer64’, ‘length<-.integer64’, ‘[.integer64’, ‘[[.integer64’, ‘[[<-.integer64’, ‘[<-.integer64’, ‘str.integer64’, ‘print.integer64’, ‘format.integer64’, ‘is.vector.integer64’, ‘is.na.integer64’, ‘is.nan.integer64’, ‘is.finite.integer64’, ‘is.infinite.integer64’, ‘all.integer64’, ‘any.integer64’, ‘!.integer64’, ‘&.integer64’, ‘|.integer64’, ‘xor.integer64’, ‘!=.integer64’, ‘==.integer64’, ‘<.integer64’, ‘<=.integer64’, ‘>.integer64’, ‘>=.integer64’, ‘+.integer64’, ‘-.integer64’, ‘*.integer64’, ‘... <truncated>

**Comment by mkearney** [comment]
This is an known issue with an older version of rtweet (not *that* old but old enough that I'm not eager to search for the exact commit that fixed it), so you're correct that installing the most recent version would correct this issue! 

And it was nothing of your doing! Twitter just has varying string sizes for IDs, and some of them are so long that trying to handle them in a way that allows R to recognize one value as being bigger or smaller than the other value is difficult (and a version of rtweet that tried to convert them into a special integer class, didn't work out lol).
