### ISSUE TITLE
Error in from_js(r) : could not find function "http_type"

### ISSUE THREAD

**Issue by JacobCoblentz** [mkearney/rtweet#17]
What's this? Never seen this before- am I doing something wrong, or does it have to do with my version of R?

**Comment by mkearney** [comment]
Yeah, that either means you need to update the `httr` package or a newer version of R. I'm not sure why I've kept that function around, really. So this is a good reminder to write my own function to replace it.

**Comment by mkearney** [comment]
this dependency has now been replaced with an internal rtweet function. let me know if you have any more issues!
