### ISSUE TITLE
Typo in stopwordslangs description

### ISSUE THREAD

**Issue by tyluRp** [mkearney/rtweet#172]
`?rtweet::stopwordslangs`

> This data comes **form** a group of Twitter searches conducted at several times during the calendar year of 2017. The data are commonly observed words associated with 10 different languages, including `c("ar", "en", "es", "fr", "in", "ja", "pt", "ru", "tr", "und")`. Variables include "`word`" (potential stop words), "`lang`" (two or three word code), and "`p`" (probability value associated with frequency position along a normal distribution with higher values meaning the word occurs more frequently and lower values meaning the words occur less frequently).

form should be replaced with from.

**Comment by mkearney** [comment]
Thanks for this, @tyluRp! If you're looking for an excuse to make your first pull request, I'll accept it! Otherwise I'm happy to fix it...I just know I would have appreciated someone telling me to make a pull request not long ago (learning git[hub] is tough).

**Comment by tyluRp** [comment]
Awesome, I'd love to help contribute. I just gave it a shot. Hope I did it right!

**Comment by mkearney** [comment]
Merged! Great work!
