### ISSUE TITLE
popular tweet limit for search_tweets

### ISSUE THREAD

**Issue by steveSpotted** [mkearney/rtweet#174]
Hi @mkearney,

I've looked around everywhere and haven't found any solution nor documentation for adjusting the limit for returned tweets when result_type = 'popular' (defaulting to 15 regardless of n). Maybe there is something I'm missing that you've come across? And if so, is it possible to include as a function parameter?
Much appreciated, and thanks for your work with rtweet!

Steve

**Comment by mkearney** [comment]
@steveSpotted: it's my understanding that Twitter's "popular" `result_type` only returns a handful (I suppose 15 sounds about right) of the most popular tweet (using whatever their algorithm is). This [appears to be confirmed by a similar behavior in Tweepy](https://github.com/tweepy/tweepy/issues/560). My advice is to use `result_type = "popular"` to return a lot of tweets, and then arrange by `favorites_count` or `retweet_count`.

**Comment by steveSpotted** [comment]
Gotcha.

Thanks for the quick response!
