### ISSUE TITLE
oauth error on initial use

### ISSUE THREAD

**Issue by jnolis** [mkearney/rtweet#180]
I am trying the rtweet package for the first time using R 3.4.3. After installation, I get the following error:

```r
> library(rtweet)
> get_timeline("johnlegere")
Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission,  : 
  Unauthorized (HTTP 401).
```

There is no pop-up to authenticate or anything. Further, if I try using my own credentials from a custom app, I still get this same error:

```
> twitter_token <- create_token(app=[hidden], [hidden], [hidden])
Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission,  : 
  Unauthorized (HTTP 401).
```

Thanks!

**Comment by agungarifr** [comment]
Important In the Callback URL field, make sure to enter the following: http://127.0.0.1:1410
http://rtweet.info/articles/auth.html
