### ISSUE TITLE
Use 'best' token in list when searching for tweets

### ISSUE THREAD

**Issue by elliottmorris** [mkearney/rtweet#189]
Hey Mike, 

Have a coding need right now that requires searching a ton of tweets (probably need close to half a million!) beyond the rate limit. I don't want to wait 15 minutes after each search, so I have a list of 5 tokens. Declared as such: 

`
TOKEN1 <- 
  create_token(..args..)

TOKEN2 <- 
  create_token(..args..)

TOKEN3 <- 
  create_token(..args..)

TOKEN4 <- 
  create_token(..args..)

TOKEN5 <- 
  create_token(..args..)
`

Ideally, I want to be able to pass a `list` of these functions to a modified `search_tweets()` function and have it rotate through them, getting `18000 * 5 = 90,000` **unique** tweets after cycling through these tokens. 

Does rtweet currently have functionality for this? Any ideas for writing a function that could solve this use case? 

Elliott

**Comment by mkearney** [comment]
This is not idea. One can, somewhat quickly, get shut down by Twitter for this type of workflow. Their dev policy says one use per token. I've tried interpreted that narrowly, but Twitter didn't agree with me lol.

**Comment by elliottmorris** [comment]
OH yikes ok thanks
