### ISSUE TITLE
could not find function "lists_statuses"

### ISSUE THREAD

**Issue by everetr** [mkearney/rtweet#190]
I'm able to run other functions, like get_timeline(), successfully.

However, when I try to run the following:

`rtweet::lists_statuses(slug = 'senators', owner_user = 'cspan')`

I get the following error:

`Error: 'lists_statuses' is not an exported object from 'namespace:rtweet'`

When I run it without `rtweet::`, I get the following error:

`Error in lists_statuses(slug = "senators", owner_user = "cspan") : 
  could not find function "lists_statuses"`

There's documentation for this function. I can find it when I run `?lists_statuses`. What's going on?

FYI, I have the following packages loaded:

`library(ROAuth)
library(rtweet)
library(tidyverse)
library(twitteR)`

I'm using Ubuntu (artful).

**Comment by mkearney** [comment]
Oh, this must only be available in the Github version.

``` r
devtools::install_github("mkearney/rtweet")
```

That should work. You shouldn't need to load ROAth or twitteR.

**Comment by everetr** [comment]
Ah, got it. Thank you.
