### ISSUE TITLE
retryonratelimit not working

### ISSUE THREAD

**Issue by ThomasFrederickJohnson** [mkearney/rtweet#192]
Hi, this is a really great package, but I am having a little issue.

retryonratelimit = TRUE isnt working. I am only getting a maximum of 18000 records. I have searched through all of the previous issues that have discussed this, but I am still having no luck. The script and output are shown below.

Script:
```
library(devtools)
devtools::install_github("mkearney/rtweet")
library(rtweet)
TwitTest = search_tweets("#IWD2018 OR #InterationalWomensDay OR #WorldWildlifeDay", n=50000, retryonratelimit = TRUE, token = twitter_tokens, type="recent")
```

Output:
```
Searching for tweets...
This may take a few seconds...
Finished collecting tweets!
retry on rate limit...
waiting about 9 minutes...
Searching for tweets...
This may take a few seconds...
Finished collecting tweets!
Warning messages:
1: Rate limit exceeded - 88 
2: Rate limit exceeded

```

On another note, is there a way of searching between a specific time period within this package? Similar to the 'since =' & 'until=' in twitteR?

Thanks again for the package and any help you can offer!!!

**Comment by mkearney** [comment]
Yeah, since and until should work the same. Of course, you're only limited to past 9 days or so.

This bug was fixed a little while ago. Make sure you've installed the newest version of rtweet.

As for the warning messages, they are normal. When it hits the warning, it sleeps and then tries again.
