### ISSUE TITLE
Write to CSV Example

### ISSUE THREAD

**Issue by mhornin** [mkearney/rtweet#193]
I wondered if you could provide an example to write the data to CSV found here http://rtweet.info/reference/write_as_csv.html

I'm getting an error when I write the following:

write_as_csv(tmls, file_name= “tmls.csv”, prepend_ids = TRUE, na = "",
  fileEncoding = "UTF-8")

Error says
Error: unexpected ')' in "             fileEncoding = "UTF-8")"

Thanks for any suggestions

**Comment by mkearney** [comment]
This should now be fixed. I overhauled the data returned by default (it now joins users and tweets data for you). It should now be a simplified saving process–with fewer errors. Just provide data and file name and it shuld save one CSV file.
