### ISSUE TITLE
problem getting large amounts of followers

### ISSUE THREAD

**Issue by brunojus** [mkearney/rtweet#195]
My code to get followers
followers_usuario2 <-get_followers(usuario, n = dados_usuario$followers_count, retryonratelimit = T)

When I try to run this code, I received this message:

Waiting about -170.5 minutes for rate limit reset...
Error in Sys.sleep(as.numeric(rl$reset, "secs") + 2) : 
  invalid 'time' value

**Comment by mkearney** [comment]
what version do you have? I believe this was recently fixed

```{r}
packageVersion("rtweet")

## install newest
devtools::install_github("mkearney/rtweet")
```
