### ISSUE TITLE
retweet

### ISSUE THREAD

**Issue by prokulski** [mkearney/rtweet#196]
Do you plan to add function to make retweets? _post_retweet(status_id)_ for example?

**Comment by DevDataAnalyst** [comment]
search_tweets function already has an option to enable/disable RTs

**Comment by prokulski** [comment]
Yes, but I want to send retweet, not get retweets

czw., 15 mar 2018, 08:01 użytkownik DevDataAnalyst <notifications@github.com>
napisał:

**Comment by DataStrategist** [comment]
@prokulski all you have to do to retweet is copy the URL of the tweet itself and post that, twitter will automatically retweet it for you. You can then programatically create the links using:

```
Links <- paste0("https://twitter.com/",df$screen_name,"/status/",df$status_id) 
```

or some such

**Comment by prokulski** [comment]
Effect is almost correct (Twitter shows tweet), but this is not RT. Look:

This
    get_timeline("rstatspl") %>% select(status_id, is_retweet, screen_name, text)

gives

    # A tibble: 32 x 4
       status_id          is_retweet screen_name text                                                                                                   
     * <chr>              <lgl>      <chr>       <chr>                                                                                                  
     1 974209350276296704 FALSE      rstatspl    "Sieć neuronowa w SQLu? Proszę bardzo https://t.co/ozjMlBHjEZ\n\nWięcej na FB/DaneAnalizy: https://t.c…
     2 974208645587025920 FALSE      rstatspl    https://t.co/2p5KBWQUjU                                                                                
     3 974206096272273408 FALSE      rstatspl    https://t.co/z5j3nqpaHk                                                                                
     4 974205147210440709 FALSE      rstatspl    https://t.co/xCnBUManpY                                                                                
     5 974163318247059456 FALSE      rstatspl    Jak mija dzień @PiotrKarbowiak? Witam wśród obserwujących!                                             
     6 974150730935226369 FALSE      rstatspl    Najnowszy polski tweet z #rstats to https://t.co/BJn8GpUxY0 - polecam!                                 
     7 974060136128851968 FALSE      rstatspl    Najnowszy polski tweet z #rstats to https://t.co/YLlvaq4Pk0 - polecam!                                 
     8 974038741290401792 FALSE      rstatspl    Jak mija dzień @Muktada85? Witam wśród obserwujących!                                                  
     9 974027420004114433 FALSE      rstatspl    @m_nowicki94, nice to see You here!                                                                    
    10 974019988553175040 FALSE      rstatspl    @karol_majek @lemur78 Na podstawie tego co jest ustawione w profilu (pl albo angielski dla reszty)  

Twitts ID: 974208645587025920, 974206096272273408 , 974205147210440709 should have is_retweet = TRUE. 974060136128851968 is RT with comment.

This should use API's POST statuses/retweet/:id not POST statuses/update

**Comment by mkearney** [comment]
I actually didn't realize this wasn't already possible with rtweet. I'll look into this, though I'd estimate it'll take me 2-3 weeks.

**Comment by DataStrategist** [comment]
FWIW, I am using this method for a retweet bot... and I did get a nasty notification from twitter asking me to confirm I'm a human... perhaps they are upset that I'm 'reposting content', but not formally retweeting... so perhaps @prokulski 's suggestion is necessary. I'll let you know if I get banned :D

**Comment by yogesh-bansal** [comment]
@mkearney Do we have the option to retweet a tweet yet? 

@DataStrategist Did your account got banned, I am also running into the same issue with a retweet bot I am making.

**Comment by DataStrategist** [comment]
No, I'm not banned yet, but the retweeter isn't retweeting anymore... could
be a small technical glitch or maybe something bad happened... I haven't
had the chance to go in to check... but I haven't gotten any threatening
emails from Twitter. The other thing is that I'm not 100% sure that
retweeter bots are in compliance with the terms and conditions... because
it's not original work... Just something to think about.

**Comment by mkearney** [comment]
You can now retweet via `post_tweet()` https://github.com/mkearney/rtweet/commit/03ca2a5cb53eb95b748221abeb7a5ee0dde8bbdf

I was able to successfully retweet this tweet: https://twitter.com/joshscacco/status/1006951631164968960 using the code below.

``` r
post_tweet(retweet_id = "1006951631164968960")
```
