### ISSUE TITLE
Error in retweet

### ISSUE THREAD

**Issue by IMANTMN** [mkearney/rtweet#197]
How can get the following error fixed? adding http://127.0.0.1:1410 to Call Back didn't solve the issue. My httr version is 1.3.1:

rt <- search_tweets("#rstats", n = 18000, include_rts = FALSE)
Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission, :
Unauthorized (HTTP 401).

obesity <- search_tweets("#obesity", n=18000, include_rts = FALSE)
Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission, :
Unauthorized (HTTP 401).

token <- create_token(myappname, consumer_key, consumer_secret)
Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission,  : 
  Unauthorized (HTTP 401).

**Comment by DevDataAnalyst** [comment]
I had the same issue, but as @mkearney mentioned twitter had disabled the app within rtweet, so it wasn't working. as of now its working fine 👍

**Comment by IMANTMN** [comment]
@DevDataAnalyst @mkearney  Thank you for your response. I am still facing the same issue. Not working. What I am trying to do is finding the "frequency of tweets" of a term like 'obesity' in **each U.S. state**. 
> token <- create_token(Iman_Tahamtan, consumer_key, consumer_secret)
Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission,  : 
  Unauthorized (HTTP 401).

**Comment by mkearney** [comment]
This error is about not having a valid access token. You'll have to follow the steps described here: http://rtweet.info/articles/auth.html

**Comment by IMANTMN** [comment]
@mkearney Thanks, it worked very well. One more question: is there a way I could get the "tweet frequency" of a term in a specific year? I need to know, for example, how many times "obesity" has been tweeted in Tennessee in 2015.
