### ISSUE TITLE
Empty json when streaming various users

### ISSUE THREAD

**Issue by meneos** [mkearney/rtweet#199]
I'm trying to stream tweets from a list of accounts. I followed this tutorial but I'm still not getting results:
https://cran.r-project.org/web/packages/rtweet/vignettes/stream.html

This is my code. The two users are mine:

```
id <- "hmeleiros,idealisto_"
  start <- Sys.time()

  stream_tweets(
    q = prueba,
    parse = FALSE,
    timeout = 120, 
    token = twitter_token,
    file_name = "grenades.json")
```

This is what the console says:

```
Streaming tweets for 120 seconds...
Downloading: 110 B     Finished streaming tweets!
streaming data saved as grenades.json

```
When I parse the json file it imports an empty data object.

` rt <- parse_stream("grenades.json")
`

It does work if I stream just one user. But I need to do stream various users.

This is my session info:
```
R version 3.4.1 (2017-06-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] es_ES.UTF-8/es_ES.UTF-8/es_ES.UTF-8/C/es_ES.UTF-8/es_ES.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.0.5   rtweet_0.6.16

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.15    digest_0.6.15   utf8_1.1.3      crayon_1.3.4    mime_0.5       
 [6] R6_2.2.2        xtable_1.8-2    jsonlite_1.5    magrittr_1.5    pillar_1.2.1   
[11] httr_1.3.1      rlang_0.2.0     curl_3.1        rstudioapi_0.7  tools_3.4.1    
[16] readr_1.1.1     hms_0.4.1       httpuv_1.3.6.2  yaml_2.1.17     compiler_3.4.1 
[21] pkgconfig_2.0.1 htmltools_0.3.6 openssl_1.0.1   tibble_1.4.2
```

**Comment by meneos** [comment]
Sowwy, so what should I do? install git_hub master branch?

**Comment by mkearney** [comment]
Yep!

**Comment by meneos** [comment]
I reinstalled rtweet from github's master branch and is still not working. I'm pretty sure I do everything correctly. The following code returns retweets of, mentions or replies to the selected users but it doesn't return the users own tweets (the first two users are mine and I tried tweeting with them while streaming): 

```
sns <- "hmeleiros,idealisto_,ierrejon,lavapiesdondeva,latabacalera,hermanntertsch"
stream_tweets(q = sns, parse = TRUE,timeout = 30, token = twitter_token)
```

Also sometimes that code gives this error message:

```
Streaming tweets for 30 seconds...
Finished streaming tweets!
Error in if (nrow(att_df) > 0) { : argumento tiene longitud cero
```
The last thing is spanish for "Argument of length zero".

I tried with users_id instead of screennames and had the same problems.

**Comment by meneos** [comment]
Just to update:

If I try stream_tweets() with just one screen_name it doesn't work either. I think it's because rtweet thinks that I want to filter by search-like query. It does work if I use just a single user_id. If I do that it works perfectly but if I use a couple of user_id it does not work.

**Comment by meneos** [comment]
I think my problem has to do with how the stream_tweets function constructs de POST url. I solved the problem using this code instead of the stream_function:


```
users_id <- "974252591759724545,389748303"  # These are the user_id of the twitter profiles I want to stream.

POST(
url = paste0("https://stream.twitter.com/1.1/statuses/filter.json?follow=", users_id),
config(token=twitter_token, timeout = 30), 
write_disk(file_name, overwrite = TRUE), 
add_headers(`Accept-Encoding` = "deflate, gzip"))
```
I think that when stream_tweets constructs the url that is going to be passed into the url argument in the POST function it creates one with the argument track and it has to be follow. I hope I'm explaining correctly.

**Comment by mkearney** [comment]
@meneos 

Thanks for digging into this. You've revealed something that is indeed a bit confusing. If you supply a string of user IDs separated by commas, it uses the "track" method

``` r
## as comma separated stream
rtweet:::stream_params(c("974252591759724545,389748303"))
```

But if you supply a vector of user IDs it correctly uses the "follow" method.

``` r
## as vector of IDs
rtweet:::stream_params(c("974252591759724545", "389748303"))
```

Perhaps I will split the string just in case to test whether the "follow" method should be used.

**Comment by meneos** [comment]
You are welcome! I'm glad to contribute to this amazing package.
