### ISSUE TITLE
No date in "created_at"

### ISSUE THREAD

**Issue by emillykkejensen** [mkearney/rtweet#20]
The field created_at is NA for all tweets, I tried to pull.

**Comment by mkearney** [comment]
Which version are you using? If CRAN version, try upgrading to Github version:

    install.packages("devtools")
    devtools::install_github("mkearney/rtweet")

If you're already using Github version, can you provide your session info?

**Comment by emillykkejensen** [comment]
Just tried the github version and unfortunately it's the same. Here the session info:

```
R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Danish_Denmark.1252  LC_CTYPE=Danish_Denmark.1252    LC_MONETARY=Danish_Denmark.1252 LC_NUMERIC=C                   
[5] LC_TIME=Danish_Denmark.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rtweet_0.2.9

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7     withr_1.0.2     digest_0.6.10   dplyr_0.5.0     assertthat_0.1  R6_2.1.3        jsonlite_1.1    DBI_0.5-1      
 [9] git2r_0.15.0    magrittr_1.5    httr_1.2.1      curl_1.2        lazyeval_0.2.0  devtools_1.12.0 tools_3.3.0     rsconnect_0.4.3
[17] memoise_1.0.0   knitr_1.14      openssl_0.9.4   tibble_1.2     
```

**Comment by mkearney** [comment]
Damn. Date/time objects are a little handful. I'll have to fix it tomorrow. You can always set parse=FALSE to return nested list, parse data with parse_tweets, and then swap created_at vector in dataframe with created_at in unparsed object.

**Comment by emillykkejensen** [comment]
Okay - I will have a look at it. Thanks :)

**Comment by mkearney** [comment]
The easier solution is to wait about 12 hours, but in a pinch you could do what I described above.

**Comment by mkearney** [comment]
Thank you for reporting it!

**Comment by mkearney** [comment]
@emillykkejensen I may have fixed it. If you try again, let me know!

**Comment by emillykkejensen** [comment]
Sort og works now - it is character vector in this format: Wed Sep 21 12:20:21 +0000 2016.

Would be nice, if it was POSIXct though :-)

**Comment by mkearney** [comment]
Agreed. If it shows up as character, that means it failed three different attempts to convert to POSIXct. I'll figure it out yet, but I don't want to steal you of information while I do.

**Comment by mkearney** [comment]
just realized i had set an arg default the other way (or, at least, not the way i was thinking). not sure if that affects what you get, but it could.

**Comment by emillykkejensen** [comment]
Sorry - still character vector here...

**Comment by mkearney** [comment]
Added two more attempts at it. If it comes out as a character again, can you post some output of what your data looks like for me?

**Comment by mkearney** [comment]
I haven't received reports of any other problems with returning date (`created_at`) values, but I can't help but think there's a better way to handle dates. As I learn more about date classes in R, I'll keep this in mind, but I'm going to close this issue since it was specifically related to returning a non-NA value.

If you're experiencing any other date-related issues (formatting, timezone, etc.), I'd encourage you to start a new issue related to your specific problem or inquiry.

**Comment by emillykkejensen** [comment]
Sorry for the late reply - but it works now. created_at is class POSIXct with timezone UTC

**Comment by felixhaass** [comment]
Here's a small post script to this issue: I'm on a German machine and I had to manually set 

`Sys.setlocale("LC_TIME", "English")`

before `parse_stream()` correctly produced the `created_at` column (it was `NA` before, which led me to this issue). A small warning or hint in the help file for this would be helpful.

Thanks for the great package btw!

**Comment by mkearney** [comment]
@felixhaass Thanks! I was actually just reading some Emacs Speaks Statistics documentation about this language-based R problem. I agree it's definitely worth a comment in the file here.
