### ISSUE TITLE
new data format 

### ISSUE THREAD

**Issue by hupseb** [mkearney/rtweet#201]
Hi there,

somehow the new data format from the last commits do not work (109dff1 is still working). I am using RStudio and i write the tweets into the SQL Server like this:

rt <- search_tweets("#bitcoin -\"RT @\"", n = 1000, token = tk, lang = "en", until = crawldayNext)
sqlSave(conn, rt, tablename = "BitcoinTweets", append = TRUE)

I get the error:
STRING_ELT() can only be applied to a 'character vector'
and also
STRING_ELT() can only be applied to a 'character vector', not a 'pairlist'

I think a function in the RODBC cannot handle the new format :(

**Comment by hupseb** [comment]
Hmm... thanks for the feedback, but wouldn't it be better to keep "prep_for_csv()" seperately.

Saving the data to a MongoDB / MySQL is also not working. I don't want to keep my data in a CSV file.

**Comment by mkearney** [comment]
@hupseb Any particular reason you're saving to mongodb/mysql? And how much data are you working with? (if you don't mind me asking these things; I just like to understand how rtweet's being used :))
