### ISSUE TITLE
Authentication problem

### ISSUE THREAD

**Issue by pq90** [mkearney/rtweet#202]
I am having a problem with the authentification of the package right now. I hope that you can help me with it.

I load the package and use the next line of code to do the authentification:

`twitter_token <- create_token(app = "...", consumer_key = "...", consumer_secret = "...")`

However, once the browser opens the window with the message:

>Authentication complete. Please close this page and return to R.

I get the next message from R:

> Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error in gzfile(file, mode) : cannot open the connection
In addition: Warning message:
In gzfile(file, mode) :
  cannot open compressed file 'C:/Users/user_name1.rds', probable reason 'Permission denied'

Do you know what could be the problem? If I use the same credentials in another computer it works fine.  The file that it refers to does not exist, but neither does it in the other computer and works properly. I am using Windows10 if it helps.

Thank you very much in advance for your help.

**Comment by alexiaaslan** [comment]
Last week I was able to do the authentication with no problem but now, the exact same error as described above happens and ends up with the twitter_token object not being created. I'm also in Windows 10.

**Comment by mkearney** [comment]
I haven't been able to replicate the error message yet. Can you try setting `set_renv = FALSE`

``` r
library(rtweet)
twitter_token <- create_token(app = "...", 
    consumer_key = "...", 
    consumer_secret = "...", ,
    set_renv = FALSE)
search_tweets("rstats", token = twitter_token)
```

**Comment by joel23888** [comment]
It is possible to authenticate and get tokens without a browser/callback. The following worked for me, which just uses `httr` directly to get a token using the application's access token/secret in addition to the consumer key/secret. The approach is similar to that in `twitteR` after looking through its code.

In the below code, replace `APP_NAME`, `CONSUMER_KEY`, `CONSUMER_SECRET`, `ACCESS_TOKEN`, `ACCESS_TOKEN_SECRET` with your own app's name and key/token/secret information from the `Keys and Access Tokens` section in Application Management on [apps.twitter.com](url).

```
library(rtweet)

createTokenNoBrowser<- function(appName, consumerKey, consumerSecret, 
                                  accessToken, accessTokenSecret) {
  app <- httr::oauth_app(appName, consumerKey, consumerSecret)
  params <- list(as_header = TRUE)
  credentials <- list(oauth_token = accessToken, 
                      oauth_token_secret = accessTokenSecret)
  token <- httr::Token1.0$new(endpoint = NULL, params = params, 
                                     app = app, credentials = credentials)
  return(token)
}

token <- createTokenNoBrowser("APP_NAME","CONSUMER_KEY","CONSUMER_SECRET",
                            "ACCESS_TOKEN","ACCESS_TOKEN_SECRET")

data <- search_tweets("#rstats", n = 10, include_rts = FALSE,token = token)
```

Data returned:
```
> library(dplyr)
> glimpse(data)
Observations: 10
Variables: 87
$ user_id                 <chr> "701586174926831621", "701586174926831621", "701586...
$ status_id               <chr> "984306584611377152", "984306593188732928", "984306...
$ created_at              <dttm> 2018-04-12 05:45:51, 2018-04-12 05:45:54, 2018-04-...
$ screen_name             <chr> "globalizefm", "globalizefm", "globalizefm", "globa...
$ text                    <chr> "UK Parliament on twitter: 2018-04-05 to 2018-04-12...
$ source                  <chr> "Political Topic Tracker", "Political Topic Tracker...
$ display_text_width      <dbl> 87, 87, 101, 101, 83, 83, 82, 189, 106, 23
$ reply_to_status_id      <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
$ reply_to_user_id        <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
$ reply_to_screen_name    <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
$ is_quote                <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FA...
$ is_retweet              <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FA...
$ favorite_count          <int> 0, 0, 0, 0, 0, 0, 0, 0, 1, 0
$ retweet_count           <int> 0, 1, 1, 1, 1, 1, 1, 1, 1, 0
$ hashtags                <list> [<"ukpolitics", "rstats", "politispeak">, <"ukpoli...
$ symbols                 <list> [NA, NA, NA, NA, NA, NA, NA, NA, NA, NA]
$ urls_url                <list> [NA, NA, NA, NA, NA, NA, "activevoice.us/article.j...
$ urls_t.co               <list> [NA, NA, NA, NA, NA, NA, "https://t.co/H6uvs0Nhx9"...
$ urls_expanded_url       <list> [NA, NA, NA, NA, NA, NA, "http://www.activevoice.u...
$ media_url               <list> ["http://pbs.twimg.com/media/Daj1nDjU8AAFnC4.jpg",...
$ media_t.co              <list> ["https://t.co/Nn6SkeWD8n", "https://t.co/GFkbbqSW...
$ media_expanded_url      <list> ["https://twitter.com/globalizefm/status/984306584...
$ media_type              <list> ["photo", "photo", "photo", "photo", "photo", "pho...
$ ext_media_url           <list> [<"http://pbs.twimg.com/media/Daj1nDjU8AAFnC4.jpg"...
$ ext_media_t.co          <list> [<"https://t.co/Nn6SkeWD8n", "https://t.co/Nn6SkeW...
$ ext_media_expanded_url  <list> [<"https://twitter.com/globalizefm/status/98430658...
$ ext_media_type          <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
$ mentions_user_id        <list> [NA, NA, NA, NA, NA, NA, NA, NA, NA, "407200271"]
$ mentions_screen_name    <list> [NA, NA, NA, NA, NA, NA, NA, NA, NA, "Bioconductor"]
$ lang                    <chr> "en", "en", "en", "en", "en", "en", "en", "en", "pt...
$ quoted_status_id        <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, "98422210819969...
$ quoted_text             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, "plyranges is n...
$ quoted_created_at       <dttm> NA, NA, NA, NA, NA, NA, NA, NA, NA, 2018-04-12 00:...
$ quoted_source           <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
$ quoted_favorite_count   <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, 22
$ quoted_retweet_count    <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, 13
$ quoted_user_id          <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, "3159508016"
$ quoted_screen_name      <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, "_StuartLee"
$ quoted_name             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, "Stuart Lee"
$ quoted_followers_count  <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, 308
$ quoted_friends_count    <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, 739
$ quoted_statuses_count   <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, 1496
$ quoted_location         <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, "Melbourne, Aus...
$ quoted_description      <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, "PhD student at...
$ quoted_verified         <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, FALSE
$ retweet_status_id       <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
$ retweet_text            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
$ retweet_created_at      <dttm> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
$ retweet_source          <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
$ retweet_favorite_count  <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
$ retweet_retweet_count   <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
$ retweet_user_id         <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
$ retweet_screen_name     <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
$ retweet_name            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
$ retweet_followers_count <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
$ retweet_friends_count   <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
$ retweet_statuses_count  <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
$ retweet_location        <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
$ retweet_description     <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
$ retweet_verified        <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
$ place_url               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
$ place_name              <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
$ place_full_name         <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
$ place_type              <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
$ country                 <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
$ country_code            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
$ geo_coords              <list> [<NA, NA>, <NA, NA>, <NA, NA>, <NA, NA>, <NA, NA>,...
$ coords_coords           <list> [<NA, NA>, <NA, NA>, <NA, NA>, <NA, NA>, <NA, NA>,...
$ bbox_coords             <list> [<NA, NA, NA, NA, NA, NA, NA, NA>, <NA, NA, NA, NA...
$ name                    <chr> "globalizeandears", "globalizeandears", "globalizea...
$ location                <chr> "Cambridge, MA", "Cambridge, MA", "Cambridge, MA", ...
$ description             <chr> "Asking questions about our interconnected world. T...
$ url                     <chr> "https://t.co/ue0iNXQxg7", "https://t.co/ue0iNXQxg7...
$ protected               <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FA...
$ followers_count         <int> 24, 24, 24, 24, 24, 24, 2578, 86, 57711, 3696
$ friends_count           <int> 124, 124, 124, 124, 124, 124, 2960, 1078, 36, 2
$ listed_count            <int> 1, 1, 1, 1, 1, 1, 3241, 2, 1768, 126
$ statuses_count          <int> 1133, 1133, 1133, 1133, 1133, 1133, 71067, 194, 170...
$ favourites_count        <int> 1, 1, 1, 1, 1, 1, 195, 367, 2, 24
$ account_created_at      <dttm> 2016-02-22 01:55:53, 2016-02-22 01:55:53, 2016-02-...
$ verified                <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FA...
$ profile_url             <chr> "https://t.co/ue0iNXQxg7", "https://t.co/ue0iNXQxg7...
$ profile_expanded_url    <chr> "http://www.globalize.fm", "http://www.globalize.fm...
$ account_lang            <chr> "en", "en", "en", "en", "en", "en", "en", "en", "en...
$ profile_banner_url      <chr> "https://pbs.twimg.com/profile_banners/701586174926...
$ profile_background_url  <chr> "http://abs.twimg.com/images/themes/theme2/bg.gif",...
$ profile_image_url       <chr> "http://pbs.twimg.com/profile_images/70740324355556...
```

**Comment by Waqasejaz** [comment]
@joel23888 I tried your solution, but it doesn't seem to work as I get the following error
"Warning: 89 - Invalid or expired token.
Error in `$<-.data.frame`(`*tmp*`, "app", value = "appname") : 
  replacement has 1 row, data has 0"

Any idea what's not working?

**Comment by Waqasejaz** [comment]
@mkearney the issue persists despite trying everything even the Callback URL and re-checking the keys. So far no luck!

**Comment by joel23888** [comment]
@Waqasejaz would you mind posting your actual code substituting any secret information? Will see if I can point you in the right direction.

**Comment by Waqasejaz** [comment]
@joel23888 Thank you for your assistance, but I managed to solve the problem. The problem seems to be originated from checking "Enable Callback locking". Once I unchecked it, I could manage to get myself authenticated.

**Comment by dojo505** [comment]
@Waqasejaz Yes! I had the same issue. Unchecking the callback locking on the settings page did the trick.

**Comment by joel23888** [comment]
It is worth considering adding this functionality into `rtweet`. Unfortunately I cannot submit a pull request from where I am using this code. If one of you (@Waqasejaz or @dojo505) would like to submit a pull request including `createTokenNoBrowser` I think that would be helpful.

**Comment by Waqasejaz** [comment]
@joel23888 what exactly would you require in order to make your code functional for all?

**Comment by joel23888** [comment]
@mkearney what are your thoughts on adding this functionality to `rtweet`.

**Comment by Arf9999** [comment]
@joel23888 
I found your solution while searching for a solution to failed callback using RStudio Server on an AWS Ubuntu instance. 

I tried it on a local machine and it works perfectly, definitely should be added to rtweet as standard.

But, on RStudio Server, I get "Error: Not a valid access token" when running your example code. I have absolutely no idea how the exact same same token on a local machine works perfectly, but on the server it fails. Any idea on what could be causing this? In case it was a port issue, I have opened every port on the instance to all types of traffic, but that hasn't helped.

**Comment by joel23888** [comment]
@Arf9999 I am not entirely sure but could you try what @Waqasejaz by checking “Enable Callback Locking” on the Twitter side?

By the way, this worked for me while using RStudio Server.

**Comment by Arf9999** [comment]
@joel23888 Thanks for the feedback. I haven't managed to fix it, but have got a workaround by copying a token from my local machine and specifically mentioning `token=` in every function call.  Seems to be ok now.

**Comment by SCel1** [comment]
Am new to the rtweet package but I am also having this exact issue with the following error:

```
Authentication complete. 
Error in file(file, mode) : cannot open the connection
In addition: Warning message:
In file(file, mode) :
  cannot open file 'C:/Users/sulia1.rds': Permission denied
```

Not sure how to solve as the 'Enable Callback locking' box no longer exists as of June 12th ( see https://twittercommunity.com/t/action-required-sign-in-with-twitter-users-must-whitelist-callback-urls/105342 )

Thanks in advance for any help.

**Comment by AWMTransport** [comment]
Dear SCel1 - I had the same problem as you after a attempted to create a token. 
My error read:

`Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error in file(file, mode) : cannot open the connection
In addition: Warning message:
  In file(file, mode) :
  cannot open file 'C:/Users/woodburn1.rds': Permission denied`

I was able to resolve this problem by running RStudio as an administrator on my windows machine. You might try this or also try altering your exemptions for firewalls.

**Comment by HRK777** [comment]
Unfortunately, same problem persists over here for me. No option to "uncheck" callback locking anymore and the error message get's displayed. 

Anyone an idea what the error could be?

**Comment by odros** [comment]
This worked for me today. Insert your information inside the "", disable 'Sign in with Twitter', and don't set any callback URL in your app.

```
library(rtweet)

#App name
an <- ""
#API key
ak <- ""
#API secret key
ask <- ""
#Access token
at <- ""
#Access token secret
ats <- ""

t <- create_token(an, ak, ask, at, ats)
data <- search_tweets("", n = 100, include_rts = FALSE, token = t)
```
