### ISSUE TITLE
lookup_users  not working as expected

### ISSUE THREAD

**Issue by Arf9999** [mkearney/rtweet#203]
I'm trying to build a network map and as such I am populating a dataframe of unique user_id nodes based on mentions, retweets, quotes etc.

I have a dataframe of 1027 unique user_ids, but when I try to lookup_users on that frame I only get 690 rows returned. And it seems inconsistent, sometimes 520 rows, sometimes 580 rows. I can understand that thee may be some attrition due to suspended accounts or suchlike, but I can't understand why it varies so much within a short space of time.

Here's my script - maybe I've done something stupid:

```
##Populate node list for network map.

node_ids <- unique(filter(node_id_full, user_id != "" & !is.na(user_id))) ##get rid of empty rows, NAs and duplication for node_ids

node_users <- lookup_users(node_ids[1,"user_id"]) ##create node_users df

for (u in 2:nrow(node_ids)) {
  user_temp <- lookup_users(node_ids[u,"user_id"])
  node_users <- rbind(node_users, user_temp) ##populate node_users df with all node user detail
}
```

I did receive these 5 errors in the console (which are probably deleted or suspended users).
```
Error code: 17
No user matches for specified terms.
Error code: 17
No user matches for specified terms.
Error code: 17
No user matches for specified terms.
Error code: 17
No user matches for specified terms.
Error code: 17
No user matches for specified terms.
```

Just for clarity, this is what node_ids looks like:
```
> glimpse(node_ids)
Observations: 1,027
Variables: 1
$ user_id <chr> "206952204", "369493249", "409097105", "40456464", "186143241",...
```

**Comment by mkearney** [comment]
Try this

``` r 
node_ids <- unique(filter(node_id_full, user_id != "" & !is.na(user_id))
node_users <- lookup_users(node_ids$user_id)
node_users
```

**Comment by Arf9999** [comment]
Hah, it seems that I've overcomplicated things.

Let me try that.  Thanks.

**Comment by Arf9999** [comment]
Suggestion works perfectly.  Closing.  Thanks again.
