### ISSUE TITLE
Unauthorized (HTTP 401) error

### ISSUE THREAD

**Issue by Qua111** [mkearney/rtweet#204]
I have been using this package for about 2 weeks know, and everything worked fine.
Since somewhere mid last week I keep getting the error:
"Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission,  : 
  Unauthorized (HTTP 401)."

I have even created a new twitter app, with the same settings and default callback url, but still nothing. 
Today i have deleted all past R data, and reinstalled both R and Rstudio, hoping it would then be a history issue. Still no luck.

Any idea as to what could be causing this issue?

**Comment by AmeliaMN** [comment]
I'm having the same problem. I never got a pop-up browser window (tried changing browser, as in issue #178), and even when I authenticate with consumer/secret keys I get the error.

**Comment by mkearney** [comment]
Can you all check the current TWITTER_PAT

``` r
Sys.getenv("TWITTER_PAT")
```

Does a path exist? Is it to a token that you made? Or is it something like ".rtweet_token1"?

**Comment by naomiggg** [comment]
Hi @mkearney I have the same problem and I just did what you said, it is just showing me [1] ""

**Comment by AmeliaMN** [comment]
I was also getting an empty string, but I went back and followed [the instructions](http://rtweet.info/articles/auth.html) for consumer/secret keys again and realized I had missed a step you marked **Important** ("In the Callback URL field, make sure to enter the following: http://127.0.0.1:1410"). When I changed that setting and tried again, running 
```
twitter_token <- create_token(
  app = appname,
  consumer_key = key,
  consumer_secret = secret)
```
caused a browser window to open and the twitter authorization page to pop up! Now my `Sys.getenv("TWITTER_PAT")` has a path.

**Comment by jsta** [comment]
In my case `TWITTER_PAT` was pointing to a file that no longer exists.

**Comment by EOneita** [comment]
Hi- I have been getting that issue too, even with the correct callback and creation of a twitter token. Here is my session info:

`R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.1

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.7.4   rtweet_0.6.20 twitteR_1.1.9 httr_1.3.1    httpuv_1.4.1 
[6] openssl_1.0.1

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16      bindr_0.1         magrittr_1.5      hms_0.4.2        
 [5] munsell_0.4.3     bit_1.1-12        colorspace_1.3-2  viridisLite_0.3.0
 [9] rjson_0.2.15      R6_2.2.2          rlang_0.2.0       plyr_1.8.4       
[13] tools_3.4.3       grid_3.4.3        gtable_0.2.0      DBI_0.8          
[17] assertthat_0.2.0  yaml_2.1.18       bit64_0.9-7       lazyeval_0.2.1   
[21] tibble_1.4.2      bindrcpp_0.2      gridExtra_2.3     readr_1.1.1      
[25] ggplot2_2.2.1     later_0.7.1       viridis_0.5.1     promises_1.0.1   
[29] curl_3.1          glue_1.2.0        compiler_3.4.3    pillar_1.2.1     
[33] scales_0.5.0      jsonlite_1.5      pkgconfig_2.0.1 `

There is also no path that currently exists.

Thank you in advance for assistance.

**Comment by MrMetlHed** [comment]
For what it's worth, if you're having trouble try unchecking the "Enable Callback Locking" checkbox on the app page. I didn't see that in the instructions, and was getting the same error as y'all until I unchecked it.

**Comment by EOneita** [comment]
Thanks @MrMetlHed - I tried that hoping it would work, but unfortunately still encountering the same error. Very baffling!

**Comment by franciscorodriguez92** [comment]
Thanks @MrMetlHed! It helped me a lot :)

**Comment by vlad43210** [comment]
I'm getting the same issue :( Checked for extra spaces, made sure callback URL is set to http://127.0.0.1:1410, made sure Enable Callback Locking is checked. Nothing :( Any ideas? 

I'm running RStudio 1.1.447 with R 3.5.0 and I installed rtweet from source as indicated on the github page: https://github.com/mkearney/botrnot

**Comment by franciscorodriguez92** [comment]
@vlad43210 Did you uncheck the "Enable Callback Locking" checkbox as @MrMetlHed pointed out?

**Comment by vlad43210** [comment]
That did it! Sorry, I misread "uncheck" as "check" -- whoops! That did it, and the auth flow worked, hooray :)

**Comment by nandanosql** [comment]
But for me It is not working. 
I unchecked it but still getting 

> > 
> > twitter_token <- create_token(app = appname,consumer_key = key,consumer_secret = secret)
> Error in curl::curl_fetch_memory(url, handle = handle) : 
>   Timeout was reached: Connection timed out after 10000 milliseconds

**Comment by tyluRp** [comment]
Thanks @MrMetlHed , unchecking that box fixed the issue for me.
