### ISSUE TITLE
retweet_count and favorite_count in streaming mode always returns 0

### ISSUE THREAD

**Issue by thomas-keller** [mkearney/rtweet#213]
Hi, I noticed this when parsing my weird old jsons, but it seems that newly collected streams also have this behavior. I'm on rtweet_0.6.20 and pulled down the dev version in the last day or so.

The original tweet package will always have a retweet_count of 0, which seems to be the field you are consistently parsing. If you back out in the json structure to the retweet level, that level will properly have favorites and retweets > 0 in the streaming data (when it actually exists). I was going to paste an example tweet, but with the retweet structure it gets extremely long.

**Comment by mkearney** [comment]
This makes sense for retweets (there's one gllobal count for retweets) but for favorites, too? I thought Twitter counted the number of favorites for each user's retweets (and thus it would make sense if streaming always yielded a favorites_count of zero).

Thanks for pointing this out, btw. I'll try to get the fix committed soon.

**Comment by thomas-keller** [comment]
See this snippet of a retweet json packet, you see both the retweet_count and favorite_count and incremented to the number you would get from the search api at the time it passes through the stream.

"retweet_count":24,"favorite_count":65

**Comment by thomas-keller** [comment]
Actually, would you mind if I tried to patch this? It looks like the relevant code is in the tweets_to_tbl_ and wrangle_retweet functions. It'll end up being slower, but I'll finally end up contributing to a  open-source project.

Its cool either way. I'll bail if I can't figure it out in a day or two.

**Comment by mkearney** [comment]
Absolutely! Just let me know if you do bail, and I'll jump in. Just know that the code used to be 10X as confusing (and bad) about 6-8 months ago lol
