### ISSUE TITLE
Problem with lookup_users() in Windows 10

### ISSUE THREAD

**Issue by sms1962** [mkearney/rtweet#216]
Generally, the lookup_users() works perfectly, but sometimes I have a problems with downloading data from some accounts. For example, a code:

`x <- lookup_users("981559669771685894")`

specifies the error

 "Error in fix.by(y.y, y) : 'by' must specify a uniquely valid column"

The error occurs only in Windows 10 (R 3.4.4 & Rstudio 1.1.423) and, as I suppose, only in the case of accounts that did not send a single tweet.  
In Linux everything is OK.

**Comment by mkearney** [comment]
I think this behavior has been fixed (to return an empty data frame). What version of rtweet were you using?

**Comment by mkearney** [comment]
This should now be fixed @sms1962!
