### ISSUE TITLE
Stream Tweets Issue

### ISSUE THREAD

**Issue by JacobCoblentz** [mkearney/rtweet#22]
> stream_tweets("trump", timeout =60)
Streaming tweets for 60 seconds...
  |=========================================================================================================| 100%
opening file input connection.
Error: lexical error: invalid char in json text.
                                       <html>\n<head>\n<meta http-equi
                     (right here) ------^
closing file input connection.

Downloaded the Github version of rtweet too- what's causing this? Sorry to keep submitting so many issues

**Comment by mkearney** [comment]
It worked for me. Can you provide your sessionInfo()?

**Comment by mkearney** [comment]
It could be you need to upgrade the `jsonlite` package or a problem with your connection. I kind of think it's the latter, because it looks like you may be getting html meta data (presumably with an error message) instead of a json structure.

**Comment by JacobCoblentz** [comment]
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] httpuv_1.3.3 rtweet_0.2.9 jsonlite_1.1

loaded via a namespace (and not attached):
 [1] httr_1.2.1       colorspace_1.2-6 scales_0.4.0     R6_2.1.3         plyr_1.8.4       tools_3.3.1     
 [7] gtable_0.2.0     curl_2.0         Rcpp_0.12.7      ggplot2_2.1.0    grid_3.3.1       openssl_0.9.4   
[13] munsell_0.4.3

**Comment by mkearney** [comment]
This should now be fixed. Stream requests can still fail on occasion, but as long as you specify a file_name, the json text should be saved. I've added a safety valve in the parse_stream function that should handle most errors, but please let me know if you experience any more! Until then, I'm making this as closed.
