### ISSUE TITLE
Delete tweets with rtweet?

### ISSUE THREAD

**Issue by iamvishnurajan** [mkearney/rtweet#223]
Is it possible to use rtweet for deletion of tweets? I looked through the documentation and can see that one can un-favorite a tweet (using destroy = TRUE), however I did not come across anything that indicated the ability to delete a tweet.

**Comment by mkearney** [comment]
At the current time I do no believe it's possible.

**Comment by mkearney** [comment]
Turns out it was an easy add. Just supply a status ID to the new `destroy_id` parameter!

**Comment by iamvishnurajan** [comment]
Excellent - thanks a ton for the quick fix!
