### ISSUE TITLE
Installation fails (due to bit and bit64 encoding issues?)

### ISSUE THREAD

**Issue by mgagliol** [mkearney/rtweet#224]
Hello,

If I try to install the package, it fails installing the bit64 dependency:

> `* installing *source* package ‘bit64’ ...`
> `** package ‘bit64’ successfully unpacked and MD5 sums checked`
> `Warning in writeLines(paste0(c(out[is_not_empty]), eor), file) :`
 >  `invalid char string in output conversion`
> [...]
> `Warning: S3 methods ‘!.bit’, ‘!.bitwhich’, ‘!=.bit’, ‘!=.bitwhich’, ‘&.bit’, ‘&.bitwhich’, ‘[.bit’, ‘[[.bit’, ‘[[<-.bit’, ‘[<-.bit’, ‘|.bit’, ‘|.bitwhich’, ‘==.bit’, ‘==.bitwhich’, ‘all.bit’, ‘all.bitwhich’, ‘all.ri’, ‘any.bit’, ‘any.bitwhich’, ‘any.ri’, ‘as.bit.bit’, ‘as.bit.bitwhich’, ‘as.bit.double’, ‘as.bit.integer’, ‘as.bit.logical’, ‘as.bit.ri’, ‘as.bit.which’, ‘as.bitwhich.bit’, ‘as.bitwhich.bitwhich’, ‘as.bitwhich.double’, ‘as.bitwhich.integer’, ‘as.bitwhich.logical’, ‘as.bitwhich.ri’, ‘as.bitwhich.which’, ‘as.double.bit’, ‘as.double.bitwhich’, ‘as.double.ri’, ‘as.integer.bit’, ‘as.integer.bitwhich’, ‘as.integer.ri’, ‘as.logical.bit’, ‘as.logical.bitwhich’, ‘as.logical.ri’, ‘as.which.bit’, ‘as.which.bitwhich’, ‘as.which.default’, ‘as.which.ri’, ‘c.bit’, ‘c.bitwhich’, ‘length.bit’, ‘length [... truncated]`
> `Error: package or namespace load failed for ‘bit’:`
> `.onLoad failed in loadNamespace() for 'bit', details:`
>  `call: bit_init()`
>  `error: could not find function "bit_init"`
> `Error : package ‘bit’ could not be loaded`
> `ERROR: lazy loading failed for package ‘bit64’`

One thing I noticed is that files in the `bit64` package are encoded as `ISO-8559`, while my system (Linux) is configured to use `UTF-8`, but I guess this should not normally be a problem?

My `version`:
> platform       x86_64-pc-linux-gnu         
> arch           x86_64                      
> os             linux-gnu                   
> system         x86_64, linux-gnu           
> status                                     
> major          3                           
> minor          4.4                         
> year           2018                        
> month          03                          
> day            15                          
> svn rev        74408                       
> language       R                           
> version.string R version 3.4.4 (2018-03-15)
> nickname       Someone to Lean On          

Thanks a lot for your suggestions!

MG

**Comment by mkearney** [comment]
This bug should be fixed now. Try installing the most recent [Github] version.

``` r
## install devtools package if it's not already
if (!requireNamespace("devtools", quietly = TRUE)) {
  install.packages("devtools")
}

## install dev version of rtweet from github
devtools::install_github("mkearney/rtweet")

## load rtweet package
library(rtweet)
```
