### ISSUE TITLE
Saving to csv problem

### ISSUE THREAD

**Issue by Scapin56** [mkearney/rtweet#226]
Hi, 
I have a data sheet of a user followers I want to save as a csv file. 
I tried save_as_csv and write_as_csv but that did not work, here is what I got, I replaced my data sheet name by **X**:

save_as_csv(**X**, test)
Error in stopifnot(is.character(file_name), length(file_name) == 1) : 
  object 'test' not found

AND:

save_as_csv(**X**, test, prepend_ids = TRUE, na = "", fileEncoding = "UTF-8")
Error in stopifnot(is.character(file_name), length(file_name) == 1) : 
  object 'test' not found

I tried to put a folder path before the file_name, I tried to create a csv file named "test", etc etc...doesn't work.

**Comment by mkearney** [comment]
The error message says it's not finding the symbol `test`. Just try providing a character string with the name you'd like to save it as (you don't have to create a CSV or anything; it'll do that for you):


``` r
save_as_csv(X, "my-data-set.csv")
```

Also try the newest Github version

``` r
## install devtools package if it's not already
if (!requireNamespace("devtools", quietly = TRUE)) {
  install.packages("devtools")
}

## install dev version of rtweet from github
devtools::install_github("mkearney/rtweet")

## load rtweet package
library(rtweet)
```
