### ISSUE TITLE
Does ts_plot always use UTC?

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [mkearney/rtweet#227]
I am attempting to plot tweets in a different time zone, and my approach was to write over the `created_at` column with `lubridate::with_tz`. The conversion works however when I plot these data using `ts_plot` the x-axis is in UTC again. I think the following might be the reason:

https://github.com/mkearney/rtweet/blob/1f7f5c3c62a39b0dcd626a7f8a3fb559cd48f319/R/ts_plot.R#L163

Is this the intended functionality of the `ts_plot` function? If not, how can I change the timezone used in the x-axis?

**Comment by mkearney** [comment]
This problem drove me nuts a few months ago, so I decided just to hardwrite "UTC" into the `ts_*()` functions. I gave it another look and just committed an update I think allows you to specify a desired timezone...

``` r
## search for tweets
rt <- search_tweets("rstats", n = 500)

## with default timezone (UTC)
ts_data(rt, "hours")

## with american central time zone
ts_data(rt, "hours", tz = "US/Central")
```

**Comment by opladynunesp** [comment]
I tried this and the error message was:

Error in strptime (xx, f, tz = tz): input string is too long

Any ideas for me?

**Comment by djpeluca** [comment]
Is this still a thing? I'm trying to use tz por ts_plot it's always printing UTC time. thanks
this is my code:
(working fine for the la subtitle)
`#Plot timeline
ts_plot(mañanatweets, "mins", tz = "America/Montevideo") +
  labs(x = NULL, y = NULL,
       title = "Frequency of tweets",
       subtitle = paste0(format(min(mañanatweets$created_at), "%d/%m/%Y - %H:%M:%S", tz = "America/Montevideo"), " to ", format(max(mañanatweets$created_at),"%d/%m/%Y - %H:%M:%S", tz = "America/Montevideo")),
       caption = "Data collected from Twitter's REST API via rtweet") `
