### ISSUE TITLE
Timeout was reached: Connection timed out after 10000 milliseconds

### ISSUE THREAD

**Issue by nandanosql** [mkearney/rtweet#229]
Hi , 
I am using as per documentation which I can able to see. Even provided same callback url as mentioned. 
But I am getting below error. 

> > twitter_token <- create_token(app = appname,consumer_key = key,consumer_secret = secret)
> Error in curl::curl_fetch_memory(url, handle = handle) : 
>   Timeout was reached: Connection timed out after 10000 milliseconds

Please tell me how to resolve this query. 
Thanks

**Comment by mkearney** [comment]
Do other HTTP requests work for you? Run this code below and make sure it prints `Status: 200`

``` r
> httr::GET("http://cran.r-project.org/Rlogo.jpg")
Response [http://cran.r-project.org/Rlogo.jpg]
  Date: 2018-05-14 19:57
  Status: 200
  Content-Type: image/jpeg
  Size: 16 kB
<BINARY BODY>
```

If that doesn't work, then you've got a bigger issue going on with how R is trying to interact with the internet. I'd recommend googling the error message you received when making the above request.

If it does work, then can you print your session info?

``` r
sessionInfo()
```

**Comment by Oriojas** [comment]
https://github.com/jeroen/curl/issues/72

**Comment by sanjaysarowa** [comment]
Change Your Internet connection.

**Comment by gvegayon** [comment]
I know is kind of old, but you can always extend the timeout using `curl`'s `connecttimeout` option. For some reason, the `timeout()` function included in `httr` does not work for me. What did worked was setting `config`, e.g.:

```r
httr::GET("http://cran.r-project.org/Rlogo.jpg", config = httr::config(connecttimeout = 60))
```
Will tell `curl` to wait 60 seconds for the connection to establish before returning an error.

**Comment by tyq521** [comment]
I got the same problem. HTTP request does work for me and I can also print my session info, then what can I do to resolve this error?

**Comment by llrs** [comment]
@tyq521 it might have been a problem on twitter side or on you connection. Try again later and hopefully it will be resolved.

**Comment by AlestWalter** [comment]
> I know is kind of old, but you can always extend the timeout using `curl`'s `connecttimeout` option. For some reason, the `timeout()` function included in `httr` does not work for me. What did worked was setting `config`, e.g.:
> 
> ```r
> httr::GET("http://cran.r-project.org/Rlogo.jpg", config = httr::config(connecttimeout = 60))
> ```
> 
> Will tell `curl` to wait 60 seconds for the connection to establish before returning an error.

This helped me on another project, and it was exactly the solution I was looking for. Thank you!
