### ISSUE TITLE
lists_memberships() error

### ISSUE THREAD

**Issue by srhrnkn** [mkearney/rtweet#230]
I'm getting this error when trying to call list_memberships()

```
> lists_memberships(user = "kearneymw")
Error: All components of query must be named
```

Grabbed the latest build via  devtools::install_github but that didn't help. 

Thanks!

**Comment by mkearney** [comment]
I could replicate the error when setting `filter_to_owned_lists = TRUE`

``` r
lists_memberships(user = "kearneymw", filter_to_owned_lists = TRUE)
```

But I could see how the source of the problem could still happen, so the fix I just committed should hopefully solve your issue as well.

**Comment by srhrnkn** [comment]
It did - thank you!
