### ISSUE TITLE
Just making sure you saw these API deprecations & removals (apologies if you knew it already)

### ISSUE THREAD

**Issue by hrbrmstr** [mkearney/rtweet#231]
https://blog.twitter.com/developer/en_us/topics/tools/2017/announcing-more-functionality-to-improve-customer-engagements-on-twitter.html

As we outlined in April, User Streams and Site Streams, along with the legacy Direct Message endpoints, will be replaced by improved products such as Account Activity API. We are providing notice to all Twitter developers that on Tuesday June 19, 2018 we are retiring the following services and endpoints:

- User Streams
- Site Streams
- `GET direct_messages`
- `GET direct_messages/sent`
- `GET direct_messages/show`
- `POST direct_messages/new`
- `POST direct_messages/destroy`

**Comment by nzstefinitely** [comment]
Was this not [indefinitely delayed](https://twitter.com/TwitterDev/status/982346370882461696?ref_src=twsrc%5Etfw)? 

Twitter Dev: "Last year we announced our plan to retire Site Streams & User Streams, and replace them with the Account Activity API (currently in beta). We are delaying the scheduled June 19th deprecation date."

**Comment by hrbrmstr** [comment]
I saw some chatter yesterday that has suggested this the indefinite part is no longer indefinite (I cannot post the link as it's not to a public resource nor can I disclose the resource).

**Comment by nzstefinitely** [comment]
Seems you were very much correct. August 16th is the new date.
