### ISSUE TITLE
retweet_retweet_count field missing in get_timelines()

### ISSUE THREAD

**Issue by diplodata** [mkearney/rtweet#236]
Am I right that `get_timelines` omits the `retweet_retweet_count` field that `get_timeline` reports?  I've just hit an issue joining datasets sourced by both methods, and this field is missing from get_timelines..

**Comment by mkearney** [comment]
Try updated to most recent version of rtweet

``` r
devtools::install_github("mkearney/rtweet")
```

If it still doesn't work, then can you provide code that replicates the error? For now I'm closing this issue as the `retweet_retweet_count` field seems to be returned for me.

``` r
> tmls <- get_timelines(c("kearneymw", "cstonehoops", "natesilver538"), n = 500)
> tmls$retweet_retweet_count

> sum(!is.na(tmls$retweet_retweet_count))
[1] 406

```
