### ISSUE TITLE
lookup_coords() doesn't always return map coordinates. (Inconsistent)

### ISSUE THREAD

**Issue by Arf9999** [mkearney/rtweet#237]
I've got a script that pulls the coordinates of a country in order to create the map to plot geo-located tweets but it seems to fail inconsistently. After doing some checking it seems that `lookup_coords` sometimes returns empty lists.  It is difficult to replicate, but I've copied some tests from the console. It returns the correct values twice and then fails the third time on the identical request.

(In case it makes a difference, this is using RStudio on an AWS instance)

```
> country <- "South Africa"
> lookup_coords(country)
$place
[1] "South Africa"

$box
   sw.lng    sw.lat    ne.lng    ne.lat 
 16.28170 -47.13135  38.22169 -22.12542 

$point
      lat       lng 
-30.55948  22.93751 

attr(,"class")
[1] "coords" "list"  
> lookup_coords(country)
$place
[1] "South Africa"

$box
   sw.lng    sw.lat    ne.lng    ne.lat 
 16.28170 -47.13135  38.22169 -22.12542 

$point
      lat       lng 
-30.55948  22.93751 

attr(,"class")
[1] "coords" "list"  
> lookup_coords(country)
$place
[1] "South Africa"

$box
   sw.lng    sw.lat    ne.lng    ne.lat 
 16.28170 -47.13135  38.22169 -22.12542 

$point
      lat       lng 
-30.55948  22.93751 

attr(,"class")
[1] "coords" "list"  
> lookup_coords(country)
$place
[1] "South Africa"

$box
NULL

$point
NULL

attr(,"class")
[1] "coords" "list" 
```

**Comment by mkearney** [comment]
This is a hacky request to google maps, which, technically, requires an API key. I'd just be careful to rely too heavily on this...it's mostly just there for convenience and not really designed according to best practices (if it's not central to interacting with Twitter's API then i try to limit the amount of time i spend on it).
