### ISSUE TITLE
Followers (get_followers) for multiple user_ids or screen_names

### ISSUE THREAD

**Issue by holnburger** [mkearney/rtweet#238]
Is it possible to introduce the same function to `get_followers` as to `get_friends`? 

For example: It's possible to get the friends of multiple users with 
`get_friends(c("cnn", "abc"))`
```
1 friend networks collected!
2 friend networks collected!
```

whereas `get_followers(c("cnn", "abc"))` just returns
`Error: isTRUE(length(user) == 1) is not TRUE`.

For consistency and improvement of the package it should work on both.

**Comment by mkearney** [comment]
Followers and friends are not the same. They have different properties and often get used in different ways. For example, Twitter actually limits the number of friends to 5000 (it's possible to increase limit but it requires users to maintain a certain minimum friend:follower ratio) whereas there is no limit to the number of followers. So while it's quite rare that users follow more than 5000 accounts, which conveniently is the max number of friend IDs returned by a single API call, it's fairly common to have users with wayyy more than 5000 followers. So, in terms of rtweet mechanics, this means `get_followers()` would have to decide whether to get the first 5000 followers (takes 1 or 2 seconds) or ALL of the followers (to get all of realdonaldtrump's, for example, would take about a week) for each account. I decided it made sense in the case of `get_friends()` (b/c 5000 is actually a platform limit) but not for `get_followers()`.

I'd recommend using lapply/purrr::map or (for more control over rate limit/sleep calls) a `for` loop e.g.,


``` r
flw <- vector("list", length(users))
n <- 75000

for (i in seq_along(flw)) {
  flw[[i]] <- get_followers(users[i], n = n)
  Sys.sleep(60 * 15)
}
```

**Comment by holnburger** [comment]
Thanks a lot for your explanation, feedback and suggestions!
