### ISSUE TITLE
get_timeline() returns error

### ISSUE THREAD

**Issue by itsnickyjones** [mkearney/rtweet#239]
My script has been humming along for several weeks now and this morning it broke. Attempting to grab a timeline returns an error. Not sure if this is related to some of the new API changes Twitter is planning to/has already introduced. I'm authenticating just fine and I am able to search trends. Please let me know if I should provide more detail. 

Example code:
`mytweets <- get_timeline("itsnickyjones", n = 1000, check=T, token = twitter_token)`

Returns this error:
**Error in if (n.times == 0L) { : argument is of length zero**

**Comment by JBGruber** [comment]
I have the same problem. My script runs every day and worked fine in the last couple of months but suddenly stopped yesterday morning.

**Comment by mikechapple** [comment]
Same problem here, but the error that I'm seeing is slightly different:

Error in `$<-.data.frame`(`*tmp*`, "reset", value = NA_character_) : 
  replacement has 1 row, data has 0

**Comment by itsnickyjones** [comment]
I get that same error as you when I'm in Linux. The one I posted is on my Windows machine.

**Comment by hrbrmstr** [comment]
Twitter is having API issues right now
https://twittercommunity.com/t/application-rate-limit-status-broken/106429/3

**Comment by sadettindemirel** [comment]
I'm having the **same problem** 
Error in `$<-.data.frame`(`*tmp*`, "reset", value = NA_character_) : 
  replacement has 1 row, data has 0

**Comment by hrbrmstr** [comment]
@sadettindemirel Twitter is having API issues right now
https://twittercommunity.com/t/application-rate-limit-status-broken/106429/3

**Comment by itsnickyjones** [comment]
They may have fixed the rate limit issue (they must be working on it!). I'm going to close this for now, since my script appears to be running normally and this issue is duplicated across several other posts.

**Comment by JBGruber** [comment]
Works fine again for me too. Thanks for the update @itsnickyjones
