### ISSUE TITLE
rate_limit error

### ISSUE THREAD

**Issue by pwsmfia** [mkearney/rtweet#241]
rate_limit function gives these errors.

data frame with 0 columns and 0 rows

I tried another computer, givees

Error in `$<-.data.frame`(`*tmp*`, "reset", value = NA_character_) :replacement has 1 row, data has 0

**Comment by Arf9999** [comment]
A few rtweet functions are giving the same error. It looks like an API change from twitter.

**Comment by hrbrmstr** [comment]
https://twittercommunity.com/t/application-rate-limit-status-broken/106429/3
