### ISSUE TITLE
Error to start collecting and analyzing Twitter data

### ISSUE THREAD

**Issue by franklinayres** [mkearney/rtweet#242]
Hello,
I am trying to execute the samples provided but I am getting errors when execute then. I am using R-3.5.0-win and RStudio-1.1.453. Please find the errors below:

##Twitter rate limits cap the number of search results returned to 18,000 every 15 minutes. To request more than that, simply set retryonratelimit = TRUE and rtweet will wait for rate limit resets for you.

## search for 250,000 tweets containing the word data
rt <- search_tweets(
  "data", n = 250000, retryonratelimit = TRUE
)
Error in if (n <= remaining || !retryonratelimit) { : 
  missing value where TRUE/FALSE needed
  
## get them all (this would take a little over 5 days)
cnn_flw <- get_followers(
  "cnn", n = cnn$followers_count, retryonratelimit = TRUE
)
Error in vector("list", n.times) : invalid 'length' argument

## get user IDs of accounts followed by CNN
tmls <- get_timelines(c("cnn", "BBCWorld", "foxnews"), n = 3200)
Error in if (n.times == 0L) { : argument is of length zero

**Comment by hrbrmstr** [comment]
Twitter is having API issues right now
https://twittercommunity.com/t/application-rate-limit-status-broken/106429/3

**Comment by Arf9999** [comment]
It seems Twitter has resolved the issue. 
https://twittercommunity.com/t/application-rate-limit-status-broken/106429/12

**Comment by hrbrmstr** [comment]
aye. it's working for me as of this afternoon (EDT) but wasn't earlier even after they claimed it was fixed.
