### ISSUE TITLE
Problem collecting tweets with search_tweets() function

### ISSUE THREAD

**Issue by franciscorodriguez92** [mkearney/rtweet#245]
Hi!

I've been trying to collect tweets with the following code:
```
library("rtweet")
library("tidyverse")
terminos <- c("feminazi", '"a la cocina"', '"a fregar"', "marimacho", "ninata", '"mujer tenias que ser"', '"las feministas"',
              '"en tus dias"')
create_corpus <- function(search_pattern, n = 5, lang = "es"){
  tweets <- search_pattern %>% map_df(function (x) search_tweets(x, n=n, include_rts = FALSE, lang = lang, verbose = FALSE,
                                                                 retryonratelimit = TRUE, type = "mixed") %>% mutate(termino=x))
  return (tweets)
}

corpus <- create_corpus(terminos, n = 15000)
```
And I'm getting the following error:

Error in Sys.sleep(reset + 2) : invalid 'time' value
In addition: Warning messages:
1: Rate limit exceeded - 88

**Comment by mkearney** [comment]
@franciscorodriguez92 try updating to the current dev version of rtweet

``` r
devtools::install_github("mkearney/rtweet")
```

Also, I'd recommend setting `n = 100` as it will require the same number of API requests as setting `n = 5`.

**Comment by franciscorodriguez92** [comment]
Using a for loop I get the same error:

```
create_corpus2 <- function(search_pattern, n, lang = "es"){
  tweets <- data.frame()
  for (q in search_pattern){
    tweets_temp <- search_tweets(q, n=n, include_rts = FALSE, lang = lang, verbose = FALSE,
                                 retryonratelimit = TRUE, type = "mixed") %>% mutate(termino=q)
    tweets <- bind_rows(tweets, tweets_temp)
  }
  return (tweets)
}
corpus <- create_corpus2(terminos, n = 15000)
```
Error in Sys.sleep(reset + 2) : invalid 'time' value

If I set n = 100, it works properly (mainly because it doesn't require retries). The problem is when setting `n = 15000` because the variable `reset` is a negative value.

**Comment by franciscorodriguez92** [comment]
I've seen that the response from `application/rate_limit_status ` is a negative value for the reset variable when it fails:
```
[1] "rtlimit:"
# A tibble: 1 x 7
  query         limit remaining reset              reset_at            timestamp           app            
  <chr>         <int>     <int> <time>             <dttm>              <dttm>              <chr>          
1 search/tweets   180         0 -0.498060401280721 2018-06-12 12:00:54 2018-06-12 12:01:24 corpus_machismo
```

As a temporary solution I'm setting `reset <- 0` when it's a negative value but I have to check if it's working properly.

**Comment by mkearney** [comment]
yeah you've got to manage the global app rate *and* the search/tweets rate limits, which is 18,000 every fifteen minutes. The `retryonratelimit` argument can only do so much. Ideally, if you are going to write a for loop, then I'd set that value to FALSE and add the sleep functions manually.

You might also check out the `bearer_token()` option I've recently implemented. You get a higher rate limit for searching.

``` r
rt <- search_tweets("lang:en", n = 45000, token = bearer_token())
```
