### ISSUE TITLE
remove the readr dependency

### ISSUE THREAD

**Issue by ColinFay** [mkearney/rtweet#246]
When you try to install rtweet on a small RAM computer (let's imagine on an ubuntu with 1Gb of RAM ;) ) you have the following error on dependencies install, with {readr} : 

```
virtual memory exhausted: Cannot allocate memory /usr/lib/R/etc/Makeconf:143: recipe for target 'Collector.o' failed make: *** [Collector.o] Error 1 ERROR: compilation failed for package ‘readr’
```

This is due to the small size of the memory, and seems to be readr specific, as far as rtweet is concerned. 

I can see there is only read_lines and write_lines imported from readr, I was wondering if maybe this would make sense to have them replace by the base equivalent?

**Comment by ColinFay** [comment]
See https://github.com/tidyverse/readr/issues/544 for more info

**Comment by mkearney** [comment]
The problem is readr is performing a task (reading/parsing in especially large .json files) that's hard to replace. I suppose I could move readr to `suggests` and add a `requireNamespace()` check if readr is actually necessary (I imagine it's a rather rare use case anyway).

**Comment by ColinFay** [comment]
Oh, indeed if this is hard to replace it, no worry :) 
Just wanted to let you know that. 

I could'nt install rtweet either on my Rpi nor on a Digital Ocean VM, but I guess that's still indeed a rare use case, and that can be solved by manually compiling {readr}.

**Comment by mkearney** [comment]
Reduced some dependencies (removed glue, scales; moved readr to from imports to suggests), so if you give it another shot, you'll have to let me know if it works!
