### ISSUE TITLE
Missing hashtags in "hashtags" column for retweets when using get_timeline()

### ISSUE THREAD

**Issue by IWeavey** [mkearney/rtweet#247]
Hashtags are taken from the "text" column, but for retweets the text is often truncated (there is a retweet_text column so this information is not lost), but the result is the "hashtag" column in not accurate.

For, example consider the following tweet.
https://twitter.com/wearestillin/status/1002522496128741377

This was retweeted by @ClifBar and the text column is as such:
"RT @wearestillin: With the US government stepping back from the #ParisAgreement, Americans are rising to the challenge. Mayors, governors,…"

while the retweet_text column properly gives the initial tweet as such:
"With the US government stepping back from the #ParisAgreement, Americans are rising to the challenge. Mayors, governors, CEOs, tribes, and universities are committed to accelerating climate action in the USA. #WeAreStillIn #AmericasPledge https://t.co/MWjqTFSpu9 https://t.co/rcCDXkZde6"

There are 3 hashtags within the initial tweet (#ParisAgreement, #WeAreStillIn, #AmericasPledge), but the hashtag column only contains 1 (#ParisAgreement) because it is taking the hashtags from the "text"column.

This is just one example, but it applies to every case where we have a retweet.

It is not difficult to workaround this, but it is something people should be aware of (and something that should ultimately be fixed in the package one day)

**Comment by mkearney** [comment]
Great point! Thanks for making this an issue. Users can still recover all retweet hashtags by parsing `retweet_text` but retweet rows should be treated careful due to differences in counts, text, and hashtags!

``` r
## load rtweet
library(rtweet)

## load tidyverse
library(tidyverse)

## search tweets
rt <- search_tweets("lang:en", n = 300)

## wrangle and print to demonstrate issue
rt %>%
  mutate(l = lengths(hashtags),
    l = ifelse(l == 1 & is.na(hashtags), 0, l)) %>%
  filter(l > 0 & l < 6) %>%
  mutate(text = chr::chr_remove_links(text), 
    text = chr::chr_extract(text, "#[[:alpha:]][[:alnum:]]{0,}"),
    text = map_chr(text, ~ if (length(.x) == 1 && is.na(.x)) "" 
       else paste(.x, collapse = " ")),
    rtext = chr::chr_remove_links(retweet_text), 
    rtext = chr::chr_extract(rtext, "#[[:alpha:]][[:alnum:]]{0,}"),
    rtext = map_chr(rtext, ~ if (length(.x) == 1 && is.na(.x)) "" 
       else paste(.x, collapse = " "))) %>%
  arrange(is_retweet, -l) %>%
  select(is_retweet, text, hashtags, retweet_text = rtext) %>%
  slice(-c(1, 12:17, 21:26)) %>%
  print(n = 100)
#> # A tibble: 20 x 4
#>    is_retweet text                                 hashtags  retweet_text         
#>    <lgl>      <chr>                                <list>    <chr>                
#>  1 FALSE      #FREE #HPInstantInk #ad              <chr [3]> ""                   
#>  2 FALSE      #Boeing #aviation #united            <chr [3]> ""                   
#>  3 FALSE      #Albuquerque #NM                     <chr [2]> ""                   
#>  4 FALSE      #replacement #wood                   <chr [2]> ""                   
#>  5 FALSE      #Tetlltale #TheWalkingDead           <chr [2]> ""                   
#>  6 FALSE      #VegasBorn #tattoo                   <chr [2]> ""                   
#>  7 FALSE      #RankedChoiceVoting #BetterDemocracy <chr [2]> ""                   
#>  8 FALSE      #FY19NDAA                            <chr [1]> ""                   
#>  9 FALSE      #SONICBLOOM                          <chr [1]> ""                   
#> 10 FALSE      #CPSAppreciationWeek                 <chr [1]> ""                   
#> 11 TRUE       #DDay #Normandy                      <chr [2]> #DDay #Normandy      
#> 12 TRUE       #CMTawards #VOTEBLAKE                <chr [2]> #CMTawards #VOTEBLAKE
#> 13 TRUE       #OTRII #Cardiff                      <chr [2]> #OTRII #Cardiff      
#> 14 TRUE       #CandaceForCongress                  <chr [1]> #CandaceForCongress  
#> 15 TRUE       #IPICKNINIOLA18                      <chr [1]> #IPICKNINIOLA18      
#> 16 TRUE       #DDay                                <chr [1]> #DDay                
#> 17 TRUE       #SIFYSmileAgain                      <chr [1]> #SIFYSmileAgain      
#> 18 TRUE       #Pride2018                           <chr [1]> #Pride2018 #Pride2018
#> 19 TRUE       #HOOKEDTONIGHT                       <chr [1]> #HOOKEDTONIGHT       
#> 20 TRUE       #IntelRigChallenge                   <chr [1]> #IntelRigChallenge   
```

As you can see from the output above, when `is_retweet` is `FALSE` the number of parsed retweets in `text` exactly equal to the number of hashtags observed in `hashtags`. But when `is_retweet` is `TRUE`, the number of parsed hashtags in `retweet_text` is not always equal to the number of hashtags observed in `hashtags` (presumably because `text` is truncated for retweets).



Also, I apologize for the code above. It's probably not super translatable to other machines, but I figured I'd include it because it can be tweaked to accomplish similar effect.

**Comment by mkearney** [comment]
retweet rows should be given special attention regardless of whether they have hashtags (i.e., favorite counts carry over, etc), so I'm closing this specific issue.
