### ISSUE TITLE
Authorization issues when scheduling stream_tweets()...

### ISSUE THREAD

**Issue by herrmannrobert** [mkearney/rtweet#248]
Sorry for fetching the authorization issue again - but I reached my limit...

What I simply try to do is that R automatically starts streaming twitter after my windows system booted (taskscheduleR package). It works perfekt when I reboot the system and then manually run the code, however, the scheduled task would create one file.json after another (without any content) - most likely due to authentication issues.

I tried saving the token and everything as described by e.g. rtweet.info - without any success at all. I bet it's very simple and has to do with saving and loading the AccessToken. 

Here is how I deal with the access token:

```
library(rtweet)

if(T){appname <- "herr[...]mann"
      key <- "SzA[...]1o7u"
      secret <- "4MtSJom[...]WjdgRUuz"
      twitter_token <- create_token(app = appname, consumer_key = key, consumer_secret = secret)}

home_directory <- path.expand("~/")
file_name <- file.path(home_directory, "twitter_token.rds")
saveRDS(twitter_token, file = file_name)

cat(paste0("TWITTER_PAT=", file_name),
    file = file.path(home_directory, ".Renviron"),
    append = TRUE)
```

This code is executed by the TaskScheduler:

```
library(rtweet)
Sys.setenv(TZ = "UTC")

files   <- list.files("C:/Users/DataMine/.../DataBase", pattern = ".rds")
cc      <- strsplit(files, '[.]')
symbols <- unlist(cc)[2*(1:length(files))-1]

setwd("D:/Twitter")
cashtags <- paste("$", symbols, sep = "")
query    <- paste(cashtags, collapse = ",")
fn       <- paste(format(Sys.time(), "%Y%m%d_%H%M%S"), "json", sep = ".")

stream_tweets2(q = query, timeout = 60*60, file_name = fn)
```

Thanks for any hint...

EDIT: See below for more reproducible example...

**Comment by herrmannrobert** [comment]
Did some testing on saving and loading the access token again. Following worked fine for me when manually running the code after re-booting windows - but not when scheduling the task with taskscheduleR package (stops immediately after it starts running):

```
#Before re-booting
library("rtweet")
appname <- "herr[...]mann"
key <- "SzA[...]1o7u"
secret <- "4MtSJom[...]WjdgRUuz"
twitter_token <- create_token(app = appname, consumer_key = key, consumer_secret = secret)

saveRDS(twitter_token, "twitter_token.rds")
```

Then manually running (or scheduling) after re-booting windows and R:

```
#After re-booting
library("rtweet")
twitter_token <- readRDS("twitter_token.rds")
test <- stream_tweets(q = "election", file_name = "...", timeout = 60)
```

Seems to be related to scheduling the task rather than an access-token-issue itself. Maybe @jwijffels can help somehow...

Thanks again...

**Comment by jwijffels** [comment]
Looks to me you need to use full paths to your RDS read/write operationele

**Comment by herrmannrobert** [comment]
Nope - unfortunately not. I saved and wrote the RDS including full path. Is that what you meant...?

```
saveRDS(twitter_token, file = "C:/Users/DataMine/Documents/R/twitter_token.rdf")
twitter_token <- readRDS("C:/Users/DataMine/Documents/R/twitter_token.rds")
```

**Comment by herrmannrobert** [comment]
Meanwhile the riddle could be solved. You need to pass the access-token manually to the `token` argument, like here:

```
twitter_token <- readRDS("C:/Users/DataMine/Documents/R/twitter_token.rds")
stream_tweets(q = "ellection", token = twitter_token)
```
For me, that was the only way to get this thing on schedule...

Thanks anyway...
