### ISSUE TITLE
search_users() gives: Error in attr(d, "tweets") <- x[["tweets"]]

### ISSUE THREAD

**Issue by rdatasculptor** [mkearney/rtweet#25]
when running this code:

`search_users("Ybeltje Berckmoes-Duindam",n=2)`

It gives this error:

```
Error in attr(d, "tweets") <- x[["tweets"]] : 
  attempt to set an attribute on NULL
```

Any ideas about what causes this error?

Kind regards,
Jelle

**Comment by mkearney** [comment]
@rdatasculptor that error has now been fixed. However, the search yields 0 results, so the function should now return an empty data frame.

I was able to return 2 users by searching just the first name:

```{r}
search_users("Ybeltje, n = 2)
```

**Comment by rdatasculptor** [comment]
It works. Thanks!
