### ISSUE TITLE
dataframe with 0 columns and 0 rows

### ISSUE THREAD

**Issue by pvincentruz** [mkearney/rtweet#250]
### Problem

I have this user: "DrCJSobers"
and if you see in twitter the account is public and all looks good but when I try to get info so i convert to id number

user <- lookup_users("DrCJSobers")
user_s <- user$user_id

and try to use the get followers function
get_followers(user_s, n = 20000, page = "-1")

### Expected behavior
No list obtained

### Reproduce the problem
What I get is: data frame with 0 columns and 0 rows

``` r
## insert code here

```

### rtweet version
downloaded from github

``` r
## copy/paste output
packageVersion("rtweet")
```

### Session info

``` r
## copy/paste output
sessionInfo()
```

### Token

``` r
## copy/paste output
rtweet::get_token()
```

**Comment by mkearney** [comment]
You probably just need a new version of rtweet:

``` r
devtools::install_github("mkearney/rtweet")
```

The code worked for me:

``` r
> user_s <- user$user_id
> flw <- get_followers(user_s, n = 20000, page = "-1")
> flw
# A tibble: 194 x 1
   user_id           
   <chr>             
 1 887435936090525696
 2 278249128         
 3 3100863671        
 4 105644803         
 5 2704715387        
 6 2695727239        
 7 456617304         
 8 498428017         
 9 2724556301        
10 2508834390        
# ... with 184 more rows
```

Also, side note, you can actually supply the screen name directoy to the `get_followers()` function, e.g.

``` r
> flw <- get_followers("DrCJSobers")
> flw
# A tibble: 194 x 1
   user_id           
   <chr>             
 1 887435936090525696
 2 278249128         
 3 3100863671        
 4 105644803         
 5 2704715387        
 6 2695727239        
 7 456617304         
 8 498428017         
 9 2724556301        
10 2508834390        
# ... with 184 more rows
```

**Comment by pvincentruz** [comment]
thanks!
