### ISSUE TITLE
issue with encoding

### ISSUE THREAD

**Issue by fnagano** [mkearney/rtweet#26]
when using search_tweets() function to extract tweets in portuguese (lang ="pt-br"), it drops characters like ç, ã, Á. ("vdeo" instead of "vídeo")

**Comment by mkearney** [comment]
Thank you for opening the issue. I'll look into it. To clarify: Are the characters dropped in your query or are they being dropped in the text of tweets?

**Comment by fnagano** [comment]
In the text of tweets. Thanks!

**Comment by mkearney** [comment]
This should be fixed at least for now. Something isn't quite right with what Twitter says to expect about encoding and what it returns, so I'm not convinced my solution is perfect. I'll keep looking into it, but if you have any more difficulties let me know. Also, in the short term, at least, you can set parse = FALSE within a function and that should return a more complete version of the text.

**Comment by neuwirthe** [comment]
get_timeline now also gives tweets containing umlauts. Thanks.
