### ISSUE TITLE
Post tweet doesn't actually post

### ISSUE THREAD

**Issue by JacobCoblentz** [mkearney/rtweet#27]
When I use post_tweet, the tweet doesn't actually show up on my twitter account- what's going on?

**Comment by JacobCoblentz** [comment]
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rtweet_0.2.9

loaded via a namespace (and not attached):
[1] httr_1.2.1        R6_2.1.3          tools_3.3.1       curl_2.0          jsonlite_1.1.9000 openssl_0.9.4

**Comment by mkearney** [comment]
It likely has something to do with your token. Can you make sure you've authorized "write" access for your token on https://apps.tokens.com? And how are you calling your token? If you setup the environment variable correctly, then it should work, but if you haven't done that, then you'd need to make sure to specify the token argument so it points to the correct token object.
