### ISSUE TITLE
creating lists

### ISSUE THREAD

**Issue by neuwirthe** [mkearney/rtweet#276]
This is not a problem, but a suggestion you might consider.
Can you add a function which allows to create a list from a vector of names?

**Comment by Arf9999** [comment]
Doesn't base R already have this as a function?
`as.list()`
[(https://stat.ethz.ch/R-manual/R-devel/library/base/html/list.html)]

**Comment by neuwirthe** [comment]
Sorry for not being precise enough. I meant Twitter list = groups of usernames which one can read in a separate timeline containing _only_ posts from these people.

**Comment by mkearney** [comment]
yes @Arf9999 is right! And I just recently fixed an issue when adding users to it. Just beware the API is a bit picky when you remove and add several users!
