### ISSUE TITLE
Get_timeline() doesn't pull older tweets than 3200 tweets cap

### ISSUE THREAD

**Issue by marvinmilatz** [mkearney/rtweet#278]
Hey! I ran into a problem and hope you can help me out. 

### Problem

Get_timeline() works great, when pulling the first batch of 3200 tweets from an account's timeline, however, when using max_id for receiving tweets from further back, it doesn't work. Is 3200 tweets the maximum that is possible to receive for an account? No matter what?

### Expected behavior

According to Twitter's documentation it should be possible to traverse back the timeline with the max_id command. I can't see why 3200 tweets should be the limit. https://developer.twitter.com/en/docs/tweets/timelines/guides/working-with-timelines

### Reproduce the problem

The following code does not produce any tweets. As I understand the function, it should return up to 3200 tweets older than the max_id posted.

``` r
tweets <- get_timeline(user = "realDonaldTrump",
                       n = 3200, 
                     max_id = "877234140483121152",
                     home = FALSE)

```

### rtweet version

``` r
‘0.6.0’
```

### Session info

``` r
## copy/paste output
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

```

### Token

``` r
<Token>
<oauth_endpoint>
 request:   https://api.twitter.com/oauth/request_token
 authorize: https://api.twitter.com/oauth/authenticate
 access:    https://api.twitter.com/oauth/access_token
<oauth_app> twi
  key:    kK4
  secret: <hidden>
<credentials> oauth_token, oauth_token_secret, user_id, screen_name
```

Many thanks for looking into this!

Marvin

**Comment by mkearney** [comment]
@marvinmilatz I wish you were right, but I'm afraid the 3200 limit isn't relative to `max_id` but is hardwired in to Twitter's REST API.

**Comment by alexpghayes** [comment]
Can I request that the documentation be updated to reflect this?

**Comment by llrs** [comment]
@alexpghayes The devel documentation now says: " This number should not exceed 3200 as Twitter limits returns to the most recent 3,200  statuses posted or retweeted by each user." Academic track API is being tracked on #468 and v2 API is on #445
