### ISSUE TITLE
Can you get back more than 3200 tweets with get_timeline?

### ISSUE THREAD

**Issue by mablan** [mkearney/rtweet#286]
### Problem

This is probably not a bug. Is it possible to get beyond 3200 tweets in get_timeline by specifying a max_id properly? What is the Twitter API limit for timelines? I do not seem to get beyond 3000 and so tweets, even after trying to sample on different days.

### Expected behavior
A data frame with 3200 tweets older than max_id 

If I can get the expected behavior, I can concatenate new and old results and get back the whole history of tweets for the period of time that I am interested in. 

### rtweet version
> packageVersion("rtweet")
[1] ‘0.6.7’

``` r
## copy/paste output
sessionInfo()
```

### Token

``` r
## copy/paste output
rtweet::get_token()
```

**Comment by zacharskim** [comment]
Hi mablan, I have the same question. Did you ever figure out if/how it is possible to get more than 3200 tweets using the max_id argument and making multiple calls?
