### ISSUE TITLE
question on open data of tweets

### ISSUE THREAD

**Issue by jwijffels** [mkearney/rtweet#291]
Hi @mkearney 
My apologies if this is not the right place for asking this question.
I'm developing an R wrapper around Starspace here: https://github.com/bnosac/ruimtehol
In order to build an example of a classification model, I was thinking on doing it on tweets in order to categorise the hashtag of a tweet.
Do you happen to have a .RData file containing tweets available which can be used to incorporate in that package or do you - par hasard - know of a place where I can find such data?

**Comment by jwijffels** [comment]
Thanks for the feedback. Wasn't aware of the Twitter TOS. That will be a blocking factor.
I was basically looking for a ready-made dataset containing tweets such that I don't need to let the R package depend on another package. I'll look to another example then.
Thank you for your input either way!

**Comment by mkearney** [comment]
Perhaps anonymize the data? Or maybe tweets from public figures–e.g., predicting whether Trump tweet was sent from iPhone, Android, and/or other; predict partisanship of the account tweeter; etc.?
