### ISSUE TITLE
`post_message` Not Working

### ISSUE THREAD

**Issue by Tom-Wolff** [mkearney/rtweet#293]
I'm trying to send a direct message using the following code:
`rtweet::post_message(text = "Testing, 1, 2.", user = "T_mWolff")` 

I'm getting the following error message when running it, however. This message appears even when I change the recipient screenname in the `user` argument:
`$errors`
`$errors[[1]]`
`$errors[[1]]$code`
`[1] 34`

`$errors[[1]]$message`
`[1] "Sorry, that page does not exist."`

Any advice on how to remedy this issue would be greatly appreciated!

**Comment by mkearney** [comment]
This is probably related to your token's access level. You can check the access level associated with your token like so:

``` r
> rtweet:::get_access_level(rtweet::get_token())
[1] "read-write-directmessages"
```

If you created your own app, then go to https://developer.twitter.com/, click on your profile name on the top right and then click on your app in the subsequent dropdown. Navigate to permissions and enable read-write-directmessages

If you used the rtweet client to create an app, then you're out of luck as those are now read-only. You'll have to apply for a developer account (same link as above: https://developer.twitter.com). When/if they approve your use, then you can create an app and specify the appropriate permissions.

**Comment by Tom-Wolff** [comment]
I just changed my access token's privileges to include direct messages. The `get_access_level` call shows me what you've posted above now, but I'm still getting the same error when I try and send a DM. Thoughts?

**Comment by mkearney** [comment]
You'll have to regenerate your token (should be clickable button at https://developer.twitter.com) and then create a new token using the regen'd token credentials

**Comment by mkearney** [comment]
it may be broken independently. i'll look into it. twitter has made a number of changes related to write access and DMs recently.

**Comment by Tom-Wolff** [comment]
I forgot to mention that I regenerated my token before I posted the last comment. Please let me know if this is more of an issue on Twitter's end if you find that's the case!

**Comment by Tom-Wolff** [comment]
No worries! I just reinstalled rtweet off GitHub and gave `post_message` another try. Now I'm getting the following message:

`Error in lookup_user(user) : could not find function "lookup_user"`

Any thoughts on what's happening here?

**Comment by mkearney** [comment]
typo 😇. but, **this time**, i think we've got it!

**Comment by Tom-Wolff** [comment]
We're golden! Thanks for your help (and for rtweet more generally)!

**Comment by 7670367** [comment]
I'm not sure if this is a similar problem. When I try to use `post_message` i get this error:
~~~
> post_message("test 2 from R", "jayteeemdee")
$request
[1] "/1.1/direct_messages/events/new.json"
$error
[1] "Read-only application cannot POST."
~~~
I think the problem is that I only have "read" access:
~~~
> packageVersion("rtweet")
[1] ‘0.6.9’
> rtweet:::get_access_level(rtweet::get_token())
[1] "read"
~~~
But on my Twitter dev page, it says I've authorized `Read, write, and Direct Messages`
~~~
Consumer API keys
xxx (API key)
xxx (API secret key)

Access token & access token secret
xxx (Access token)NEW
xxx (Access token secret)NEW
Read, write, and Direct Messages (Access level)
~~~
Thanks.
