### ISSUE TITLE
umlauts in tweets

### ISSUE THREAD

**Issue by neuwirthe** [mkearney/rtweet#30]
When creating wordclouds from timelines I noticed that  the text component  of get_timeline suppresses all umlauts, and possibly also other characters from Western nonEnglisch languages. Could you modify the parser to keep those letters?

**Comment by mkearney** [comment]
Done. Non-ascii characters can create errors in some instances, so I've streamlined a `clean_tweets` argument (defaults to FALSE, which is what you would want) for anyone looking to avoid those characters altogether.

Thanks for letting me know. I do appreciate it!

**Comment by neuwirthe** [comment]
Thanks, it works
