### ISSUE TITLE
Searching tweets having a specific keyword between two given dates

### ISSUE THREAD

**Issue by rish19** [mkearney/rtweet#306]
### Problem

Since twitteR doesn't provides extended tweets, I moved to the rtweet package.

in twitteR,

obj.tweets = searchTwitter(searchString,lang='en', num, resultType='recent', since = "start date", until = "end date")

This would provide me with tweets between the start date and end date.

But when I try

rt <- search_tweets(
  searchString , n=100, retryonratelimit = FALSE, include_rts = FALSE, since = "2019-01-25", until = "2019-01-26")
)

or 

rt <- search_tweets(
  searchString , n=100, retryonratelimit = TRUE, include_rts = FALSE, since = "2019-01-25", until = "2019-01-26")
)

I don't get anything in rt. 

I know there's a limitation in free APIs that allows searching tweets within a span of 7 days. But I couldn't search anything within a time frame of 7 days too.

**Comment by mkearney** [comment]
This works for me (though it exposes another bug I wasn't aware of–the number of returned tweets is too high when setting `retryonratelimit = TRUE`...thought that's never really necessary when only searching for 100 tweets):


``` r
> rt <- search_tweets(
+   "rstats", 
+   n = 100, 
+   retryonratelimit = TRUE, 
+   include_rts = FALSE, 
+   since = "2019-01-25", 
+   until = "2019-01-26"
+ )
Downloading [>----------------------------------------]   3%
> range(rt$created_at)
[1] "2019-01-25 00:00:20 UTC" "2019-01-25 23:51:05 UTC"
> nrow(rt)
[1] 426
```

**Comment by rish19** [comment]
Yes, it's working!
Thanks for helping!
Strange but the same piece of code that I mentioned above works well now!

**Comment by mkearney** [comment]
@rish19 Twitter's API can be a bit buggy, so I have no doubt that could have experienced something different!
