### ISSUE TITLE
Unable to find older tweets. 

### ISSUE THREAD

**Issue by jtsayagog** [mkearney/rtweet#307]
I have been trying to get data on older tweets however I can´t find anything. I tried using search_tweets here and get: 

> q <- "@SeguridadCali"
> n <- 10000
> since2 <- "2017-01-01"
> rt2 <- search_tweets( q = q, n = n,  since = since2)
Searching for tweets...
This may take a few seconds...
Finished collecting tweets!
> summary(rt2$created_at)
                 Min.               1st Qu.                Median 
"2019-01-17 21:18:55" "2019-01-22 01:50:58" "2019-01-24 21:29:01" 
                 Mean               3rd Qu.                  Max. 
"2019-01-23 19:28:21" "2019-01-25 18:08:00" "2019-01-27 22:18:33" 

Also tried with the get_timeline function and got

> archivo2 <- get_timeline( account, n =3200, parse = TRUE, since = "2017-01-01")
> summary(archivo2$created_at)
                 Min.               1st Qu.                Median 
"2018-05-23 02:44:32" "2018-08-14 07:34:30" "2018-10-06 23:40:41" 
                 Mean               3rd Qu.                  Max. 
"2018-09-30 17:34:29" "2018-11-28 14:30:33" "2019-01-27 18:35:55" 

Is there a way to access older data? 
Thanks
Juan

> packageVersion("rtweet")
[1] ‘0.6.8.9000’

> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.14.2

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rtweet_0.6.8.9000

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0        magrittr_1.5      R6_2.3.0          rlang_0.3.1      
 [5] fansi_0.4.0       httr_1.4.0        tools_3.5.1       pkgbuild_1.0.2   
 [9] utf8_1.1.4        cli_1.0.1         withr_2.1.2       askpass_1.1      
[13] remotes_2.0.2     openssl_1.2.1     assertthat_0.2.0  rprojroot_1.3-2  
[17] tibble_2.0.1      crayon_1.3.4      processx_3.2.1    callr_3.1.1      
[21] later_0.7.5       promises_1.0.1    ps_1.3.0          curl_3.3         
[25] pillar_1.3.1      compiler_3.5.1    backports_1.1.3   prettyunits_1.0.2
[29] jsonlite_1.6      httpuv_1.4.5.1    pkgconfig_2.0.2  

> rtweet::get_token()
<Token>
<oauth_endpoint>
 request:   https://api.twitter.com/oauth/request_token
 authorize: https://api.twitter.com/oauth/authenticate
 access:    https://api.twitter.com/oauth/access_token
<oauth_app> App_search_crime_cali
  key:    StpJdNU7RlufutkXfJ7ej9IzG
  secret: <hidden>
<credentials> oauth_token, oauth_token_secret, user_id, screen_name
---
>

**Comment by mrmvergeer** [comment]
the search api only returns tweets up to a couple of days back in time. The REST api for the timeline tweets only returns the latest 3200 tweets of a specific user. No fault of the package but a Twitter imposed limitation. The only way to get them is buy them from a data seller such as Crimson Hexagon, but that is hugely expensive.

**Comment by jtsayagog** [comment]
I am trying to check the difference between the sandbox 30 days and the full archive, which is supposed to allow the download of tweets since 2006, however I need to check the changes necessary to make in the make_url in search_tweets
As it says on this link: https://developer.twitter.com/en/docs/tweets/search/overview/premium 
However still trying...

**Comment by tuggawaugh** [comment]
@jtsayagog were you able to find a solution to it? They have premium sandbox for 30 days and I am trying to figure out how to get tweets 30 days prior.

**Comment by jtsayagog** [comment]
@tuggawaugh The author of the package created a function that will solve it. it is called search_fullarchive you need to get the premium sandbox but it works perfectly. 
J

**Comment by ikashnitsky** [comment]
While I'm exploring similar issues, here is a project that is focused to resolve these exact issues via the new Academic API. 
https://github.com/cjbarrie/academictwitteR
