### ISSUE TITLE
lookup_users issue

### ISSUE THREAD

**Issue by neuwirthe** [mkearney/rtweet#31]
`lookup_users("neuwirthe")` 

does not give the full information, there are lots of NAs.

`lookup_users("neuwirthe","ArminWolf")`

works, but

`lookup_users("neuwirthe","neuwirthe")`

also does not give the full information. So it seems that lookup_users needs to be given at least two different user names to return correct results.

**Comment by mkearney** [comment]
Good catch!

The parser filters out non-unique rows, so the problem occurred when NROW = 1. That should now be fixed!
