### ISSUE TITLE
lookup_statuses get 400 malformed error

### ISSUE THREAD

**Issue by peeyooshc** [mkearney/rtweet#35]
running this demo script does not return a dataframe 

statuses <- c("potus", "hillaryclinton", "realdonaldtrump",
  "fivethirtyeight", "cnn", "espn", "twitter")

twt_df <- lookup_statuses(statuses)
twt_df

Went looking at the internals and it seems to think that TWIT is making a call but nothing is being returned. What could be happening?

I tried the same query in https://apigee.com/console/twitter and it also get a 200 OK response but no data.

**Comment by mkearney** [comment]
Oh this was a silly mistake on my part. That function expects a `status_id` (tweet ids) vector. To lookup those users, it should use the `lookup_users()` function.

```{r}
> users <- c("potus", "hillaryclinton", "realdonaldtrump",
  "fivethirtyeight", "cnn", "espn", "twitter")
> twt_df <- lookup_users(users)
> twt_df
     user_id            name     screen_name          location
1 1536791610 President Obama           POTUS  Washington, D.C.
2 1339835893 Hillary Clinton  HillaryClinton      New York, NY
3   25073877 Donald J. Trump realDonaldTrump      New York, NY
4 2303751216 FiveThirtyEight FiveThirtyEight      New York, NY
5     759251             CNN             CNN              <NA>
6    2557521            ESPN            espn       Bristol, CT
7     783214         Twitter         twitter San Francisco, CA
...
```

**Comment by mkearney** [comment]
Thanks for pointing this out! I've updated the documentation (incoming commit), so I'll close this issue. The example provided for lookup_statuses should now look something like this:

```{r}
> statuses <- c("567053242429734913", "266031293945503744", 
+   "440322224407314432")
> statuses <- lookup_statuses(statuses)
> statuses
           created_at    status_id
1 2015-02-15 20:10:02 5.670532e+17
2 2012-11-07 04:16:18 2.660313e+17
3 2014-03-03 03:06:13 4.403222e+17
                                                                                                                                      text
1 For every retweet this gets, Pedigree will donate one bowl of dog food to dogs in need! \U0001f60a #tweetforbowls http://t.co/z4rmc2HsGT
2                                                                                                    Four more years. http://t.co/bAJE6Vom
3                                                        If only Bradley's arm was longer. Best photo ever. #oscars http://t.co/C9U5NOtGap
               source in_reply_to_status_id in_reply_to_user_id in_reply_to_screen_name is_quote_status retweet_count favorite_count lang
1             Twuffer                    NA                  NA                      NA           FALSE        684247         135915   en
2  Twitter Web Client                    NA                  NA                      NA           FALSE        837868         466187   en
3 Twitter for Android                    NA                  NA                      NA           FALSE       3304788        2291832   en
   user_id  screen_name quoted_status_id mentions_user_id mentions_screen_name      hashtags urls is_retweet retweet_status_id place_name
1 14465607    AHMalcolm               NA               NA                   NA tweetforbowls   NA      FALSE                NA       <NA>
2   813286  BarackObama               NA               NA                   NA            NA   NA      FALSE                NA       <NA>
3 15846407 TheEllenShow               NA               NA                   NA        oscars   NA      FALSE                NA       <NA>
```

**Comment by peeyooshc** [comment]
Thanks Michael,

I apologise I wasn't clear in my request. I want to get the latest tweet
from each of these users in the status vector.

Do I have to cycle through each user's timeline?

**Comment by mkearney** [comment]
@peeyooshc Once you run the `lookup_users()` function, use the `tweets_data` function to see the most recent tweet for each user.
```{r}
> users <- c("potus", "hillaryclinton", "realdonaldtrump",
  "fivethirtyeight", "cnn", "espn", "twitter")
> usr_df <- lookup_users(users)
> tweets_data(usr_df)
```
Alternatively, yes, you can also cycle through each user's timeline. The benefit to this approach, is that you can easily get a lot more than the most recent (single) tweet. In a lot of cases, you can get around 3,000 tweets for each user.

```{r}
> users <- c("potus", "hillaryclinton", "realdonaldtrump",
  "fivethirtyeight", "cnn", "espn", "twitter")
> twt_df <- lapply(users, get_timeline, n = 100)
> twt_df <- do.call("rbind", twt_df)
> head(twt_df)
```

**Comment by peeyooshc** [comment]
Sorry Michael,

 I think I'm being thick. I've run through the script and it works fine.
When I then call tweets_data, the tweets are returned with statusID, but
not with user_id or screen_name.

 Am I doing something wrong, I looked at extractors.R but couldn't see why
screen_name wouldn't be populated.

 - PC

**Comment by mkearney** [comment]
You should find user_id and screen_name, but they might be columns 11-13ish. The ourput I posted above from the lookup_tweets function includes the same data organization that you should be seeing. Perhaps some columns were cut off by the print method?

**Comment by mkearney** [comment]
Okay, ran some tests. You're totally right! I'm looking into it!

**Comment by peeyooshc** [comment]
Thanks !
