### ISSUE TITLE
"Rate limit exceeded" tripped by checking rate_limit too often?

### ISSUE THREAD

**Issue by ssyvert** [mkearney/rtweet#38]
I'm trying to gather tweets iteratively based on a user list, and I'm being stopped by an error that didn't make much sense to me at first. It seems that the built in rate-limiting is what's causing the trouble, even though I'm doing a query that should allow for 900 queries in 15 minutes.

Here's some test code that prints to console:

```
# arbitrary list of popular twitter accounts
users = c("katyperry", "justinbieber", "taylorswift13", "BarackObama", "rihanna", "YouTube", "ladygaga", "TheEllenShow", "twitter", "jtimberlake", "KimKardashian", "britneyspears", "Cristiano", "selenagomez", "cnnbrk", "jimmyfallon", "ArianaGrande", "shakira", "instagram", "ddlovato", "JLo", "Oprah", "Drake", "KingJames", "BillGates", "nytimes", "KevinHart4real", "onedirection", "MileyCyrus", "SportsCenter")

for (i in users) {
  get_timeline(i, token=my_token, n = 100, clean_tweets = T, verbose = T)
  curr_limit = rate_limit(token=my_token)
  print(paste0("searched for ",i,", and there were ",curr_limit$remaining[curr_limit$query == "statuses/user_timeline"]," user API calls, ",curr_limit$remaining[curr_limit$query == "application/rate_status"]," status API calls left."))
}
```

And here's what's in the console - you'll notice that the remaining calls for the rate limiting info itself is what terminates the loop:

```
[1] "searched for katyperry, and there were 862 user API calls, 67 status API calls left."
[1] "searched for justinbieber, and there were 861 user API calls, 64 status API calls left."

(much of the same, until...)

[1] "searched for Oprah, and there were 841 user API calls, 4 status API calls left."
[1] "searched for Drake, and there were 840 user API calls, 1 status API calls left."
Error: rate limit exceeded.

```

I realise I'm inflating the rate at which the status API call limit decreases by calling it for the console output, but even so, since it starts at 180 it could never accommodate running through a 900 limit one all the way through. 

A flag disabling the check or making it less frequent could work, perhaps?

**Comment by mkearney** [comment]
Thanks for this. I've been going through the entire package to reduce redundancies or otherwise unnecessary API rate limit checks.

Typically that information is included in the response object, so maybe I should add the rate limit info as an attribute in the returned df? That would allow you to print iteration messages without sacrificing API calls or time.

Assuming it's not too difficult to incorporate, I'll include this in the next CRAN update (so in the next week or two).

**Comment by ssyvert** [comment]
Hey, sorry for the late reply, I had a long break from the project where I bumped into this. Picked it up again and it seems to be working a bit better now, thanks!
