### ISSUE TITLE
get_timeline -> changing the output a bit?

### ISSUE THREAD

**Issue by masalmon** [mkearney/rtweet#4]
I'm currently using `get_timeline` and I've noticed it returns two data.frames now. For a package of mine (monkeylearn) I'd been advised to rather have only one data.frame as output with the other data.frame as attributes to the first one, so maybe in your case `users` could be an attribute of `tweets` so that it might be easier to deal with `get_timeline` output? It's just a suggestion of course, I find the function great already!

Moreover when retrieving 2000 tweets from realDonaldTrump the `users` data.frame contains 4 times the same line, should you add an `unique`-call somewhere?

**Comment by mkearney** [comment]
```
I'm currently using get_timeline and I've noticed it returns two data.frames now. For a package of mine (monkeylearn) I'd been advised to rather have only one data.frame as output with the other data.frame as attributes to the first one, so maybe in your case users could be an attribute of tweets so that it might be easier to deal with get_timeline output? It's just a suggestion of course, I find the function great already!
```
You wouldn't have any handy resources on this would you? I remember reading about ref classes and attributes in Hadley's book, but if you have any other recommendations I'll take them.

```
Moreover when retrieving 2000 tweets from realDonaldTrump the users data.frame contains 4 times the same line, should you add an unique-call somewhere?
```
This should now be fixed.

**Comment by masalmon** [comment]
Sorry about the lack of details. I too learnt about attributes very recently. You'd just need to write `attr(tweets, "users") <- users`,  because the data.frame can have any number of attributes without defining a class. ☺

**Comment by masalmon** [comment]
https://github.com/ropensci/onboarding/issues/45 this is where I was told about attributes.

**Comment by mkearney** [comment]
@masalmon should be integrated now for search_tweets, get_timeline, and stream_tweets (next step will be to integrate with lookup_users). I also added users_data() and tweets_data() functions as shortcuts for attri(x, "users/tweets"). It's about the same amount of code, but it's easier for me at least to remember those over the attr call.

**Comment by mkearney** [comment]
If you try them out any time soon, let me know how it goes :)

**Comment by masalmon** [comment]
Cool, thank you!

When I write `djt <- get_timeline("realDonaldTrump", n = 20)`

then the results data.frame has 19 empty lines, see picture below. Do you get this too?

![rtweet](https://cloud.githubusercontent.com/assets/8360597/17729624/5d53304a-6465-11e6-945e-a2a1fbaf8ef1.png)

**Comment by mkearney** [comment]
Good call. There should only be 1 row there. I thought I fixed this, but it seems I overlooked something. Either way, I need to make sure my tests catch this as well.

**Comment by masalmon** [comment]
And then you could add continuous integration, see e.g. http://juliasilge.com/blog/Beginners-Guide-to-Travis/ :-)

**Comment by mkearney** [comment]
Oh perfect! The section on Travis in Hadley's book seemed to assume people had a little more familiarity with it than I, so that gentle intro looks perfect! If it's not completely obvious, programming is a recent development for me. My background, and reason I started learning to code at all, is in statistics, so the help, as always, is very appreciated!

**Comment by masalmon** [comment]
I'll tag @juliasilge so she can see the praise. :smile_cat: 

And no it's not "completely obvious", you're doing great!

**Comment by good-marketing** [comment]
Hi, I tried to use the timeline function and got the following error. I also tried not parsing the results but it gave me the same error.

Thanks for your help!

 ```
djt <- get_timeline("realDonaldTrump", n = 20)

Error in as.POSIXct.default(rl_df$reset, origin = "1970-01-01") : 
  do not know how to convert 'rl_df$reset' to class “POSIXct”

 ```

**Comment by mkearney** [comment]
Are you using the Github or CRAN version of rtweet? Can you supply your sessionInfo() as well?

**Comment by mkearney** [comment]
I'm having trouble replicating the error, but think I may have fixed it (at least, in the Github version). Let me know if you continue to have problems!

**Comment by good-marketing** [comment]
I tried the method in a different session and project and the error went away. So it's due to something in my R environment. I'lll dig some more but you can close the issue. Thanks for your response.
