### ISSUE TITLE
Provide standard twitter app as default

### ISSUE THREAD

**Issue by hadley** [mkearney/rtweet#40]
So every user doesn't have to create their own app.

**Comment by mkearney** [comment]
This exists but documentation has lagged. I've also been meaning to auto-populate the app name (if not provided by user) arg within the create token function, which this is a good reminder for as well.

**Comment by hadley** [comment]
No be clear, there is no need for the user to provide their own app. You can create an app and store the app key/secret in the package.

**Comment by mkearney** [comment]
It only took me about a year to figure this out!

**Comment by hadley** [comment]
Awesome! You can update the readme now 😉
