### ISSUE TITLE
stream_tweets(): bounded bx geocoords not working?

### ISSUE THREAD

**Issue by itsnickyjones** [mkearney/rtweet#42]
Ahoy,

I have attempted to stream tweets from a geographic area, but when I run the script I believe I'm just getting a random sample of tweets (as if I left the script with q = "").

**Here is what I ran:** 
area <- stream_tweets(q = "-94,36,-93,37", timeout = 30, parse = TRUE, clean_tweets = TRUE, token = twitter_token, verbose = TRUE)

Did I structure this correctly? Many thanks!

**Comment by mkearney** [comment]
Turns out you were doing it perfectly! I had a typo in the stream query logic (it should be `locations` not `location`).

It should now be fixed.

I just ran the code below and it worked great:

```{r}
> library(rtweet)
Welcome to rtweet v0.3.7!
> rt <- stream_tweets(
+   q = c(-94, 36, -93, 37), timeout = 30, clean_tweets = TRUE)
Streaming tweets for 30 seconds...
Downloading: 18 kB      
Finished streaming tweets!
opening file input connection.
 Imported 13 records. Simplifying...
closing file input connection.
```

Selected output looks beautiful too (so few accounts opt-in to geo-located tweets, I'm not accustomed to seeing these columns appear as anything but blocks of `NA`s)!

```{r}
> rt
            created_at          status_id
1  2016-12-06 19:34:20 806220245656539136
2  2016-12-06 19:34:21 806220249859321856
3  2016-12-06 19:34:26 806220274031095808
4  2016-12-06 19:34:32 806220299217883136
5  2016-12-06 19:34:33 806220303487696896
6  2016-12-06 19:34:37 806220319111397385
7  2016-12-06 19:34:39 806220325402779648
8  2016-12-06 19:34:40 806220330121498628
9  2016-12-06 19:34:41 806220334890385409
10 2016-12-06 19:34:41 806220336299737088
11 2016-12-06 19:34:43 806220342771515393
12 2016-12-06 19:34:44 806220346542133250
13 2016-12-06 19:34:47 806220358881832960
...
         country coordinates.1 coordinates.2 coordinates.3 coordinates.4 coordinates.5 coordinates.6
1  United States    -106.64565    -106.64565     -93.50813     -93.50813      25.83709      36.50070
2  United States    -106.64565    -106.64565     -93.50813     -93.50813      25.83709      36.50070
3  United States    -106.64565    -106.64565     -93.50813     -93.50813      25.83709      36.50070
4  United States    -106.64565    -106.64565     -93.50813     -93.50813      25.83709      36.50070
5  United States    -106.64565    -106.64565     -93.50813     -93.50813      25.83709      36.50070
6  United States     -94.61771     -94.61771     -89.64484     -89.64484      33.00411      36.49977
7  United States    -106.64565    -106.64565     -93.50813     -93.50813      25.83709      36.50070
8  United States     -95.77470     -95.77470     -89.09884     -89.09884      35.99548      40.61364
9  United States    -106.64565    -106.64565     -93.50813     -93.50813      25.83709      36.50070
10 United States    -106.64565    -106.64565     -93.50813     -93.50813      25.83709      36.50070
11 United States     -95.77470     -95.77470     -89.09884     -89.09884      35.99548      40.61364
12 United States    -106.64565    -106.64565     -93.50813     -93.50813      25.83709      36.50070
13 United States    -106.64565    -106.64565     -93.50813     -93.50813      25.83709      36.50070
   coordinates.7 coordinates.8
1       36.50070      25.83709
2       36.50070      25.83709
3       36.50070      25.83709
4       36.50070      25.83709
5       36.50070      25.83709
6       36.49977      33.00411
7       36.50070      25.83709
8       40.61364      35.99548
9       36.50070      25.83709
10      36.50070      25.83709
11      40.61364      35.99548
12      36.50070      25.83709
13      36.50070      25.83709

```

**Comment by itsnickyjones** [comment]
Excellent! I will give it a whirl later today. Thanks for your prompt reply!

**Comment by itsnickyjones** [comment]
Hi again,

So I'm a little late in followup (end of quarter grading and a road trip, oops!) -- I have attempted to reinstall rtweet to the updated version but I get this error during install: 

* installing *source* package 'rtweet' ...
** R
** inst
** tests
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'fields'
ERROR: lazy loading failed for package 'rtweet'

*sacrifices carrot in thy name*

**Comment by mkearney** [comment]
Thanks for posting this. A dependency was missing from the rworldmap pkg, which I just added along with some other new plotting features, but that should now be fixed!

**Comment by mkearney** [comment]
Map plotting functions still in development, but to give you an idea of how cool the data are from streaming using geo locations.... 
- Over 1 million tweets on huge world map: http://mikewk.com/rtweetworld.png

**Comment by itsnickyjones** [comment]
First of all, you are amazing for being so responsive. Thanks for the
example image. Very exciting stuff!

I have attempted to install again but it now says that there is no package
called "spam".

Thanks again MWK!

**Comment by mkearney** [comment]
You just have good timing :). But thanks!

For now try doing this before attempting to install again:

    install.packages("rworldmap", dependencies = TRUE)

**Comment by itsnickyjones** [comment]
Hm. Still got the same error. I restarted the session after installing
rworldmap too...in case that matters!

**Comment by mkearney** [comment]
Well you can try installing that spam package too. Otherwise I'll see if I can fix it in the next hour or so!

**Comment by itsnickyjones** [comment]
10-4

**Comment by mkearney** [comment]
Woof these maps packages have a lot of baggage, but I just got it to successfully load on a PC, so I think it should be working now.

**Comment by itsnickyjones** [comment]
Awesome. I installed 'spam' and got it working. Thank you so much!
