### ISSUE TITLE
Error in lookup_users

### ISSUE THREAD

**Issue by wsamuelw** [mkearney/rtweet#44]
Here is the error message "Error in is.data.frame(x) : object 'usr' not found"

#Get follower IDs (This Twitter account has roughly 800 followers)
`followers = get_followers(user = "xyz") 
`

#Convert to DF (In preparation to get the last digit of the ID)
`followers_DF = as.data.frame(followers)
`

#Create last digit (The purpose is to break it down by last digit to find out the potential cause)
`library(stringr)
followers_DF$last_digit <- str_sub(followers_DF$ids, -1)`

#Transform num to char
`followers_DF$user_id = as.character(followers_DF$ids)`
```
table(followers_DF$last_digit)
# 0   1   2   3   4   5   6   7   8   9 
# 100  72 113  60  89  77  96  72  84  81 
```
#Lookup users
`users <- lookup_users(followers_DF$user_id)`
`Error in is.data.frame(x) : object 'usr' not found`

And, I have done a subset with the last digit = 0.

`zero <- lookup_users(subset(followers_DF, last_digit==0, select = user_id))`

Then, I received this error message. And, the count for 0 should be 100. Not sure how it is showing 93 and 92.
```
Error in `[[<-.data.frame`(`*tmp*`, "screen_name", value = c("gymibot",  : 
  replacement has 93 rows, data has 92
```

**Comment by mkearney** [comment]
Only have a min right now, so I'll look into this more later. But this worked for me:

```{r}
> followers = get_followers(user = "xyz")
> users <- lookup_users(followers$ids)
> NROW(users)
[1] 8239
```

**Comment by wsamuelw** [comment]
Thanks for looking into it. 

I've just tried running the same code above. I got the same error.

Error in is.data.frame(x) : object 'usr' not found

I've also re-install the package to find different things.

**Comment by mkearney** [comment]
Thanks for trying it. This has been a reoccurring issue with `lookup_users` (Twitter's API returns a slightly different status, or tweets, data object compared to other more status oriented functions). I'm actually in the process of overhauling all of the data parsing internals, so a patchwork solution isn't ideal.

One thing that should definitely work is to set the parse argument to false:

```{r}
users <- lookup_users(followers$ids, parse = FALSE)
```

That'll return a nested list object with all of the data; it's just not very friendly to work with. Then you can try parsing the structures individually:

```{r}
## preview tweets data
tweets_df(users) %>% head

## preview users data
users_df(users) %>% head
```

One of those may produce an error. If you're still looking for that data, then you can try installing the most recent CRAN version or wait until Monday or Tuesday, when I will have time to make sure it's working properly.

**Comment by wsamuelw** [comment]
Thanks again for looking into it.

I am still seeing the same error when running the code with parse = F.

```
followers = get_followers(user = "xyz")
users <- lookup_users(followers$ids, parse = FALSE)
```
Error in lookup_users(followers$ids, parse = FALSE) : 
  object 'usr' not found

I suspect that the error occurs when the list of IDs contains certain IDs. Not entirely sure if it is the right direction to look into further. 

Thanks again

**Comment by mkearney** [comment]
Okay, it should be working now. But I've changed the column name for the default return object. It is now `user_id` to make it consistent across the package.

```{r}
devtools::install_github("mkearney/rtweet")
library(rtweet)
followers <- get_followers(user = "xyz")
users <- lookup_users(followers$user_id)
head(users)
```

Or you can try out the new parser, which is exported but not yet integrated into functions by default yet.

```{r}
users <- lookup_users(followers$user_id, parse = FALSE)

## old parser
users.old <- users %>% parser
users.old %>% str

## new parser
users.new <- users %>% parse.piper

## preview users data
users.new %>% head

## preview tweets data
users.new %>% tweets_data %>% head
```
