### ISSUE TITLE
Can't seem to pass extra params to stream_tweets

### ISSUE THREAD

**Issue by seanchrismurphy** [mkearney/rtweet#45]
The steaming API supposedly takes extra parameters like lang - it would be nice to stream only english tweets. But there doesn't seem to be an input mechanism in stream_tweets that actually makes it through to the API call. Unless there's a way to format q such that it breaks into arguments?

**Comment by mkearney** [comment]
Tried a few things this morning, but I don't think there's a way to filter by language. You could filter the data after collection or geo coordinates to form a box around the US, but I'm afraid this may just be a limitation of the streaming API :/.

**Comment by seanchrismurphy** [comment]
I managed to get it working manually today. The streaming API does have a language filter, number four on the [list of parameters](https://dev.twitter.com/streaming/overview/request-parameters#replies). However, it has to by specified as "language = 'en'" rather than "lang = 'en'" as in the search API. 

The following code gives me only english tweets
```
params <- list(track = 'a', filter_level = 'low', language = 'en')
file_name <- (tempfile(fileext = ".json"))

response <- tryCatch(POST(url = rtweet:::make_url(restapi = FALSE, 'statuses/filter', param = params), config = rtweet:::check_token(NULL), write_disk(file_name,  overwrite = TRUE), progress(), timeout(10)), error = function(e) return(NULL))

response <- parse_stream(file_name, clean_tweets = FALSE, as_double = TRUE)
```
