### ISSUE TITLE
plyget not handling pages with missing response fields

### ISSUE THREAD

**Issue by seanchrismurphy** [mkearney/rtweet#47]
When a single page of results doesn't have data for a given field, the lapply call in plyget fails and returns NAs for all responses. This seems to most often be a problem for the geo-data, as the parse piper function almost uniformly returns all NAs for all coordinate data.

**Comment by mkearney** [comment]
Several outstanding issues created with the parser update. This fix and more should make it to Github tonight.

**Comment by mkearney** [comment]
Tho I'm sure it's possible this could come up again, for now I'm closing this until a more specific problem arises. The parser is now performing well with my current tests.
