### ISSUE TITLE
Tweets and users use the same created_at variable to mean different things

### ISSUE THREAD

**Issue by seanchrismurphy** [mkearney/rtweet#49]
This is partly a stylistic choice I suppose, but it seems like something you'd commonly want to do is extract user data from a set of tweets with users_data, then join the two data.frames together. This fails at the moment because they both use created_at, but one means the date the user account was created, while the other means the date the tweet was created.

**Comment by mkearney** [comment]
Yeah I've thought about that. I like to keep them separated, but most would probably want to be able to merge them easier. Either way, `created_at` could easily be misunderstood as the package is currently constructed. I guess I can change the users variable to `account_created_at`? Or if you have any other suggestions?

**Comment by seanchrismurphy** [comment]
I would almost change the naming of the tweet version, since it seems less obvious to think of tweets as being 'created'. Maybe tweets could be 'date_posted' and accounts could be 'date_created'? But if Twitter is returning them as 'created_at', maybe it does make sense to just append 'account_created_at' to one to minimize the change.
