### ISSUE TITLE
`search_tweets`

### ISSUE THREAD

**Issue by masalmon** [mkearney/rtweet#5]
Shouldn't

```r
  params <- list(q = q,
    result_type = type,
    count = 100,
    max_id = max_id,
    ...)
```

be

```r
  params <- list(q = q,
    result_type = type,
    count = n,
    max_id = max_id,
    ...)
```
?

**Comment by mkearney** [comment]
Max of any single draw is 100 and requests sometimes return one or two blanks, so I decided to hardwire count=100 to make burning another [resource limited] call less likely. The speed difference is negligible, so it seems okay to me. Can you think of another drawback I'm missing?

**Comment by masalmon** [comment]
Oh ok thanks, I misread it!
