### ISSUE TITLE
Rate limit handling with search API

### ISSUE THREAD

**Issue by seanchrismurphy** [mkearney/rtweet#50]
I was wondering if there are plans to build in rate limit handing to the search API, similar to what twitteR implemented, where the call is paused until the rate limit resets. Or do you intend this to be done with loops?

If the latter, do you think you'll implement error handling so that when the rate limit is exceeded, the current results are returned, rather than an error message without results?

Cheers!

**Comment by mkearney** [comment]
I'm not going to build-in a rate-limit sleeper function; instead the plan is to have documentation with examples on how to do it. 

And as for salvaging the data, I'm guessing you too have been burned by the big `search_tweets` call that took a few minutes to run before exceeding the rate limit and returning zilch? Yeah, I've been meaning to fix that for a while now. Sorry :/. But I can assure you it's burned me countless times lol. 

Regardless, you're right. There should be a warning message that at least says, "you've exceeded the rate limit." I suppose I could even include the cooldown time. In short term, the `rate_limit()` function should help you navigate rate limits.

**Comment by mkearney** [comment]
check = true is now default.
