### ISSUE TITLE
Rate limit for multiple tokens

### ISSUE THREAD

**Issue by Facj** [mkearney/rtweet#51]
First, I would like to thank you for your work! I find specially useful and convenient the possibility of saving several tokens together.
However, although tokens are correctly iterated over when included into an API call, I have found out that when rate_limit() is called, it returns the rate limit for the first of the tokens. As a result, the output may show 0 calls remaining where other of the tokens have still calls available.
As I need to do a large number of API calls, I would like to be able to check the total number of calls remaining (or at least if there are any left).
For instance, in this situation, rate_limit of the joint tokens returns the same output than rate_limit of the first one (0). However, the get_followers query is still successful because it makes use of the available calls for the second token.

>  twitter_token1 <- c(
>     create_token(app = "XXXXX", 
>                  consumer_key = "XXXXXXXX",
>                  consumer_secret = "XXXXXXXXXXX")
> )
> twitter_token2 <- c(
>     create_token(app = "XXXXXXXXX",
>                  consumer_key = "XXXXXXXX",
>                  consumer_secret = "XXXXXXXXXXXXXXX")
> )
> 
> twitter_tokens <- c(twitter_token1,twitter_token2)
> limit <- rate_limit(token = twitter_token1, query = "followers/ids", rest = TRUE)
> print(limit)
```
             query limit remaining         reset
1 followers/ids    15         0              4.124966 mins
```

> limit <- rate_limit(token = twitter_token2, query = "followers/ids", rest = TRUE)
> print(limit)
```
             query limit remaining         reset
1 followers/ids    15         15            14.98748 mins
```
> limit <- rate_limit(token = twitter_tokens, query = "followers/ids", rest = TRUE)
> print(limit)
```
             query limit remaining         reset
1 followers/ids    15         0              4.124966 mins
```
> followers <- get_followers("28918980",n=75000,page=-1,token=twitter_tokens)
> print(str(followers))
```
'data.frame':	75000 obs. of  1 variable:
$ user_id: chr  "636025446" "802811092346900480" "741213275522752512" "816567129382199296" ...
attr(*, "next_cursor")= num 1.5e+18
NULL

```

**Comment by mkearney** [comment]
I'm not sure if I'm exactly following, but perhaps you're looking for the `lapply()` function to get total remaining rate limit estimates?

```{r}
tokens <- get_tokens()
r <- lapply(tokens, rate_limit, "followers/ids")
r %>% 
    vapply(getElement, "remaining", double(1)) %>%
    sum(na.rm = TRUE)
```

**Comment by Facj** [comment]
Thank you again!
I had assumed rate_limit function could also be applied to a group of tokens, instead to only one of them at a time.

**Comment by mkearney** [comment]
Thanks for opening the issue! Feedback is always very appreciated!

(and it wouldn't be hard to make `rate_limit()` more friendly to multiple tokens, so I think I'll try to add that in future updates!)

**Comment by NataliaUC** [comment]
Hi!
I have been having trouble iterating among three tokens when calling the API. How can I do this?

Many thanks!
