### ISSUE TITLE
coordinate values jumbled from search_tweets

### ISSUE THREAD

**Issue by seanchrismurphy** [mkearney/rtweet#53]
While search_tweets does return coordinate values now, it appears to be putting the entire search's worth of coordinate values in each row of the resulting data.frame (i.e. each tweet has a vector of 100s of values for coordinates).

**Comment by mkearney** [comment]
i'm not getting this. you have code to replicate?

**Comment by seanchrismurphy** [comment]
Can't replicate it, but in the tests I just ran all I'm getting is NA in the coordinates column (after installing the latest version) so maybe that's why. But it's possible my version hasn't updated properly, I'll test when I get a chance.
