### ISSUE TITLE
Getting total rate limits

### ISSUE THREAD

**Issue by seanchrismurphy** [mkearney/rtweet#54]
Someone brought this up in a separate issue, that it would be useful to get the total rate limit when you have multiple tokens. I wrote this convenience function for myself that might be useful to roll into the package. It just sums remaining limits and takes the minimum of reset times (that is perhaps not perfect but at least tells you when one pool of limits will reset next)

```
tot_limits <- function(query = NULL, token = get_tokens()) {
  
  if (length(token) == 1) {
    limits <- rate_limit(token, query = query)
  } else {
    limits <- lapply(token, rate_limit, query = query)
    tot_limit <- do.call('cbind', limits)
    
    limits <- data.frame('query' = tot_limit[, 1], 'limit' = tot_limit[, 2], 'remaining' =
                           rowSums(tot_limit[, grep('remaining', colnames(tot_limit))]),
                         'reset' = do.call('pmin', tot_limit[, grep('reset', colnames(tot_limit))]))
  }
  return(limits)
}
```

Separate note, but it feels like rate_limit should check your first token by default. I.e. it seems odd that when I just call rate_limit() it fails. By default maybe it should work like rate_limit(get_tokens[1])?

**Comment by seanchrismurphy** [comment]
Building on that function, I've also found this convenience function useful to handle rate limiting - basically makes it much easier to write loops that respect the rate limit. Since you said you didn't want to build it in directly, this may help people implement it themselves. 

`control_rate_limit <- function(query = NULL, limit = NULL) {
    if(tot_limits(query)[['remaining']] < max(1, limit)) {
        print(paste0('sleeping for ', as.numeric(tot_limits(query = query)[1, 'reset']), ' minutes.'))
        Sys.sleep(as.numeric(tot_limits(query = query)[1, 'reset']))
    }
}`

**Comment by mkearney** [comment]
I'm starting to think I should just have a "waitforratelimit" option (or whatever twitteR called it). Not everyone is comfortable writing for loops and it can quickly get a bit complicated including break conditions, etc.

**Comment by seanchrismurphy** [comment]
I think that would be ideal - otherwise it will limit the scope of using the package to people who are using the streaming API or pretty comfortable with loop programming. On a similar front, an easy way to continue your search from where you left off (i.e. going backwards from the min id in your current set) would be helpful (twitteR did this if you searched for more than 18k tweets in one go).

**Comment by mkearney** [comment]
this is already offered with params like max_id. provisionally added this feature to `search_tweets` with `retryonratelimit` argument.
