### ISSUE TITLE
get_friends doesn't return a next_cursor attribute

### ISSUE THREAD

**Issue by seanchrismurphy** [mkearney/rtweet#55]
get_friends and get_followers both take a page argument so that you can use next_cursor to move to the next page. however, only get_followers actually returns an object with a next_cursor attribute. So the next_cursor function doesn't work for friends. The parse piper function for friends is much shorter than for followers (haven't had a chance to look any further into it) so I imagine that's the difference.

**Comment by mkearney** [comment]
This should be fixed now :)
