### ISSUE TITLE
get_timeline eats up rate limits

### ISSUE THREAD

**Issue by seanchrismurphy** [mkearney/rtweet#56]
The way get_timeline is written, it checks for the rate limit no matter how you call it. This means that if you want to get 200 tweets from each of 900 users (possible within a single 15 minute window based on the timeline rate limit) you're going to hit the limit after 180 because of constant calls to rate_limit. Not sure if there's a better way to do this? It was a problem in twitteR as well.

**Comment by mkearney** [comment]
Think I'm gonna standardize a check/checktoken arg that defaults to TRUE. What do you think?

**Comment by seanchrismurphy** [comment]
Yeah, that'd be a solid approach. I feel like this is a niche problem but would be nice to just be able to turn off the rate limit checks if you're doing it manually.
