### ISSUE TITLE
Issues with the lookup_users function

### ISSUE THREAD

**Issue by wsamuelw** [mkearney/rtweet#58]
Issue 1 - it skips some IDs e.g. 70688154XXXXXXXXXX and 74914597XXXXXXXXXX. Initially, I thought the function skips all this pattern i.e. IDs start with 7 in18 digit long. No. Some did pass thru fine. I have also tried doing a search by ID on some website to return a handle. Those ones that the function did not return did return error finding too. 

Issue 2 - the function doesn't return all followers. 

```
# Subset test 1 - select first 100 obs
followers_vt <- as.vector(followers$ids[c(1:100)])
```

```
Error in `[[<-.data.frame`(`*tmp*`, "screen_name", value = c("a_follower_handle_here",  : 
  replacement has 93 rows, data has 92
```

**Comment by mkearney** [comment]
I'm not able to replicate it. Can you try the most recent Github version and include your code so I can try to replicate?

The test I just ran worked fine.

```{r}
> library(rtweet)
Loading rtweet
Welcome to rtweet v0.3.93!
> rdt <- get_followers("realdonaldtrump", n = 75000)
> rdt$user_id %>%
+     unique() %>%
+     NROW()
[1] 74999
> usrs <- lookup_users(rdt$user_id[1:100])
> nrow(usrs)
[1] 85
```

The 15 users that weren't returned no longer exist (or, at least, their user ids are no longer associated with an account accessible through public Twitter).

**Comment by wsamuelw** [comment]
The v0.4.0! version is awesome! Issue fixed. Thanks again.
