### ISSUE TITLE
post_favorite function

### ISSUE THREAD

**Issue by wsamuelw** [mkearney/rtweet#61]
I think my app has got the right permission to read/write as the 2 functions below work fine for me.

```
post_unfollow_user()
post_tweet()
```

However, I received the following error message when running the post_favorite() function.

`something didn't work. are you using a token associated with *your* Twitter account? if so you may need to set read/write permissions or reset your token at apps.twitter.com.`

**Comment by mkearney** [comment]
So the actions were performed correctly but that error message printed out anyway?

**Comment by wsamuelw** [comment]
The functions post_unfollow_user() and post_tweet() performed correctly. So, I would assume that I have read/write permissions (which I have also checked app.twitter.com). The post_favorite() function did not perform correctly. The error message seems to be irrelevant if the above is true.

**Comment by mkearney** [comment]
I wrote sort of a catch all error message for post functions so I could get the update to CRAN faster. Thanks for reporting it! I'll try to figure out what's going on in the next day or two.
