### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by etancoigne** [mkearney/rtweet#62]
Hi,

I posted a few months ago some questions regarding your package. Thanks to your quick replies I was able to conduct a little research on Twitter and "citizen science". 
It is published on my team's research blog: http://citizensciences.net/2017/01/26/4-things-twitter-tells-us-about-citizen-science/
I thought you might be interested to get feedback!

Elise

**Comment by mkearney** [comment]
This is great! Thank you!
