### ISSUE TITLE
get_timeline doesn't allow for retrieving more than the last x tweets. 

### ISSUE THREAD

**Issue by MarkGannon** [mkearney/rtweet#63]
The get_timeline() function has the following example: 
`djt <- get_timeline("realDonaldTrump", n = 2000)`

Returns the first 1,999 tweets in the timeline.  

Any inclusion of the max_id parameter results in the following:
```
djt <- get_timeline("realDonaldTrump", n = 2000, max_id=5)
Error in x[[1]] : subscript out of bounds
```
Trying to use "since" or "since_id" produces a df with the latest 200 tweets ignoring the value for N.

**Comment by mkearney** [comment]
This should be fixed in the most recent version of rtweet. Try updating the package and see if the problem still happens. It worked for me (though I'm not quite sure why this didn't return 3200 rows...), but if the problem persists for you please let me know!

```
> install.packages("rtweet")
> djt <- get_timeline("realDonaldTrump", n = 3200)
> nrow(djt)
> [1] 3199
```

**Comment by MarkGannon** [comment]
Thanks for the quick response.    I'm sorry I wasn't as clear as I should have been.  The code you show works as you intended it to.  I get 3199 results.  I would like the ability to get all of the tweets in a timeline beyond the 3200 per individual query limit.  

The output from sessionInfo() reads: 
```
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Gentoo/Linux

locale:
 [1] LC_CTYPE=en_US.utf8       LC_NUMERIC=C             
 [3] LC_TIME=en_US.utf8        LC_COLLATE=en_US.utf8    
 [5] LC_MONETARY=en_US.utf8    LC_MESSAGES=en_US.utf8   
 [7] LC_PAPER=en_US.utf8       LC_NAME=C                
 [9] LC_ADDRESS=C              LC_TELEPHONE=C           
[11] LC_MEASUREMENT=en_US.utf8 LC_IDENTIFICATION=C      

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rtweet_0.4.0

loaded via a namespace (and not attached):
[1] httr_1.2.1    magrittr_1.5  R6_2.2.0      tools_3.3.2   curl_2.3     
[6] jsonlite_1.2  openssl_0.9.6

```

**Comment by mkearney** [comment]
Ahh I see. Unfortunately, 3200 is the limit for user timelines via Twitter's public REST API. However, if you're interested in getting all of Donald Trump's tweets, I created a [trumptweets repository](https://github.com/mkearney/trumptweets) with some functions for doing that.

**Comment by MarkGannon** [comment]
Great!  Thanks for the quick response!  Good luck with your PhD!
