### ISSUE TITLE
lookup_friendships error

### ISSUE THREAD

**Issue by pssguy** [mkearney/rtweet#64]
df <-lookup_friendships("pssGuy", parse = TRUE, token = NULL)
Error in fndshp[, c(1:2, 4, 6:10)] : incorrect number of dimensions

I'm using v 0.4.1 and have a token in the environment
tx

**Comment by mkearney** [comment]
Thanks for catching this. To be honest, I forgot that function existed. I believe that function is supposed to return friendship information for pairs of users. 

If you would like all of a user's friends, then try using the `get_friends()` function.

**Comment by pssguy** [comment]
Yep looking at [twitter API](https://dev.twitter.com/rest/reference/get/friendships/show) seems like you need both a target and source (user_id or screen-name) in the function

Could provide some useful info  on relationships, though
