### ISSUE TITLE
get_timeline error when using max_id home=TRUE

### ISSUE THREAD

**Issue by pssguy** [mkearney/rtweet#65]
```
jb_received <-get_timeline("JennyBryan",  max_id="830955495280275458",home=TRUE)
Error in rsp[[1]] : subscript out of bounds

jb_sent <-get_timeline("JennyBryan", n=10, max_id="830955495280275458",home=FALSE)
```
Data gets returned for latter command - although with 200, not 10,results; So n has a minimum, right?

BTW. Had you thought of splitting the home=TRUE/FALSE into two separate functions. They return completely different info, in contrast with the other parameters?

I'm using v 0.4.1

**Comment by mkearney** [comment]
For the first line of code, the max_id parameter will break the request if the ID is from older than 3200 tweets ago. It works for me if you exclude the max_id.

Using `lookup_statuses()`, I found the status ID you've used is not for the same user you've requested. If that was a retweet, then the ID would be associated with the original tweet.

The reasons for a somewhat clunky minimum are explained in [issue #60](https://github.com/mkearney/rtweet/issues/60).

**Comment by pssguy** [comment]
Thanks for swift reply
I was trying to obtain tweets received by a specific user ad infinitum so wanted to repeatedly use, a changing) max_id in calls until I had potentially all of them. I guess that is not feasible

There is no error  when removing the max_id but I get nowhere near 3200 (<800) from the past couple of days

Re the n=200. It was no problem as the data is received swiftly. I see you may be amending docs to clarify

Thanks for all the work you have done on the package
