### ISSUE TITLE
not possible to follow, unfollow

### ISSUE THREAD

**Issue by jcolomb** [mkearney/rtweet#68]
hi.

It seems the app do not have write permission, although I did give all permissions. Any clue?

    post_unfollow_user(testuser)

    something didn't work. are you using a token associated with *your* Twitter account? if so you may        need to set read/write permissions or reset your token at apps.twitter.com.
    Response [https://api.twitter.com/1.1/friendships/destroy.json?user_id=9437692&notify=FALSE]
       Date: 2017-03-07 15:59
      Status: 401
      Content-Type: application/json; charset=utf-8
      Size: 62 B

on the app.twitter.com:

> Access level Read, write, and direct messages (modify app permissions)
> Consumer Key (API Key) bCvJIidfPdffeFIj8bvtZwasE (manage keys and access tokens)
> Callback URL http://127.0.0.1:1410
> Callback URL Locked No
> Sign in with Twitter Yes
> App-only authentication https://api.twitter.com/oauth2/token
> Request token URL https://api.twitter.com/oauth/request_token
> Authorize URL https://api.twitter.com/oauth/authorize
> Access token URL https://api.twitter.com/oauth/access_token

**Comment by mkearney** [comment]
This is likely because the functions are defaulting to the built-in system token, which doesn't have write capabilities. Try `get_tokens()` and check to make sure the app name (see output below) and key (your should be ) match the token associated with your account.

```{r}
> rtweet::get_tokens()
<Token>
<oauth_endpoint>
 request:   https://api.twitter.com/oauth/request_token
 authorize: https://api.twitter.com/oauth/authenticate
 access:    https://api.twitter.com/oauth/access_token
<oauth_app> appnamefoundhere
  key:    Spuqrt5RsPOzHx9w8FjIXTgVW
  secret: <hidden>
<credentials> oauth_token, oauth_token_secret, user_id, screen_name, x_auth_expires
```

**Comment by jcolomb** [comment]
indeed this works:
    post_unfollow_user(testuser, token = twitter_token)

while rtweet::get_tokens() find 2 tokens...

**Comment by mkearney** [comment]
If get_tokens() doesn't return the token you created then you'll either have to include the token explicitly or save your token as an environment variable---instructions for which can be found here https://mkearney.github.io/rtweet/articles/auth.html.

**Comment by jcolomb** [comment]
I had to recreate token and had cached the first one without noticing,
trashing the cache file .httr-oauth did the trick.

thanks
