### ISSUE TITLE
Is it possible to sign in by providing access_token and access_secret instead of storing to hard drive?

### ISSUE THREAD

**Issue by DGaffney** [mkearney/rtweet#70]
Most other libraries allow you to explicitly pass in access_token and access_secret directly in order to log in, such as Ruby (https://github.com/sferik/twitter) and Python (https://github.com/bear/python-twitter) - is there a way to do this with rtweet, and if so, how do you do it? Looking around docs I haven't found a solution yet.

**Comment by mkearney** [comment]
Yes, the `create_token()` function allows you to create an object using those parameters and then you can specify that in any of the functions.
