### ISSUE TITLE
Search_users returns duplicates

### ISSUE THREAD

**Issue by maelle** [mkearney/rtweet#74]
When preparing my [blog post](http://www.masalmon.eu/2017/03/19/facesofr/) I used

```r
users <- search_users(q= '#rstats',
                      n = 1000,
                      parse = TRUE)
users <- unique(users)
```

I first got 1,000 rows but only about 455 unique ones or so. Is the output of duplicates an API issue?

Thanks :smile_cat:

**Comment by maelle** [comment]
I also wonder whether `search_users` searches tweets or profiles (the latter being my assumption), the package and API documentation are not clear regarding this :thinking:

**Comment by maelle** [comment]
For my second question now I now `search_users` searches profiles, maybe it should be clearer in the documentation?

Reference https://twitter.com/andypiper/status/843834564988600320

**Comment by andypiper** [comment]
On the Twitter API doc side, let me know what is unclear on the two endpoint pages; I cannot assistt with the R docs side of things. Thanks.

**Comment by maelle** [comment]
Thanks! Now that I think of it "Provides a simple, relevance-based search interface to public user accounts on Twitter." is quite clear @andypiper but maybe a few more details would be useful e.g. saying the fields that are searched are the profile description / the username?

@mkearney as regards the package doc now for `search_users` it is "Query to be searched, used in filtering relevant tweets
to return from Twitter's REST API.", I guess it was a bad copy-paste?

**Comment by maelle** [comment]
@andypiper if I can ask another thing, why does the API return some users several times instead of just once? With the query above for "#rstats" I got many duplicates.

**Comment by andypiper** [comment]
Hmm that's a good question. 

I'm not seeing the same thing using the base Twitter API. Here's an example command I just ran:

`twurl "/1.1/users/search.json?q=#rstats"  | jq '[.[] | {id: .id_str, name: .name, screen_name: .screen_name}]'`

I tried that with the first few pages of results and didn't see any duplicates.

**Comment by d4tagirl** [comment]
I have the same problem getting duplicate results:

```r 
a <- search_users(q = "#rstats",
                               n = 1000,
                               parse = TRUE)
> nrow(a)
[1] 1000

b <- unique(a)
> nrow(b)
[1] 516 
```

**Comment by mkearney** [comment]
It appears that rather than returning NULL/nothing, Twitter's search/users API returns last valid page of results. There were a handful of duplicates even when I compared the last two pages of results, so, in addition to cutting off the call once it starts getting redundant pages of information, a `unique` call is applied to both the users and [attributed] tweets data:

``` r
> users <- search_users(
+   q = '#rstats',
+   n = 1000,
+   parse = TRUE
+ )
Searching for users...
Finished collecting users!
> users
# A tibble: 549 x 20
      user_id               name    screen_name             location
        <chr>              <chr>          <chr>                <chr>
 1    5685812          boB Rudis       hrbrmstr Underground Cell #34
 2  295344317    One R Tip a Day       RLangTip                     
 3 4911181019 Statistician Jason    RStatsJason          Atlanta, GA
 4   24228154      Hilary Parker         hspter       San Francisco 
 5 2170413740    Baseball with R BaseballRstats                     
 6 2167059661        Jenny Bryan     JennyBryan        Vancouver, BC
 7  469960224 Emil OW Kirkegaard KirkegaardEmil        United States
 8   12640312        Daniel Pett        DEJPett              Θάλασσα
 9   46245868     David Robinson           drob         New York, NY
10  551600672           Kara Woo       kara_woo          Seattle, WA
# ... with 539 more rows, and 16 more variables: description <chr>, url <chr>,
#   protected <lgl>, followers_count <int>, friends_count <int>,
#   listed_count <int>, statuses_count <int>, favourites_count <int>,
#   account_created_at <dttm>, verified <lgl>, profile_url <chr>,
#   profile_expanded_url <chr>, account_lang <chr>, profile_banner <chr>,
#   profile_bg <chr>, profile_image <chr>
> nrow(unique(users))
[1] 549
```
