### ISSUE TITLE
error message when creating twitter token

### ISSUE THREAD

**Issue by Bluebell4090** [mkearney/rtweet#75]
Hi, I am getting the error "Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission,  : 
  Unauthorized (HTTP 401)." using the code suggested for rtweet.
  
  This is the code I have used:

install.packages("rtweet")
install.packages("httk")
install.packages("httr")
install.packages("httpuv")
install.packages("twitteR")
install.packages("devtools")
install.packages("base64enc")
install.packages("Rtools")

library(rtweet)
library(httk)
library(httr)
library(httpuv)
library(twitteR)
library(devtools)
library(base64enc)

devtools::install_github("mkearney/rtweet")

appname <- "ST4090Louise"
key <- "xxxxxx"
secret <- "xxxxxx"

twitter_token <- create_token(
	app = appname,
	consumer_key = key,
	consumer_secret = secret)

Any help would be appreciated. I've spent hours googling already and tried a few things but nothing is working.

Thank you!

**Comment by Btibert3** [comment]
Check that your appname, key, and secret are correct.  I was getting a similar error, but noted that when copy/paste from the Twitter app, there was an extra space in my key, which caused the error.

**Comment by lwasser** [comment]
hey @Bluebell4090 i had the same error - the fix for me was to set my callback url to http://127.0.0.1:1410 when setting up my API application in twitter. If you follow the library documentation they suggest to do that. worked for me. hope it works for you!

**Comment by nujcharee** [comment]
Hi there, I have the same problem. I believe my api key and secret are right as I tested in using library twitterR function setup_twitter_oauth(api_key,api_secret,access_token,access_token_secret) and that seemed tow ork but when I follow create_token function as per the above it keeps saying Unauthorized(401)

**Comment by mkearney** [comment]
If the callback is correct, some users have reported copying an extra space on accident. Which version of rtweet are you using? There have been some recent bug fixes as well, if you want to try the Github version.

**Comment by nujcharee** [comment]
It's the latest version (I installed it off cran last night)
Will check extra space thank you v much.
