### ISSUE TITLE
search_tweets result inconsistent

### ISSUE THREAD

**Issue by pabloxavje** [mkearney/rtweet#76]
Hi, I have a problem with search_tweets, sometimes I get a dataframe when I run this function but in other cases I get a list. It is a problem when I try to do some operations specifict for dataframes.

data_tweets <- search_tweets(buscar,n=18000, lang="en",
                             geocode=geoloca[2],
                             type="mixed", token = twitter_token)
class(data_tweets)
[1] "list"

data_tweets <- search_tweets(buscar,n=18000, lang="en",
                             geocode=geoloca[20],
                             type="mixed", token = twitter_token)
> class(data_tweets)
[1] "data.frame"

I hope you can helpme with this problem.

Best regards,
PJ

**Comment by mkearney** [comment]
The list is returned as a fail safe because there can be some inconsistencies in what data is returned. I think most of the sources of inconsistencies, though, should now be fixed.
