### ISSUE TITLE
implementation of direct messages

### ISSUE THREAD

**Issue by jcolomb** [mkearney/rtweet#77]
hi,
I used the twitteR to send dm, it seems as if it is not implemented in rtweet. did I miss it?

**Comment by mkearney** [comment]
I've got this working finally @jcolomb but I have a related question: were you able to upload media files while sending DMs using twitteR? I tried modifying the code that worked for uploading media to statuses but it didn't work, and I couldn't find any documentation about media attachments in DMs.

**Comment by jcolomb** [comment]
Never tried, When using media, I was creating a normal tweet and shared the tweet by dm.

Best

Dr. Julien Colomb
Neurobiologie
FU Berlin
