### ISSUE TITLE
Error with non-European tweets in unicode (easy fix with curl)

### ISSUE THREAD

**Issue by saudiwin** [mkearney/rtweet#78]
Hi --

I tried to search on an Arabic hashtag, and got a weird error from somewhere deep in the curl internals. After some searching, I found that Arabic can't be put into a URL/GET request without conversion using the `curl_escape()` command.

Thus, this gives an error:
```
hashtag1 <- 'ما_يتعداش'
all_tweets <- search_tweets(q=hashtag1,
                            token=token,
                            n=180)
```

Whereas this does not:

```
hashtag1 <- 'ما_يتعداش'
all_tweets <- search_tweets(q=curl::curl_escape(hashtag1),
                            token=token,
                            n=180)
```

**Comment by Crackz** [comment]
Check this:  https://github.com/mkearney/rtweet/issues/72
