### ISSUE TITLE
Extended tweets

### ISSUE THREAD

**Issue by CrowKing001** [mkearney/rtweet#81]
Not really an issue,  just a quick question. I noticed on twitter's dev API page that there are some planned changes specifically around freeing portions of the 140 character limit for common elements (like URL etc). Here's the page [Upcoming changes to Tweets](https://dev.twitter.com/overview/api/upcoming-changes-to-tweets).

When it goes live, will these changes be incorporated into rTweet? If so, any guidelines on future proofing code that uses rTweet today?

Thanks.

ck

**Comment by mkearney** [comment]
rtweet should already be adhering to those changes, but I'd like to explore how to maximize text returns a bit more. To date, I've opted to by default return the full text returned by Twitter. So long as that's still possible, there shouldn't need to be any change in the use of rtweet.
