### ISSUE TITLE
if_load() can never be TRUE

### ISSUE THREAD

**Issue by jsta** [mkearney/rtweet#9]
I am trying to store the my API key in `.Renviron` as recommended by the vignette. However, I am getting this error upon running any `rtweet` function that requires authentication:

>Error in if (if_load(pat)) { : argument is not interpretable as logical

It seems to me that the error is a result of the fact that `if_load()` can never be TRUE. I think this is only a problem if `identical(pat, ".httr-oauth")` is FALSE (see the `load_tokens` function).

**Comment by mkearney** [comment]
Ah yes that would be a problem. I added some authorization functions to make the transition from twitteR to rtweet easier, but clearly overlooked that possibility. Fixing it should be relatively easy, but this is symptomatic of a larger problem--being able to implement a variety of token/caching tests in Travis. Fortunately, I have a couple basic tests setup now, and unless there are major changes in Twitter's oauth process or the httr package, it should remain relatively stable.

**Comment by mkearney** [comment]
So I originally thought this was caused be a conflicting options() specification (e.g., setting global cache to FALSE) otherwise I would have fixed this right away. It's fixed now and I added a number of other token checking methods that should continue to make managing oauth stuff easier.
