### ISSUE TITLE
Allow Scraping of Untruncated Tweets

### ISSUE THREAD

**Issue by ajakubow** [mkearney/rtweet#91]
It would be great if you could specify an option to grab the full, extended tweets.  Take a look at the conversation here:  https://twittercommunity.com/t/retrieve-full-tweet-when-truncated-non-retweet/75542

It looks like an additional argument for  tweet_mode="extended" could be added to the function calls.  Easier said than done, I'm sure!  Thanks for such a great package!

**Comment by mkearney** [comment]
Extended Tweet mode is already in there. I'll setup some testing to ensure it works!

**Comment by mkearney** [comment]
Full text is now returned by default. Truncation may still occur on retweets or quotes so I've returned the `retweet_text` and `quoted_text` as well.

**Comment by ajakubow** [comment]
Wonderful. Thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
