### ISSUE TITLE
retweets function in twitteR

### ISSUE THREAD

**Issue by hussainshehadeh** [mkearney/rtweet#92]
Hello,

I was working on twitteR but now I changed to rtweet-package. I was wondering, is there any equivalent function to retweets (on the twitteR package), that can be used on rtweet?

**Comment by mkearney** [comment]
I've got it queued up, yes. You'll soon be able to get a list of IDs (retweeters) and/or retrieve the full data for each retweet. If twitteR had anything else though, please le me know!

**Comment by hussainshehadeh** [comment]
Hello, do you know how soon? Since I am using this for my thesis.

**Comment by mkearney** [comment]
I'll shoot for having it done by the end of this week!

**Comment by hussainshehadeh** [comment]
Thank you very much
