### ISSUE TITLE
creating a for loop to save each data in a separate file

### ISSUE THREAD

**Issue by hussainshehadeh** [mkearney/rtweet#99]
I am trying to take the list of users from a DataFrame, and then create a for loop to look for their followers. I want the followers for user 1,2,3,4..., but I don't want them to be saved in the same file. Here is the code, what am I missing?

```
## vector of users
users <- unique(dat$screen_name)

for(i in seq_along(users)){
  print(users[i])
  D <- get_followers(users[i], n= "all", page = "-1", parse = TRUE, token = NULL)
}
```

This is overwriting, so it deletes the first user followers, and write it over the 2nd and so on.

**Comment by mkearney** [comment]
This is good and very close working perfectly! With for loops, though, you need to preallocate space---or, at least, an object---that can store multiple different outputs.


``` r
## vector of users
users <- unique(dat$screen_name)

flw <- vector("list", length(users))

for(i in seq_along(users)){
  print(users[i])
  flw[[i]] <- get_followers(users[i], n= "all", page = "-1", parse = TRUE, token = NULL)
}
```

**Comment by mkearney** [comment]
Btw, I know there are reasons for keeping them, but just thought I'd mention that arguments in `get_followers` that are set to the default (page, parse, token) can be omitted.

``` r
## vector of users
users <- unique(dat$screen_name)

## output object
flw <- vector("list", length(users))

for(i in seq_along(users)){
  print(users[i])
  flw[[i]] <- get_followers(users[i], n= "all")
}
```

Also, once you have your output object from the for loop, you can collapse it into one data frame and save it. But if you decide to do this, then you'd want to have the user whose followers you've taken from identified with their respective followers. You can do this by creating another variable (column) in the for loop.

``` r
## vector of users
users <- unique(dat$screen_name)

flw <- vector("list", length(users))

for(i in seq_along(users)){
  print(users[i])
  flw[[i]] <- get_followers(users[i], n= "all", page = "-1", parse = TRUE, token = NULL)
  flw[[i]]$user <- users[i]
}

## collapse into single data frame
d <- do.call("rbind", flw)
```

Alternatively, you can save the whole list.

``` r
## name data frames using users so you can keep track of followers
names(flw) <- users

## save the whole list
saveRDS(flw, "followersofusers.rds")
```

Or save each data frame as it's own file

``` r
## csv
for (i in seq_along(users)) {
  write.csv(flw[[i]], file = paste0(users[i], "-followers.csv"), row.names = FALSE)
  cat("*")
}

## better version of csv
if (!"readr" %in% installed.packages()) {
  install.packages("readr")
}
for (i in seq_along(users)) {
  readr::write_csv(flw[[i]], path = paste0(users[i], "-followers.csv"))
  cat("*")
}

## as R data object (this is usual my preference)
for (i in seq_along(users)) {
  saveRDS(flw[[i]], file = paste0(users[i], "-followers.csv"))
  cat("*")
}
```

Which ever method you choose, but especially if it's saving to CSV files, make sure to check to make sure they are saving correctly. Since the user IDs are all numbers, it's possible they can be saved in scientific notation.

**Comment by hussainshehadeh** [comment]
I did this and it works fine 

```
## execute `i` loops (one for each obs in users) 
flws <- vector("list", length(users))
for (i in seq_along(users)) {
  print(users[i])
  ## get follows for user i
  flws[[i]] <- get_followers(users[i], n = "all", page = "-1", parse = TRUE, token = NULL)
  ## add user variable
  flws[[i]]$user <- users[i]
}

lapply(names(flws), function(x) {
  x1 <- flws[[x]]
  save(x1, file=paste0(getwd(),'/', x, '.RData'))
})

#Extracting the followers ids only
R <-  sapply(flws, "[[", 1)
R2 <- rbind.fill(lapply(R, as.data.frame))

#Combining the datasets
AA$id <- rownames(R) 
Followers <- melt(R)


#Loop for retweeters
rtwts <- vector("list", length(x))
for (i in seq_along(x)) {
  print(x[i])
  ## get retweeters for tweet i
  rtwts[[i]] <- search_tweets(x[i], n = 500)
  ## add retweets variable
  rtwts[[i]]$user <- x[i]
}

#Extracting the retweeters ids only
AA <-  sapply(rtwts, "[[", 1)

AA2 <- rbind.fill(lapply(AA, as.data.frame))

#Combining the datasets
AA$id <- rownames(AA) 
Retweeters <- melt(AA)

```

But this is combining all the users in one dataframe (but separating with with an extra column that identifies the user number, such as user 1 , 2 , 3 ...)

Is there a way were I can determine the number of users_ids (in retweeters) that overlaps with the user_ids (in Followers)? Taking into consideration to compare user 1 in retweeters with user 1 in followers and so on..
